### ISSUE TITLE
运行报错 

### ISSUE THREAD

**Issue by Skyer857** [Tencent/CodeAnalysis#10]
没注意需要先运行./compose_init.sh,在运行docker-compose up -d 中途通过ctrl+z中断后，删除docker容器重启运行./compose_init.sh有如下提示：./compose_init.sh: 7: Syntax error: "(" unexpected

**Comment by color-way** [comment]
sudo dpkg-reconfigure dash

**Comment by Skyer857** [comment]
> 须藤 dpkg-重新配置破折号

未解决
