### ISSUE TITLE
扫描报错。。。

### ISSUE THREAD

**Issue by AzuoHealer** [Tencent/CodeAnalysis#100]
![image](https://user-images.githubusercontent.com/39117380/149493791-ea6592dd-f757-48c0-ba52-53d654c54469.png)

**Comment by Lingghh** [comment]
可以看一下``file``服务目录下的日志，看看有什么报错

**Comment by AzuoHealer** [comment]
![image](https://user-images.githubusercontent.com/39117380/149689661-26b3b4ef-82d7-4f07-a8bd-6b0ff3f5700b.png)

**Comment by AzuoHealer** [comment]
重启了一下服务，还是连不上8004端口
![image](https://user-images.githubusercontent.com/39117380/149706567-1ff9d25d-b678-476d-b311-309f1bb9cca2.png)
![image](https://user-images.githubusercontent.com/39117380/149706597-f22f11e2-615b-4ca4-acab-c16445127b89.png)

**Comment by Lingghh** [comment]
这里是源码部署的么？File Server源码部署的端口号已经调整为 ``8804``，可以更新代码试试

**Comment by AzuoHealer** [comment]
源码部署的，我更新代码试一下。

**Comment by AzuoHealer** [comment]
更新完代码后可以正常扫描了。 @Lingghh
