### ISSUE TITLE
任务(AndroidLint)扫描失败: CompileTaskError: Error[210]: 编译语言项目执行静态分析需要输入编译命令，请填入编译命令后重试！

### ISSUE THREAD

**Issue by Pa55w0rd** [Tencent/CodeAnalysis#101]
java项目，检查规则开启了log4j漏洞，检测结束后会开启Task_37 (AndroidLint) starts ...
没有选择Android的规则
![image](https://user-images.githubusercontent.com/16274549/149498910-4e83d1ab-31a8-4823-b7f4-5429efeae7d2.png)

**Comment by cyw3** [comment]
麻烦截下分析方案中规则包和规则信息的图，这里看看是不是配置上用到的AndroidLint哈

**Comment by Pa55w0rd** [comment]
![1642387699(1)](https://user-images.githubusercontent.com/16274549/149700569-4fbd6329-48d8-4076-b9f0-24beca17bdff.png)

**Comment by cyw3** [comment]
这里【Java】减包扫描 规则包中用到了AndroidLint的规则，可以先关掉这个规则包看能不能执行哈

**Comment by Pa55w0rd** [comment]
> 这里【Java】减包扫描 规则包中用到了AndroidLint的规则，可以先关掉这个规则包看能不能执行哈

成功运行，谢谢
