### ISSUE TITLE
【需求】一个小细节， jenkins插件assert .hpi文件命名带上tca信息

### ISSUE THREAD

**Issue by XiaoQianYue** [Tencent/CodeAnalysis#1017]
建议将jenkins插件的文件名中带上tca等关键信息，若是单纯叫jenkins_plugin , 在jenkins后台的 plugin文件夹中去查看看不出这是哪一个插件。也存在被其他插件覆盖的风险。

![image](https://github.com/Tencent/CodeAnalysis/assets/92788228/ca152caf-0633-4787-b867-36fc9dd5da59)

![image](https://github.com/Tencent/CodeAnalysis/assets/92788228/cf8686a6-0db8-4f38-84d7-ac4332609909)

**Comment by bensonhome** [comment]
@XiaoQianYue 谢谢，是个好提议，我们后面改一下名字
