### ISSUE TITLE
【咨询】如何查看当前的扫描日志或是扫描状态

### ISSUE THREAD

**Issue by XiaoQianYue** [Tencent/CodeAnalysis#1019]
当前在扫描一个仓库（大小约2G），已耗时6小时，我尝试去找扫描日志，想看看这个任务是否在正常运行中。想要确认是否要继续等待。

![image](https://github.com/Tencent/CodeAnalysis/assets/92788228/5e669227-490c-49d8-9128-f8542793745d)

但找了一圈，发现不知道去哪里去看有效的日志。
已排查：
1. 界面上只有在扫描完才能下载
2. 管理入口应该是没有相关功能
3. docker logs 没有相关信息，是启动日志
4. 宿主机的CodeAnalysis/.docker_temp/logs 里面有一些，但是稍微翻了下，不太会看，不知道怎么去找到有效信息。

![image](https://github.com/Tencent/CodeAnalysis/assets/92788228/448ea7aa-ec56-4f08-ba76-08f1c00f0484)

**Comment by cyw3** [comment]
可以登陆对应的执行节点，找到 data/taskdir/ 下的编号最大的那个目录下，就有对应的task.log日志
