### ISSUE TITLE
团队管理禁用团队失败

### ISSUE THREAD

**Issue by wotrd** [Tencent/CodeAnalysis#1027]
后台管理下的团队管理，点击团队关闭按钮提示status缺失错误。

<img width="1643" alt="image" src="https://github.com/Tencent/CodeAnalysis/assets/33225215/6854874e-000d-4cbe-969f-4f84f9e5d1d0">

下面是请求报文：
curl 'http://x.x.x.x/server/main/api/v2/orgs/3vLeVrvTnL8/status/' \
  -X 'PUT' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Authorization: CodeDog eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA5OTY3OTMzLCJpYXQiOjE3MDk4ODE1MzMsImp0aSI6IjFjZWUwOWVkNjViNDQ3YTJiNDU5NDJlOGI4NTY2MmMyIiwidXNlcl9pZCI6IkNvZGVEb2cifQ.MeyErqykIJlDHRUz99_fgeo2cEJBsC7NcvJ7ez3tOsOEOe97O6i4MzLTRpsBXM3XOsU2Vch79gzhMGz266meoi4ag75BSJOLgR8m9ojWRhEO1cFfPoA80jqh_3qoiDXHe5SKBjcBNQZ8ePnvK5ju0vVyD31NoJglTwV1v5qDPXU' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Cookie: i18next=zh-CN' \
  -H 'Origin: http://x.x.x.x' \
  -H 'Referer: http://x.x.x.x/manage/orgs' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36' \
  -H 'X-Requested-With: XMLHttpRequest' \
  --data-raw '{}' \
  --insecure

**Comment by nickcdon** [comment]
已修复 #1028
