### ISSUE TITLE
任务(Rips开源版)扫描失败

### ISSUE THREAD

**Issue by Pa55w0rd** [Tencent/CodeAnalysis#105]
2022-01-17 10:30:46,693-INFO-util.logutil: Task_68 (Rips开源版) starts ...
2022-01-17 10:30:56,818-INFO-util.logutil: Task_68 is done.
2022-01-17 10:30:57,663-WARNING-node.localtask.runtask: 任务(Rips开源版)扫描失败: TaskError: Error[226]: 第三方工具执行异常,未生成结果文件: /opt/CodeAnalysis/client2/data/tools/rips-scanner/result.json
请查看本地日志文件(/opt/CodeAnalysis/client2/data/taskdirs/task_68/task.log),

**Comment by Pa55w0rd** [comment]
-2022-01-17 10:30:47,580-INFO-util.logutil: start to run task: Rips开源版, execute_processes: ['analyze', 'datahandle']
-2022-01-17 10:30:47,715-WARNING-task.taskmgr: 不是内置工具,使用自定义工具模块(No module named 'tool.rips')
-2022-01-17 10:30:47,718-INFO-task.taskmgr: task start : <class 'task.model.analyze.AnalyzeTask'>
-2022-01-17 10:30:47,719-INFO-task.sourcemgr: pre_analyze start.
-2022-01-17 10:30:47,719-INFO-task.sourcemgr: start __checkout_source_dir.
-2022-01-17 10:30:47,719-INFO-task.sourcemgr: __checkout_source_dir done. source_dir insert env. sourcedir: /opt/CodeAnalysis/code/DVWA
-2022-01-17 10:30:47,719-INFO-task.sourcemgr: pre_analyze done.
-2022-01-17 10:30:47,719-INFO-util.logutil: PATH =
****************************************************************************************************
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/root/bin
****************************************************************************************************
-2022-01-17 10:30:47,731-INFO-util.logutil: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
-2022-01-17 10:30:47,732-INFO-util.logutil: Codelint only cans main code.
-2022-01-17 10:30:47,803-INFO-util.logutil: Load from git to /opt/CodeAnalysis/client2/data/tools/rips-scanner ...
-2022-01-17 10:30:51,827-INFO-util.logutil: 获取需要扫描的文件
-2022-01-17 10:30:51,897-INFO-task.basic.common: /bin/sh: php: command not found
-2022-01-17 10:30:51,944-INFO-util.logutil: use SubProcController run cmd: php main.php
-2022-01-17 10:30:51,967-WARNING-task.puppytask: task status code is 226
-2022-01-17 10:30:51,967-WARNING-task.puppytask: task messsage: TaskError: Error[226]: 第三方工具执行异常,未生成结果文件: /opt/CodeAnalysis/client2/data/tools/rips-scanner/result.json
-2022-01-17 10:30:51,968-INFO-task.puppytask: task result: /opt/CodeAnalysis/client2/data/taskdirs/task_68/task_response.json

**Comment by Pa55w0rd** [comment]
-2022-01-17 10:43:39,650-INFO-util.logutil: start to run task: Rips开源版, execute_processes: ['analyze', 'datahandle']
-2022-01-17 10:43:39,689-WARNING-task.taskmgr: 不是内置工具,使用自定义工具模块(No module named 'tool.rips')
-2022-01-17 10:43:39,692-INFO-task.taskmgr: task start : <class 'task.model.analyze.AnalyzeTask'>
-2022-01-17 10:43:39,692-INFO-task.sourcemgr: pre_analyze start.
-2022-01-17 10:43:39,692-INFO-task.sourcemgr: start __checkout_source_dir.
-2022-01-17 10:43:39,692-INFO-task.sourcemgr: __checkout_source_dir done. source_dir insert env. sourcedir: /opt/CodeAnalysis/code/DVWA
-2022-01-17 10:43:39,692-INFO-task.sourcemgr: pre_analyze done.
-2022-01-17 10:43:39,692-INFO-util.logutil: PATH =
****************************************************************************************************
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/root/bin
****************************************************************************************************
-2022-01-17 10:43:39,692-INFO-util.logutil: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
-2022-01-17 10:43:39,692-INFO-util.logutil: Codelint only cans main code.
-2022-01-17 10:43:39,715-INFO-util.logutil: Load from git to /opt/CodeAnalysis/client2/data/tools/rips-scanner ...
-2022-01-17 10:43:41,664-INFO-util.logutil: 获取需要扫描的文件
-2022-01-17 10:43:41,721-INFO-task.basic.common: 											 	
-2022-01-17 10:43:41,721-INFO-task.basic.common: <div id="window1" name="window" style="width:600px; height:250px;">
-2022-01-17 10:43:41,721-INFO-task.basic.common: 	<div class="windowtitlebar">
-2022-01-17 10:43:41,721-INFO-task.basic.common: 		<div id="windowtitle1" onClick="toTop(1)" onmousedown="dragstart(1)" class="windowtitle"></div>
-2022-01-17 10:43:41,721-INFO-task.basic.common: 		<input id="maxbutton1" type="button" class="maxbutton" value="&nabla;" onClick="maxWindow(1, 800)" title="maximize" />
-2022-01-17 10:43:41,721-INFO-task.basic.common: 		<input type="button" class="closebutton" value="x" onClick="closeWindow(1)" title="close" />
-2022-01-17 10:43:41,721-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	<div style="position:relative;width:100%;">
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	<div id="scrolldiv">
-2022-01-17 10:43:41,722-INFO-task.basic.common: 		<div id="scrollwindow"></div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 		<div id="scrollcode"></div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	<div id="windowcontent1" class="windowcontent" onscroll="scroller()"></div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	<div style="clear:left;"></div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	<div id="return" class="return" onClick="returnLastCode()">&crarr; return</div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	<div class="windowfooter" onmousedown="resizeStart(event, 1)"></div>
-2022-01-17 10:43:41,723-INFO-task.basic.common: </div>
-2022-01-17 10:43:41,723-INFO-task.basic.common: 
-2022-01-17 10:43:41,723-INFO-task.basic.common: <div id="window2" name="window" style="width:600px; height:250px;">
-2022-01-17 10:43:41,723-INFO-task.basic.common: 	<div class="windowtitlebar">
-2022-01-17 10:43:41,723-INFO-task.basic.common: 		<div id="windowtitle2" onClick="toTop(2)" onmousedown="dragstart(2)" class="windowtitle"></div>
-2022-01-17 10:43:41,723-INFO-task.basic.common: 		<input type="button" class="closebutton" value="x" onClick="closeWindow(2)" title="close" />
-2022-01-17 10:43:41,723-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,724-INFO-task.basic.common: 	<div id="windowcontent2" class="windowcontent"></div>
-2022-01-17 10:43:41,724-INFO-task.basic.common: 	<div class="windowfooter" onmousedown="resizeStart(event, 2)"></div>
-2022-01-17 10:43:41,724-INFO-task.basic.common: </div>
-2022-01-17 10:43:41,724-INFO-task.basic.common: 
-2022-01-17 10:43:41,724-INFO-task.basic.common: <div id="window3" name="window" style="width:300px; height:300px;">
-2022-01-17 10:43:41,724-INFO-task.basic.common: 	<div class="funclisttitlebar">
-2022-01-17 10:43:41,724-INFO-task.basic.common: 		<div id="windowtitle3" onClick="toTop(3)" onmousedown="dragstart(3)" class="funclisttitle">
-2022-01-17 10:43:41,726-INFO-task.basic.common: 		user defined functions and calls
-2022-01-17 10:43:41,726-INFO-task.basic.common: 		</div>
-2022-01-17 10:43:41,727-INFO-task.basic.common: 		<input type="button" class="closebutton" value="x" onClick="closeWindow(3)" title="close" />
-2022-01-17 10:43:41,727-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,727-INFO-task.basic.common: 	<div id="windowcontent3" class="funclistcontent">
-2022-01-17 10:43:41,727-INFO-task.basic.common: 		<div >
-2022-01-17 10:43:41,727-INFO-task.basic.common: 			<input type="button" id="functionlistbutton" class="button" onclick="showlist('function');minWindow(3, 650);" value="list" style="background:white;color:black;" />
-2022-01-17 10:43:41,727-INFO-task.basic.common: 			<input type="button" id="functiongraphbutton" class="button" onclick="showgraph('function');maxWindow(3, 650);" value="graph"/>
-2022-01-17 10:43:41,727-INFO-task.basic.common: 			<input type="button" id="functioncanvassave" class="button" onclick="saveCanvas('functioncanvas', 3)" value="save graph" />
-2022-01-17 10:43:41,727-INFO-task.basic.common: 					</div>
-2022-01-17 10:43:41,727-INFO-task.basic.common: 		<div id='functiongraph_code' style='display:none'>document.getElementById('windowcontent3').innerHTML='No user defined functions found.'</div>
-2022-01-17 10:43:41,727-INFO-task.basic.common: 		<div id="canvas3" style="display:none"></div>
-2022-01-17 10:43:41,728-INFO-task.basic.common: 		<canvas id="functioncanvas" tabindex="0" width="650" height="200"></canvas>	
-2022-01-17 10:43:41,728-INFO-task.basic.common: 	</div>	
-2022-01-17 10:43:41,728-INFO-task.basic.common: 	<div class="funclistfooter" onmousedown="resizeStart(event, 3)"></div>
-2022-01-17 10:43:41,728-INFO-task.basic.common: </div>
-2022-01-17 10:43:41,728-INFO-task.basic.common: 
-2022-01-17 10:43:41,728-INFO-task.basic.common: <div id="window4" name="window" style="width:300px; height:300px;">
-2022-01-17 10:43:41,728-INFO-task.basic.common: 	<div class="funclisttitlebar">
-2022-01-17 10:43:41,728-INFO-task.basic.common: 		<div id="windowtitle4" onClick="toTop(4)" onmousedown="dragstart(4)" class="funclisttitle">
-2022-01-17 10:43:41,728-INFO-task.basic.common: 		user input
-2022-01-17 10:43:41,728-INFO-task.basic.common: 		</div>
-2022-01-17 10:43:41,728-INFO-task.basic.common: 		<input type="button" class="closebutton" value="x" onClick="closeWindow(4)" title="close" />
-2022-01-17 10:43:41,728-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,728-INFO-task.basic.common: 	<div id="windowcontent4" class="funclistcontent">
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		No userinput found.	</div>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 	<div class="funclistfooter" onmousedown="resizeStart(event, 4)"></div>
-2022-01-17 10:43:41,729-INFO-task.basic.common: </div>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 
-2022-01-17 10:43:41,729-INFO-task.basic.common: <div id="window5" name="window" style="width:300px; height:300px;">
-2022-01-17 10:43:41,729-INFO-task.basic.common: 	<div class="funclisttitlebar">
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		<div id="windowtitle4" onClick="toTop(5)" onmousedown="dragstart(5)" class="funclisttitle">
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		scanned files and includes
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		</div>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		<input type="button" class="closebutton" value="x" onClick="closeWindow(5)" title="close" />
-2022-01-17 10:43:41,729-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 	<div id="windowcontent5" class="funclistcontent">
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		<div >
-2022-01-17 10:43:41,729-INFO-task.basic.common: 			<input type="button" id="filelistbutton" class="button" onclick="showlist('file');minWindow(5, 650);" value="list" style="background:white;color:black;"/>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 			<input type="button" id="filegraphbutton" class="button" onclick="showgraph('file');maxWindow(5, 650);" value="graph"/>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 			<input type="button" id="filecanvassave" class="button" onclick="saveCanvas('filecanvas', 5)" value="save graph" />
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		</div>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 				<div id="canvas5" style="display:none"></div>
-2022-01-17 10:43:41,730-INFO-task.basic.common: 		<canvas id="filecanvas" tabindex="0" width="650" height="200"></canvas>
-2022-01-17 10:43:41,730-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,730-INFO-task.basic.common: 	<div class="funclistfooter" onmousedown="resizeStart(event, 5)"></div>
-2022-01-17 10:43:41,730-INFO-task.basic.common: </div>		
-2022-01-17 10:43:41,730-INFO-task.basic.common: 
-2022-01-17 10:43:41,730-INFO-task.basic.common: <div id="funccode" onclick="closeFuncCode()">
-2022-01-17 10:43:41,730-INFO-task.basic.common: 	<div id="funccodetitle" onmouseout="closeFuncCode()"></div>
-2022-01-17 10:43:41,730-INFO-task.basic.common: 	<div id="funccodecontent"></div>
-2022-01-17 10:43:41,730-INFO-task.basic.common: </div>
-2022-01-17 10:43:41,730-INFO-task.basic.common: 
-2022-01-17 10:43:41,730-INFO-task.basic.common: <div id="stats" class="stats">
-2022-01-17 10:43:41,730-INFO-task.basic.common: 	<table class="textcolor" width="100%">
-2022-01-17 10:43:41,730-INFO-task.basic.common: 		<tr>
-2022-01-17 10:43:41,731-INFO-task.basic.common: 			<th align="left" style="font-size:22px;padding-left:10px">Result</th>
-2022-01-17 10:43:41,731-INFO-task.basic.common: 			<th align="right"><input class="button" type="button" value="x" onClick="document.getElementById('stats').style.display='none';" title="close" /></th>
-2022-01-17 10:43:41,731-INFO-task.basic.common: 		</tr>
-2022-01-17 10:43:41,731-INFO-task.basic.common: 	</table>	
-2022-01-17 10:43:41,731-INFO-task.basic.common: 	<hr />	
-2022-01-17 10:43:41,731-INFO-task.basic.common: 	<table class="textcolor" width="100%">	
-2022-01-17 10:43:41,731-INFO-task.basic.common: <tr><td colspan="2" width="160">No vulnerabilities found.</td></tr></table><hr /><table class="textcolor" width="100%"><tr><td nowrap width="160" onmouseover="this.style.color='white';" onmouseout="this.style.color='#DFDFDF';" onClick="openWindow(5);eval(document.getElementById('filegraph_code').innerHTML);maxWindow(5, 650);" style="cursor:pointer;" title="open files window">Scanned files:</td><td nowrap colspan="2">0</td></tr><tr><td nowrap width="160">Include success:</td><td nowrap colspan="2">No includes.</td></tr><tr><td nowrap>Considered sinks:</td><td nowrap>0</td><td rowspan="4" ></td></tr><tr><td nowrap onmouseover="this.style.color='white';" onmouseout="this.style.color='#DFDFDF';" onClick="openWindow(3);eval(document.getElementById('functiongraph_code').innerHTML);maxWindow(3, 650);" style="cursor:pointer;" title="open functions window">User-defined functions:</td><td nowrap>0</td></tr><tr><td nowrap onmouseover="this.style.color='white';" onmouseout="this.style.color='#DFDFDF';" onClick="openWindow(4);" style="cursor:pointer;" title="open userinput window">Unique sources:</td><td nowrap>0</td></tr><tr><td nowrap>Sensitive sinks:</td><td nowrap>0</td></tr></table><hr /><center><a href="https://www.ripstech.com/latest/" target="_blank" style="text-decoration:none;font-size:11pt" onmouseover="this.style.color='white';" onmouseout="this.style.color='#DFDFDF';">Get the next generation of <font color="#FC4">RIPS</font><br />with state-of-the-art code analysis!</a></center><hr />		<table class="textcolor" width="100%">
-2022-01-17 10:43:41,731-INFO-task.basic.common: 		<tr><td nowrap width="160">Scan time:</td><td nowrap><span id="scantime">0.000 seconds</span></td></tr>
-2022-01-17 10:43:41,731-INFO-task.basic.common: 	</table>		
-2022-01-17 10:43:41,731-INFO-task.basic.common: 
-2022-01-17 10:43:41,731-INFO-task.basic.common: </div>
-2022-01-17 10:43:41,731-INFO-task.basic.common: 
-2022-01-17 10:43:41,731-INFO-task.basic.common: <div style="margin-left:30px;color:#000000">Nothing to scan. Please check your path/file name.</div>
-2022-01-17 10:43:41,843-INFO-util.logutil: use SubProcController run cmd: php main.php
-2022-01-17 10:43:41,847-WARNING-task.puppytask: task status code is 226
-2022-01-17 10:43:41,847-WARNING-task.puppytask: task messsage: TaskError: Error[226]: 第三方工具执行异常,未生成结果文件: /opt/CodeAnalysis/client2/data/tools/rips-scanner/result.json
-2022-01-17 10:43:41,848-INFO-task.puppytask: task result: /opt/CodeAnalysis/client2/data/taskdirs/task_80/task_response.json

**Comment by Pa55w0rd** [comment]
php -v
PHP 5.4.16 (cli) (built: Apr  1 2020 04:07:17) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

**Comment by owlmk** [comment]
![image](https://user-images.githubusercontent.com/28524442/149720646-7b6d02c4-287f-425a-8d2a-5eef623e6dd0.png)
请问这部分日志都是空的吗？/opt/CodeAnalysis/code/DVWA是否有php文件呢

**Comment by Pa55w0rd** [comment]
> ![image](https://user-images.githubusercontent.com/28524442/149720646-7b6d02c4-287f-425a-8d2a-5eef623e6dd0.png) 请问这部分日志都是空的吗？/opt/CodeAnalysis/code/DVWA是否有php文件呢

```
-2022-01-17 10:43:39,650-INFO-util.logutil: start to run task: Rips开源版, execute_processes: ['analyze', 'datahandle']
-2022-01-17 10:43:39,689-WARNING-task.taskmgr: 不是内置工具,使用自定义工具模块(No module named 'tool.rips')
-2022-01-17 10:43:39,692-INFO-task.taskmgr: task start : <class 'task.model.analyze.AnalyzeTask'>
-2022-01-17 10:43:39,692-INFO-task.sourcemgr: pre_analyze start.
-2022-01-17 10:43:39,692-INFO-task.sourcemgr: start __checkout_source_dir.
-2022-01-17 10:43:39,692-INFO-task.sourcemgr: __checkout_source_dir done. source_dir insert env. sourcedir: /opt/CodeAnalysis/code/DVWA
-2022-01-17 10:43:39,692-INFO-task.sourcemgr: pre_analyze done.
-2022-01-17 10:43:39,692-INFO-util.logutil: PATH =
****************************************************************************************************
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/root/bin
****************************************************************************************************
-2022-01-17 10:43:39,692-INFO-util.logutil: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
-2022-01-17 10:43:39,692-INFO-util.logutil: Codelint only cans main code.
-2022-01-17 10:43:39,715-INFO-util.logutil: Load from git to /opt/CodeAnalysis/client2/data/tools/rips-scanner ...
-2022-01-17 10:43:41,664-INFO-util.logutil: 获取需要扫描的文件
-2022-01-17 10:43:41,721-INFO-task.basic.common: 											 	
-2022-01-17 10:43:41,721-INFO-task.basic.common: <div id="window1" name="window" style="width:600px; height:250px;">
-2022-01-17 10:43:41,721-INFO-task.basic.common: 	<div class="windowtitlebar">
-2022-01-17 10:43:41,721-INFO-task.basic.common: 		<div id="windowtitle1" onClick="toTop(1)" onmousedown="dragstart(1)" class="windowtitle"></div>
-2022-01-17 10:43:41,721-INFO-task.basic.common: 		<input id="maxbutton1" type="button" class="maxbutton" value="&nabla;" onClick="maxWindow(1, 800)" title="maximize" />
-2022-01-17 10:43:41,721-INFO-task.basic.common: 		<input type="button" class="closebutton" value="x" onClick="closeWindow(1)" title="close" />
-2022-01-17 10:43:41,721-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	<div style="position:relative;width:100%;">
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	<div id="scrolldiv">
-2022-01-17 10:43:41,722-INFO-task.basic.common: 		<div id="scrollwindow"></div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 		<div id="scrollcode"></div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	<div id="windowcontent1" class="windowcontent" onscroll="scroller()"></div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	<div style="clear:left;"></div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	<div id="return" class="return" onClick="returnLastCode()">&crarr; return</div>
-2022-01-17 10:43:41,722-INFO-task.basic.common: 	<div class="windowfooter" onmousedown="resizeStart(event, 1)"></div>
-2022-01-17 10:43:41,723-INFO-task.basic.common: </div>
-2022-01-17 10:43:41,723-INFO-task.basic.common: 
-2022-01-17 10:43:41,723-INFO-task.basic.common: <div id="window2" name="window" style="width:600px; height:250px;">
-2022-01-17 10:43:41,723-INFO-task.basic.common: 	<div class="windowtitlebar">
-2022-01-17 10:43:41,723-INFO-task.basic.common: 		<div id="windowtitle2" onClick="toTop(2)" onmousedown="dragstart(2)" class="windowtitle"></div>
-2022-01-17 10:43:41,723-INFO-task.basic.common: 		<input type="button" class="closebutton" value="x" onClick="closeWindow(2)" title="close" />
-2022-01-17 10:43:41,723-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,724-INFO-task.basic.common: 	<div id="windowcontent2" class="windowcontent"></div>
-2022-01-17 10:43:41,724-INFO-task.basic.common: 	<div class="windowfooter" onmousedown="resizeStart(event, 2)"></div>
-2022-01-17 10:43:41,724-INFO-task.basic.common: </div>
-2022-01-17 10:43:41,724-INFO-task.basic.common: 
-2022-01-17 10:43:41,724-INFO-task.basic.common: <div id="window3" name="window" style="width:300px; height:300px;">
-2022-01-17 10:43:41,724-INFO-task.basic.common: 	<div class="funclisttitlebar">
-2022-01-17 10:43:41,724-INFO-task.basic.common: 		<div id="windowtitle3" onClick="toTop(3)" onmousedown="dragstart(3)" class="funclisttitle">
-2022-01-17 10:43:41,726-INFO-task.basic.common: 		user defined functions and calls
-2022-01-17 10:43:41,726-INFO-task.basic.common: 		</div>
-2022-01-17 10:43:41,727-INFO-task.basic.common: 		<input type="button" class="closebutton" value="x" onClick="closeWindow(3)" title="close" />
-2022-01-17 10:43:41,727-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,727-INFO-task.basic.common: 	<div id="windowcontent3" class="funclistcontent">
-2022-01-17 10:43:41,727-INFO-task.basic.common: 		<div >
-2022-01-17 10:43:41,727-INFO-task.basic.common: 			<input type="button" id="functionlistbutton" class="button" onclick="showlist('function');minWindow(3, 650);" value="list" style="background:white;color:black;" />
-2022-01-17 10:43:41,727-INFO-task.basic.common: 			<input type="button" id="functiongraphbutton" class="button" onclick="showgraph('function');maxWindow(3, 650);" value="graph"/>
-2022-01-17 10:43:41,727-INFO-task.basic.common: 			<input type="button" id="functioncanvassave" class="button" onclick="saveCanvas('functioncanvas', 3)" value="save graph" />
-2022-01-17 10:43:41,727-INFO-task.basic.common: 					</div>
-2022-01-17 10:43:41,727-INFO-task.basic.common: 		<div id='functiongraph_code' style='display:none'>document.getElementById('windowcontent3').innerHTML='No user defined functions found.'</div>
-2022-01-17 10:43:41,727-INFO-task.basic.common: 		<div id="canvas3" style="display:none"></div>
-2022-01-17 10:43:41,728-INFO-task.basic.common: 		<canvas id="functioncanvas" tabindex="0" width="650" height="200"></canvas>	
-2022-01-17 10:43:41,728-INFO-task.basic.common: 	</div>	
-2022-01-17 10:43:41,728-INFO-task.basic.common: 	<div class="funclistfooter" onmousedown="resizeStart(event, 3)"></div>
-2022-01-17 10:43:41,728-INFO-task.basic.common: </div>
-2022-01-17 10:43:41,728-INFO-task.basic.common: 
-2022-01-17 10:43:41,728-INFO-task.basic.common: <div id="window4" name="window" style="width:300px; height:300px;">
-2022-01-17 10:43:41,728-INFO-task.basic.common: 	<div class="funclisttitlebar">
-2022-01-17 10:43:41,728-INFO-task.basic.common: 		<div id="windowtitle4" onClick="toTop(4)" onmousedown="dragstart(4)" class="funclisttitle">
-2022-01-17 10:43:41,728-INFO-task.basic.common: 		user input
-2022-01-17 10:43:41,728-INFO-task.basic.common: 		</div>
-2022-01-17 10:43:41,728-INFO-task.basic.common: 		<input type="button" class="closebutton" value="x" onClick="closeWindow(4)" title="close" />
-2022-01-17 10:43:41,728-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,728-INFO-task.basic.common: 	<div id="windowcontent4" class="funclistcontent">
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		No userinput found.	</div>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 	<div class="funclistfooter" onmousedown="resizeStart(event, 4)"></div>
-2022-01-17 10:43:41,729-INFO-task.basic.common: </div>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 
-2022-01-17 10:43:41,729-INFO-task.basic.common: <div id="window5" name="window" style="width:300px; height:300px;">
-2022-01-17 10:43:41,729-INFO-task.basic.common: 	<div class="funclisttitlebar">
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		<div id="windowtitle4" onClick="toTop(5)" onmousedown="dragstart(5)" class="funclisttitle">
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		scanned files and includes
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		</div>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		<input type="button" class="closebutton" value="x" onClick="closeWindow(5)" title="close" />
-2022-01-17 10:43:41,729-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 	<div id="windowcontent5" class="funclistcontent">
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		<div >
-2022-01-17 10:43:41,729-INFO-task.basic.common: 			<input type="button" id="filelistbutton" class="button" onclick="showlist('file');minWindow(5, 650);" value="list" style="background:white;color:black;"/>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 			<input type="button" id="filegraphbutton" class="button" onclick="showgraph('file');maxWindow(5, 650);" value="graph"/>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 			<input type="button" id="filecanvassave" class="button" onclick="saveCanvas('filecanvas', 5)" value="save graph" />
-2022-01-17 10:43:41,729-INFO-task.basic.common: 		</div>
-2022-01-17 10:43:41,729-INFO-task.basic.common: 				<div id="canvas5" style="display:none"></div>
-2022-01-17 10:43:41,730-INFO-task.basic.common: 		<canvas id="filecanvas" tabindex="0" width="650" height="200"></canvas>
-2022-01-17 10:43:41,730-INFO-task.basic.common: 	</div>
-2022-01-17 10:43:41,730-INFO-task.basic.common: 	<div class="funclistfooter" onmousedown="resizeStart(event, 5)"></div>
-2022-01-17 10:43:41,730-INFO-task.basic.common: </div>		
-2022-01-17 10:43:41,730-INFO-task.basic.common: 
-2022-01-17 10:43:41,730-INFO-task.basic.common: <div id="funccode" onclick="closeFuncCode()">
-2022-01-17 10:43:41,730-INFO-task.basic.common: 	<div id="funccodetitle" onmouseout="closeFuncCode()"></div>
-2022-01-17 10:43:41,730-INFO-task.basic.common: 	<div id="funccodecontent"></div>
-2022-01-17 10:43:41,730-INFO-task.basic.common: </div>
-2022-01-17 10:43:41,730-INFO-task.basic.common: 
-2022-01-17 10:43:41,730-INFO-task.basic.common: <div id="stats" class="stats">
-2022-01-17 10:43:41,730-INFO-task.basic.common: 	<table class="textcolor" width="100%">
-2022-01-17 10:43:41,730-INFO-task.basic.common: 		<tr>
-2022-01-17 10:43:41,731-INFO-task.basic.common: 			<th align="left" style="font-size:22px;padding-left:10px">Result</th>
-2022-01-17 10:43:41,731-INFO-task.basic.common: 			<th align="right"><input class="button" type="button" value="x" onClick="document.getElementById('stats').style.display='none';" title="close" /></th>
-2022-01-17 10:43:41,731-INFO-task.basic.common: 		</tr>
-2022-01-17 10:43:41,731-INFO-task.basic.common: 	</table>	
-2022-01-17 10:43:41,731-INFO-task.basic.common: 	<hr />	
-2022-01-17 10:43:41,731-INFO-task.basic.common: 	<table class="textcolor" width="100%">	
-2022-01-17 10:43:41,731-INFO-task.basic.common: <tr><td colspan="2" width="160">No vulnerabilities found.</td></tr></table><hr /><table class="textcolor" width="100%"><tr><td nowrap width="160" onmouseover="this.style.color='white';" onmouseout="this.style.color='#DFDFDF';" onClick="openWindow(5);eval(document.getElementById('filegraph_code').innerHTML);maxWindow(5, 650);" style="cursor:pointer;" title="open files window">Scanned files:</td><td nowrap colspan="2">0</td></tr><tr><td nowrap width="160">Include success:</td><td nowrap colspan="2">No includes.</td></tr><tr><td nowrap>Considered sinks:</td><td nowrap>0</td><td rowspan="4" ></td></tr><tr><td nowrap onmouseover="this.style.color='white';" onmouseout="this.style.color='#DFDFDF';" onClick="openWindow(3);eval(document.getElementById('functiongraph_code').innerHTML);maxWindow(3, 650);" style="cursor:pointer;" title="open functions window">User-defined functions:</td><td nowrap>0</td></tr><tr><td nowrap onmouseover="this.style.color='white';" onmouseout="this.style.color='#DFDFDF';" onClick="openWindow(4);" style="cursor:pointer;" title="open userinput window">Unique sources:</td><td nowrap>0</td></tr><tr><td nowrap>Sensitive sinks:</td><td nowrap>0</td></tr></table><hr /><center><a href="https://www.ripstech.com/latest/" target="_blank" style="text-decoration:none;font-size:11pt" onmouseover="this.style.color='white';" onmouseout="this.style.color='#DFDFDF';">Get the next generation of <font color="#FC4">RIPS</font><br />with state-of-the-art code analysis!</a></center><hr />		<table class="textcolor" width="100%">
-2022-01-17 10:43:41,731-INFO-task.basic.common: 		<tr><td nowrap width="160">Scan time:</td><td nowrap><span id="scantime">0.000 seconds</span></td></tr>
-2022-01-17 10:43:41,731-INFO-task.basic.common: 	</table>		
-2022-01-17 10:43:41,731-INFO-task.basic.common: 
-2022-01-17 10:43:41,731-INFO-task.basic.common: </div>
-2022-01-17 10:43:41,731-INFO-task.basic.common: 
-2022-01-17 10:43:41,731-INFO-task.basic.common: <div style="margin-left:30px;color:#000000">Nothing to scan. Please check your path/file name.</div>
-2022-01-17 10:43:41,843-INFO-util.logutil: use SubProcController run cmd: php main.php
-2022-01-17 10:43:41,847-WARNING-task.puppytask: task status code is 226
-2022-01-17 10:43:41,847-WARNING-task.puppytask: task messsage: TaskError: Error[226]: 第三方工具执行异常,未生成结果文件: /opt/CodeAnalysis/client2/data/tools/rips-scanner/result.json
-2022-01-17 10:43:41,848-INFO-task.puppytask: task result: /opt/CodeAnalysis/client2/data/taskdirs/task_80/task_response.json

```

**Comment by Pa55w0rd** [comment]
> ![image](https://user-images.githubusercontent.com/28524442/149720646-7b6d02c4-287f-425a-8d2a-5eef623e6dd0.png) 请问这部分日志都是空的吗？/opt/CodeAnalysis/code/DVWA是否有php文件呢

这个是dvwa 靶场，存在php文件

**Comment by owlmk** [comment]
我本地用的是php5.6 和7.2版本还没遇到这问题， 刚更新了默认使用内置的php7.2进行分析，麻烦更新部署下再试试
