### ISSUE TITLE
localscan时可以取消代码统计任务吗？该任务结果似乎对MR扫描没有什么用，有点浪费时间

### ISSUE THREAD

**Issue by aaaa-j** [Tencent/CodeAnalysis#1051]
扫描命令是：
 python3 codepuppy.py localscan -t 000000 --org-sid EaHPm --team-name Xx -s /workspace/src --branch $gitlabSourceBranch --language C/C++ --scan-plan  $gitlabTargetBranch  --ref-scheme-id 59 --compare-branch $gitlabTargetBranch"
实际扫描3Min左右，但是代码统计似乎要花2min以上，从扫描结果来看不太清楚这个统计作用，似乎没啥用的样子，就有点浪费时间
![image](https://github.com/Tencent/CodeAnalysis/assets/70736600/871c535e-9227-43d1-82c4-2e218dbf280f)

**Comment by bensonhome** [comment]
@aaaa-j 这个是默认的代码量统计上报，作用是服务端可以按需统计一段时间内平台的扫描代码量情况。
如果觉得不需要，可以自行注释掉这部分上报逻辑，对应代码位置在：client/node/localtask/runlocaltask.py

**Comment by aaaa-j** [comment]
是不是删掉client/node/localtask/runlocaltask.py里的
74~91、131~133行就行了？

**Comment by bensonhome** [comment]
> 是不是删掉client/node/localtask/runlocaltask.py里的 74-91、131-133行就行了？

是的。

不会展示，可以从数据库捞数据。

**Comment by aaaa-j** [comment]
好嘞，谢谢benson老师！
