### ISSUE TITLE
关于扫描速度缓慢问题

### ISSUE THREAD

**Issue by uniquewdl** [Tencent/CodeAnalysis#1058]
企业内使用，数据积累越来越多，任务变得越来越慢，扫描失败率极高，TCA网站控制台加载缓慢问题

**Comment by uniquewdl** [comment]
超过半年的项目或一些代码库已经不存在的项目是否有清除？  这里不太确认删除哪些数据表，有些数据表数据量已打千万级别。

**Comment by Lingghh** [comment]
目前这一块不会自动删除，我们看看这一块可以怎么处理

**Comment by uniquewdl** [comment]
> 目前这一块不会自动删除，我们看看这一块可以怎么处理

嗯嗯，辛苦看下，应该能列一下哪些数据表可以清空，其中有部分存储组件相关的数据表达到千万级别，控制台页面基本无法正常响应。
