### ISSUE TITLE
同一个问题在不同的扫描id下会出现上一个扫描已经标注处理过，下次扫描又出现相同的问题

### ISSUE THREAD

**Issue by zzzfwww** [Tencent/CodeAnalysis#1060]
前端页面显示如下：
![cd225b0ae47f5ea5e82a89c9ae6c99b](https://github.com/Tencent/CodeAnalysis/assets/3351405/71edb671-687c-4f4f-a053-ca39d06a3a38)
![07c766224629a4b4ee69bbcc4df4fd6](https://github.com/Tencent/CodeAnalysis/assets/3351405/32676f40-ee13-44f0-84f0-5f32420ca241)
codelint_issue数据库里面对应到这两个扫描的数据信息如下：
![image](https://github.com/Tencent/CodeAnalysis/assets/3351405/291d78e6-d806-453a-a8b6-ac5d0cca78fd)

疑问：
现在对于一个标注已处理（在web页面标注）是用文件的hash值来决策？还是标注的代码片段的hash值？
试验结果：
发现可能是文件修改了，但是当前这段代码没修改，在页面标注的已解决，再下一次增量扫描还是会打开

所以想要请教一下官方这类问题是什么样的设计原则，是否可以修复这个问题

**Comment by zhang9w0v5** [comment]
是同一个分析项目，同一个分支吗？

**Comment by cyw3** [comment]
该问题已修复，麻烦更新代码重试下
