### ISSUE TITLE
代码库及账号不匹配

### ISSUE THREAD

**Issue by YeChenzjg** [Tencent/CodeAnalysis#1064]
TCA:源码部署
尝试了github gitee和自建svn代码库，git clone 和svn checkout 使用的账号和密码在tca平台上挂载代码库都提示账号不匹配
![image](https://github.com/Tencent/CodeAnalysis/assets/14322621/a846f015-f703-4bbb-a7b4-97a5f20dea2f)

**Comment by Lingghh** [comment]
可以看下 scmproxy 服务日志异常内容，看看是什么原因导致

**Comment by YeChenzjg** [comment]
![image](https://github.com/Tencent/CodeAnalysis/assets/14322621/32fe8226-e38e-4b6b-bb23-b00d74c46e86)
在scmproxy目录下面没有内容

**Comment by Lingghh** [comment]
这边是通过什么方式部署的呢？正常启动scmproxy是会有日志输出的，也可以检查下进程列表中是否有 proxyserver

**Comment by YeChenzjg** [comment]
windows10 WSL Ubuntu22.04 源码部署
```bash
root@XDRD-CHENYE-PC:/mnt/h/TCA/CodeAnalysis-main/server/projects/scmproxy/logs# ps aux | grep proxyserver
root      235880  0.0  0.0   4028  2024 pts/2    S+   10:08   0:00 grep --color=auto proxyserver
root@XDRD-CHENYE-PC:/mnt/h/TCA/CodeAnalysis-main/server/projects/scmproxy/logs#

**Comment by YeChenzjg** [comment]
解决了，WSL系统不要用Ubuntu，下个CentOS，直接用docker部署就行
