### ISSUE TITLE
查看问题列表 - 详细信息，提示账号密码错误

### ISSUE THREAD

**Issue by Pa55w0rd** [Tencent/CodeAnalysis#107]
![image](https://user-images.githubusercontent.com/16274549/149724979-d8fe7045-173e-4e16-a0ca-c3f8df1dee74.png)

**Comment by Lingghh** [comment]
该代码库登记的账号密码是否有变更过呢？

**Comment by Pa55w0rd** [comment]
> 代码库登记的账号密码是否有变更

仓库我删除了，，，这个不能在本地查找么，代码都同步到本地了
