### ISSUE TITLE
mac 当前环境不支持cobra工具步骤:['analyze']

### ISSUE THREAD

**Issue by Ferlick** [Tencent/CodeAnalysis#108]
![image](https://user-images.githubusercontent.com/18377219/149726538-ee1b1f2d-3914-4b30-b947-5521493bb5fc.png)

代码已重新拉过 server的服务也重新compose_init过 

根据#42的教程检测 也无误

![image](https://user-images.githubusercontent.com/18377219/149726784-bd2158ef-87d2-4ae1-8f02-8c2c9eb85407.png)

![image](https://user-images.githubusercontent.com/18377219/149727661-9071b873-2ea7-46ad-8d68-a1e2f5bd801e.png)

麻烦能否再给几个确认问题点的方式

**Comment by cyw3** [comment]
麻烦发下<TCA client>/data/taskdirs/下面的对应任务的task.log，这边好分析下

**Comment by Ferlick** [comment]
<TCA client>/data/ 下面只有tools的目录 没有所说的 taskdirs

![image](https://user-images.githubusercontent.com/18377219/149746798-f98abc9c-af6b-472e-a721-7125925cd6a5.png)

**Comment by cyw3** [comment]
那麻烦发下client localscan的报错信息哈

这个问题应该已经修复了 #89

**Comment by Ferlick** [comment]
![image](https://user-images.githubusercontent.com/18377219/149858428-af0b91f7-eb19-4dae-be41-1f6857b5287f.png)

这个是client localscan的报错信息

**Comment by cyw3** [comment]
从log里面没能看出cobra为何不支持执行。

https://github.com/Tencent/CodeAnalysis/blob/main/client/tool/cobra.py#L133

可以修改check_tool_usable函数，输出log试试
```python
    def check_tool_usable(self, tool_params):
        """
        这里判断机器上是否可以正常执行cobra脚本，不行的话便把任务发布给其他公线机器执行
        :return:
        """
        if SubProcController(["python", "--version"]).wait() != 0:
            return []
        if SubProcController(["python", "cobra.py", "--help"], cwd=os.environ.get("COBRA_HOME"), stdout_line_callback=self.print_log, stderr_line_callback=self.print_log).wait() != 0:
            LogPrinter.error(f"cobra不可用，建议:\n{self.install_steps}")
            return []
        return ["analyze"]

```

**Comment by Ferlick** [comment]
![image](https://user-images.githubusercontent.com/18377219/150057847-3f09cb04-678f-48e3-9b9b-fdf28ff5bee7.png)

这里加了些日志断点后 神奇的正常运行下去了 迷幻的本地环境

**Comment by Ferlick** [comment]
最后 建议client可以出一个 Docker镜像 这样应该会让很多因为本地环境而提的issue少很多

**Comment by Ferlick** [comment]
对哦 问题点分析还没交出来（毕竟光 日志断点 和 换行 肯定解决不了问题）

猜测
如果机器上有 python2 和 python3 的环境 ( 且mac是有系统文件夹保护的 不能强行给软链 只能在.zshrc 去做alias转换)
这里源代码中写的是 python 还是会去调取 python2 的命令 而导致cobra不能正常执行 有疑问的话可以在上面大佬给的对应代码块将python的命令执行打印出来，这样就会清晰很多

**Comment by Ferlick** [comment]
最后一个小小的建议

client可以出一个 Docker镜像 这样应该会让很多因为本地环境而提的issue少很多

**Comment by cyw3** [comment]
- python错乱的情况的话，这边可以考虑下，看是否需要直接指定为python3
- client制作docker镜像，是个好主意

也欢迎贡献，一起共建哈。
感谢建议!
