### ISSUE TITLE
扫描php项目，大概2000个文件，卡在(Rips开源版)这一步，没有报错信息，但是一直不出结果

### ISSUE THREAD

**Issue by jkl1994** [Tencent/CodeAnalysis#113]
2022-01-18 13:39:55,880-INFO-util.logutil: Task_653 (Rips开源版) starts ...

**Comment by owlmk** [comment]
这里系统是？

**Comment by jkl1994** [comment]
> 这里系统是？

内部的php项目,大概2000多个文件，执行扫描的时候，到调用Rips工具这一步，就一直卡住不动了，已经扫了3小时了
![image](https://user-images.githubusercontent.com/34265722/149907501-7bb2f32d-a840-4862-9cce-d849bc554fe4.png)

**Comment by Master-Kang** [comment]
完成一套thinkphp的代码需要多长时间呀  一直在分析中

**Comment by owlmk** [comment]
具体看了下，是这个工具性能不太行，先下掉了后续会考虑用我们自研工具替代掉
