### ISSUE TITLE
使用Jenkins插件配置流水线任务时遇到的问题

### ISSUE THREAD

**Issue by ec1iqse** [Tencent/CodeAnalysis#1150]
安装了[v1.10.0](https://github.com/Tencent/CodeAnalysis/releases/tag/20240621.1) 提供的[tca_jenkins_plugin.hpi](https://github.com/Tencent/CodeAnalysis/releases/download/20240621.1/tca_jenkins_plugin.hpi)插件后 在流水线内按照教程配置流水线后，运行时提示 "No such DSL method 'TCA_Builder' found among steps"，在流水线语法内也看不到TCA_Builder的用法
![QQ_1722222179768](https://github.com/user-attachments/assets/944a7051-9d66-4d77-9c9a-ed295494bcdf)

**Comment by zhuay-a** [comment]
release上的Jenkins插件目前还没有更新，启动命令稍有不同，具体格式为step([$class:'TCABuilder', codeAnalysisPath: '/user/CodeAnalysis/', teamId: 'xxxxx', projectName: 'demo', token: 'xxxxxxxxx', branchName: 'master', languageType: 'Java', refSchemeID: '1', scanPlan: 'model', threshold: '90', total:true])，减去了括号外的命令，括号内增加了一个class参数
