### ISSUE TITLE
源码部署v1.11.0版本，提示python-ldap失败

### ISSUE THREAD

**Issue by wotrd** [Tencent/CodeAnalysis#1167]
您好，我使用源码v1.11.0版本部署，提示python-ldap失败，具体报错信息如下，请问怎么解决？感谢！

![image](https://github.com/user-attachments/assets/cec7969d-7def-4b1b-8273-99cb2ed4e954)

**Comment by yyyangw** [comment]
参考Dockerfile中的EXTRA_TOOLS，用源码部署的话，你的机器上可能缺少必要的工具，可以先尝试手动安装下libsasl2-dev 、libldap2-dev 、libssl-dev 这三个工具。后续我们会对源码部署方式进行修复。

**Comment by wotrd** [comment]
已解决，感谢。
