### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by color-way** [Tencent/CodeAnalysis#12]
Traceback (most recent call last):
  File "codepuppy.py", line 18, in <module>
    from util.gitconfig import GitConfig
  File "/home/test/CodeAnalysis/client/util/gitconfig.py", line 10, in <module>
    from util.subprocc import SubProcController
ModuleNotFoundError: No module named 'util.subprocc'

**Comment by Lingghh** [comment]
这里是用什么python版本运行呢？
代码运行需要依赖python3.7版本

**Comment by color-way** [comment]
> 这里是用什么python版本运行呢？ 代码运行需要依赖python3.7版本

3.6.8不可以吗

**Comment by Lingghh** [comment]
暂时不支持3.6，可以再安装一个3.7.12版本试试

**Comment by cocorunning** [comment]
代码运行需要依赖python3.7版本
