### ISSUE TITLE
扫描 php   server端一直在进行中  5个小时后还是在进行中的状态

### ISSUE THREAD

**Issue by Master-Kang** [Tencent/CodeAnalysis#120]

**Comment by Master-Kang** [comment]
![image](https://user-images.githubusercontent.com/84483314/150245081-e48f7ffa-d704-4747-941d-f8fa5e0622bc.png)

**Comment by Lingghh** [comment]
这里麻烦提供一下client的执行日志，我们看一下什么原因

**Comment by Donny2g** [comment]
感觉是不是在拉取tool耗时比较久，我这也卡住了。尝试使用本地工具目录

**Comment by zhang9w0v5** [comment]
用本地工具还这样吗？

**Comment by cyw3** [comment]
可以更新下CodeAnalysis代码库，然后重新执行下./compose_init.sh，再重试下
这里应该是rips工具自身的性能问题，目前新版中不再设置rips为默认规则

#113
