### ISSUE TITLE
登记完gerrit仓库scm_url 格式错误，无法解析

### ISSUE THREAD

**Issue by AzuoHealer** [Tencent/CodeAnalysis#124]
![image](https://user-images.githubusercontent.com/39117380/150326753-7f3f7934-d42d-423d-b699-60c2e16b54f8.png)
![image](https://user-images.githubusercontent.com/39117380/150327008-c4536158-8ac9-43c6-b601-09f46eee92ca.png)
线上环境为gerrit仓库，可以登记，但是项目地址无法http访问，想知道这种怎么扫描。

**Comment by Donny2g** [comment]
应该可以在codedog.ini配置文件中指定source_dir的路径，在该路径下先将代码拉下来，之后执行扫码

**Comment by AzuoHealer** [comment]
我试过，拉下来也不行。
![image](https://user-images.githubusercontent.com/39117380/150328961-e0c12d72-c077-46d6-960c-e4cbc26a9283.png)

**Comment by AzuoHealer** [comment]
而且他这个工具就得拉下来才能扫描。 @Donny2g

**Comment by Lingghh** [comment]
这里看起来是识别代码库地址有问题，我们完善一下

**Comment by AzuoHealer** [comment]
@Lingghh 这个代码库地址我手动去web访问也是notfound

**Comment by Lingghh** [comment]
是指在浏览器访问http://grrit.xx/alg-target-rec会notfound么？

**Comment by AzuoHealer** [comment]
对，但是可以登记，也可以在终端clone。就是无法浏览器访问。

**Comment by Lingghh** [comment]
了解，我们完善一下

**Comment by AzuoHealer** [comment]
@Lingghh 目前这个问题有排期解决吗？

**Comment by Lingghh** [comment]
这个预计本月月底会支持上哈

**Comment by AzuoHealer** [comment]
好的。

**Comment by Lingghh** [comment]
@AzuoHealer 可以拉取最新代码试试

**Comment by AzuoHealer** [comment]
@Lingghh 已完成部署测试，目前没有问题了，就是节点分析的有点慢。。。
