### ISSUE TITLE
管理后台token或session失效后，可以下载codedog配置文件

### ISSUE THREAD

**Issue by Donny2g** [Tencent/CodeAnalysis#128]
管理后台token或session失效后，可以下载codedog配置文件

**Comment by zhang9w0v5** [comment]
@Donny2g 没太理解你指的下载codedog配置文件是什么？

**Comment by Donny2g** [comment]
启动分析-选择增量或全量分析后，会下载配置文件，文件名称叫codedog.ini

**Comment by bensonhome** [comment]
@Donny2g 这里遇到的问题是什么呢，有没有截图看一下？

**Comment by nickcdon** [comment]
@Donny2g 这里是指凭证失效后前端这块仍旧能够下载配置文件，但是文件内容显示401对吧？我们这边修复下哈。

**Comment by nickcdon** [comment]
已经修复，可以拉取最新代码，按照前端更新文档更新前端服务
