### ISSUE TITLE
CodeDog的密码初始密码是什么

### ISSUE THREAD

**Issue by yipeikk** [Tencent/CodeAnalysis#13]
![image](https://user-images.githubusercontent.com/50133499/148156627-6aee3598-c0df-4c50-af38-0e934e79b6d7.png)

**Comment by Lingghh** [comment]
admin

**Comment by nickcdon** [comment]
CodeDog

**Comment by nickcdon** [comment]
> CodeDog

admin

**Comment by Akityo** [comment]
这个readme里面居然没写，我是看了数据库密码，然后连进去看的，CodeDog/admin

**Comment by Lingghh** [comment]
谢谢提醒，已补充

**Comment by cocorunning** [comment]
目前初始密码已补充在readme中，初始密码为admin，感谢反馈。
