### ISSUE TITLE
自定义用户无用户管理权限

### ISSUE THREAD

**Issue by Donny2g** [Tencent/CodeAnalysis#138]
请问下如何查看用户表或用户权限?
我重新搭建了一套，使用自定义的用户名登录后，无法添加用户或进行用户管理。

**Comment by nickcdon** [comment]
@Donny2g 在用户管理里面将用户设置为超级管理员

**Comment by Donny2g** [comment]
@nickcdon  我之前是设置的超管的

![2821643080094_ pic](https://user-images.githubusercontent.com/2812644/150903771-b0d8959f-ba22-4eb4-9007-f9d910968fee.jpg)

**Comment by nickcdon** [comment]
@Donny2g 用之前CodeDog的这个账号创建的用户是有设置过超管吗？

**Comment by Donny2g** [comment]
默认账户是在配置文件中设置的，只改了用户名

**Comment by nickcdon** [comment]
目前内置了CodeDog作为超管，如果变更了用户名：

**Comment by nickcdon** [comment]
目前内置了CodeDog作为超管，如果变更了用户名：
方法一：在server/configs/django/local_main.py 的ADMINS中将该用户名加入，再执行 docker-compose exec main-server /bin/bash -c "python manage.py initializedb_open"
方法二：
```bash
docker-compose exec main-server /bin/bash
python manage.py shell
```
```python
from django.contrib.auth.models import User
User.objects.filter(username='用户名').update(is_staff=True, is_superuser=True)
```

**Comment by nickcdon** [comment]
目前这块确实流程上存在一定问题，我们几个单，后面优化调整下
