### ISSUE TITLE
开放平台API报错

### ISSUE THREAD

**Issue by Donny2g** [Tencent/CodeAnalysis#139]
调用开放平台API报错，截图如下。

ticket计算方式使用开放平台的示例代码：

```
user_id = 'admin'
token = 'c4d9dc7dcabc71ce8f096eccf6b4e2ef450db25e'
timestamp = int(time())
token_sig = "%s%s#%s#%s%s" % (timestamp, user_id, token, user_id, timestamp)
ticket = sha256(token_sig.encode("utf-8")).hexdigest().upper()
```
![2811643076510_ pic_hd](https://user-images.githubusercontent.com/2812644/150897969-2997b77e-3a58-4c8b-bddc-556d92a78453.jpg)

**Comment by nickcdon** [comment]
@Donny2g 感谢提醒，这块我们补上

**Comment by nickcdon** [comment]
@Donny2g 麻烦直接使用token访问，headers: {"Authorization": "Token xxx"}，我们变更下帮助文档开放API描述

**Comment by Donny2g** [comment]
Authorization使用界面上的token，还是计算后的ticket?

**Comment by nickcdon** [comment]
@Donny2g 已经更新了帮助文档，可以pull下来，重新start前端服务。界面上的token
