### ISSUE TITLE
客户端执行代码检测日志在哪里看呢？

### ISSUE THREAD

**Issue by yipeikk** [Tencent/CodeAnalysis#15]
![image](https://user-images.githubusercontent.com/50133499/148181934-9645052f-f79f-4dc6-b246-48e1a0c7abb6.png)

**Comment by BensonQin** [comment]
执行 python3 codepuppy.py localscan命令行终端会有日志输出的，看截图这里不太正常，是否中断了？

**Comment by yipeikk** [comment]
并没有中断 执行终端没有任何反馈就结束了

**Comment by yipeikk** [comment]
python版本是3.8

**Comment by Lingghh** [comment]
客户端依赖python 3.7版本运行，可以切换为python3.7版本试试
