### ISSUE TITLE
Interface in English and one report for all scans

### ISSUE THREAD

**Issue by marcinguy** [Tencent/CodeAnalysis#154]
Hi,

I have developed a similar solution to this called Scanmycode.

It has interface in English and one report.

It is also Open Source

https://github.com/marcinguy/scanmycode-ce

It unifies all findings in one report

Maybe you can make Code Analysis also in English and to show one report? 

Thanks,

**Comment by Lingghh** [comment]
Thank you for your suggestion. We will evaluate the implementation.
You can temporarily get analysis result by TCA API and generate a report.
