### ISSUE TITLE
Is there any direct way to upgrade while this project has so many bug fix merged into branch main?

### ISSUE THREAD

**Issue by yaohwu** [Tencent/CodeAnalysis#160]

**Comment by Lingghh** [comment]
It is recommended to directly pull code from branch mian at this stage.
Next we will regularly create release package.

**Comment by yaohwu** [comment]
I use docker-compose to deploy, when I want to upgrade, just pull code and reinit using compose_init.sh. 
Will the data be lost through this upgrade way?

**Comment by nickcdon** [comment]
@yaohwu The data has been mounted to the current directory, see docker-compose.yml for details

**Comment by yaohwu** [comment]
ok, thanks for your reply
