### ISSUE TITLE
代码安全

### ISSUE THREAD

**Issue by b3tterm4n** [Tencent/CodeAnalysis#165]
什么时候能上java代码安全的规则啊 准备拿来做SAST

**Comment by cocorunning** [comment]
有部分涉及商业版，还在研究和梳理。未来还会释放一些自研独有的独立工具和规则，还望多多支持，感谢！

**Comment by zhang9w0v5** [comment]
可以先把项目部署一下熟悉一下，下一个大版本会开放工具集成。全世界编程语言多，工具也很多，开放的工具集成方便大家将自己私有的工具集成使用（私有化部署，不会泄漏）。也方便自主升级或替换我们集成的工具。

**Comment by b3tterm4n** [comment]
部署确实挺费劲的 docker一键部署不成功 手动部署完碰到平台如何使用的问题  最好以后能有个用户手册😂

**Comment by Lingghh** [comment]
docker一键部署不成功

**Comment by zhang9w0v5** [comment]
在部署上我们也看了大家遇到的问题，确实问题集中在大家的各种网络环境（有的内网安全限制还是要靠诸位在内部走通），以及境外镜像仓库网络问题。
请放心，这块我们是积极收纳和完善迭代。

**Comment by b3tterm4n** [comment]
> docker一键部署不成功是遇到什么问题呢？方便发一下错误信息么

 一键部署脚本，除了redis和mysql两个镜像能够安装成功，其他的5个*-server全都报 

ERROR: Error processing tar file(exit status 1): unexpected EOF

 网上也没找到个确切的解决办法

**Comment by Lingghh** [comment]
@b3tterm4n 可以试一下这个操作，看看是什么问题哈：[Q&A文档](https://github.com/Tencent/CodeAnalysis/blob/main/doc/Q%26A.md#112-docker-compose%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5)

**Comment by b3tterm4n** [comment]
> @b3tterm4n 可以试一下这个操作，看看是什么问题哈：[Q&A文档](https://github.com/Tencent/CodeAnalysis/blob/main/doc/Q%26A.md#112-docker-compose%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5)

docker build -t xxx -f 具体位置/Dockerfile 这样按每个server装还是可以的 估计是脚本设置路径不对

**Comment by Akitata** [comment]
@zhang9w0v5 
@cocorunning 

您好，新版本预计什么时间能放出呢?

**Comment by aaaa-j** [comment]
预计在3月底release新版本~将上线任务分布式能力，项目动态敬请关注我们的微信公众号“腾讯云静态分析”，还可加入QQ交流群（361791391）一起讨论~ @Akitata
