### ISSUE TITLE
Error[204]: 不支持的语言类型: javanull

### ISSUE THREAD

**Issue by anyuan95** [Tencent/CodeAnalysis#179]
出现问题：
jenkins执行tca任务时，出现报错如下图：
![image](https://user-images.githubusercontent.com/28748124/158004241-b7e3e60c-95e3-4be9-9112-83450f671e8b.png)

操作步骤：
1.在windows上CodeAnalysis/plugins/jenkins_plugin下执行mvn clean package -DskipTests生成.hpi文件，通过jenkins页面进行插件上传安装；
2.在jenkins中配置PYTHONPATH和GITPATH环境变量;
3.创建新的jenkins job，配置文件见附件config.log（由于不允许上传xml所以后缀名改成log了）

tca源码版本：commit 3a3a9ec53b91acc50a8b11ecc3bc45e5c0e1147a
jenkins版本：2.284
python版本：3.7.12
[config.log](https://github.com/Tencent/CodeAnalysis/files/8237087/config.log)

**Comment by anyuan95** [comment]
![image](https://user-images.githubusercontent.com/28748124/158005815-5275c140-4af8-4174-b023-a7383177d6f2.png)

怀疑是因为这里没有勾选全量导致isTotal为null，导致拼装出了--language javanull ？
不清楚是否是我的jenkins版本的问题

https://github.com/Tencent/CodeAnalysis/blob/3a3a9ec53b91acc50a8b11ecc3bc45e5c0e1147a/plugins/jenkins_plugin/src/main/java/io/jenkins/plugins/StartClient.java#L42

**Comment by anyuan95** [comment]
#180

**Comment by bensonhome** [comment]
@anyuan95 是的，这里确实需要判空，感谢您的PR代码贡献！
欢迎继续关注TCA。
