### ISSUE TITLE
Docker-Compose启动失败

### ISSUE THREAD

**Issue by michael1981** [Tencent/CodeAnalysis#189]
启动Docker-Compose输出以下错误：
* Error response from daemon: Error processing tar file(exit status 1): unexpected EOF
* Error response from daemon: Error processing tar file(exit status 1): unexpected EOF
* Error response from daemon: Error processing tar file(exit status 1): unexpected EOF

**Comment by Lingghh** [comment]
目前使用的Docker-Compose版本是哪个呢？

**Comment by michael1981** [comment]
2.2.2版本

**Comment by Lingghh** [comment]
请问这里是在构建哪个服务时出现的报错呢？可以``cd``到 ``server/projects/``对应的服务目录中执行``docker build .``试试

**Comment by michael1981** [comment]
root@bogon analysis]# docker build .
Sending build context to Docker daemon   575 kB
Step 1/6 : FROM python:3.7.3
Trying to pull repository docker.io/library/python ... 
3.7.3: Pulling from docker.io/library/python
6f2f362378c5: Pull complete 
494c27a8a6b8: Pull complete 
7596bb83081b: Pull complete 
372744b62d49: Pull complete 
615db220d76c: Pull complete 
39aa0c89bda1: Pull complete 
ac275157d894: Pull complete 
98d16dec829a: Pull complete 
c8514b1c6524: Pull complete 
Digest: sha256:9e0b4f32487ca1863b45383420b8db77990debae748e2e875d2f86fa9510d4a5
Status: Downloaded newer image for docker.io/python:3.7.3
 ---> 34a518642c76
Step 2/6 : RUN apt-get update && apt-get install -y git subversion python-svn python-dev gcc svn-workbench mysql-client
 ---> [Warning] IPv4 forwarding is disabled. Networking will not work.
 ---> Running in 49c7093ae2bb

Err:1 http://deb.debian.org/debian stretch InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://security.debian.org/debian-security stretch/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:3 http://deb.debian.org/debian stretch-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python

E: Unable to locate package python-svn
E: Package 'python-dev' has no installation candidate
E: Unable to locate package svn-workbench
E: Unable to locate package mysql-client
The command '/bin/sh -c apt-get update && apt-get install -y git subversion python-svn python-dev gcc svn-workbench mysql-client' returned a non-zero code: 100

**Comment by Lingghh** [comment]
我们分析看看

**Comment by michael1981** [comment]
好的

**Comment by michael1981** [comment]
这边我开启ipv4暂时可以，但是Docker-Compose还是启动失败

**Comment by michael1981** [comment]
docker build .
Sending build context to Docker daemon 152.6 kB
Step 1/5 : FROM csighub.tencentyun.com/sdet2/python:3.7.9-slim
Trying to pull repository csighub.tencentyun.com/sdet2/python ... 
Get https://csighub.tencentyun.com/v1/_ping: dial tcp: lookup csighub.tencentyun.com on 192.168.5.2:53: no such host

**Comment by michael1981** [comment]
[root@localhost login]# docker build .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /opt/CodeAnalysis/server/projects/login/Dockerfile: no such file or directory

**Comment by michael1981** [comment]
[root@localhost projects]# cd main/
[root@localhost main]# docker build .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /opt/CodeAnalysis/server/projects/main/Dockerfile: no such file or directory

**Comment by michael1981** [comment]
[root@localhost scmproxy]# 
[root@localhost scmproxy]# docker build .
Sending build context to Docker daemon 12.62 MB
Step 1/5 : FROM python:3.7.9-slim
 ---> 95df6bf70e35
Step 2/5 : RUN mkdir -p /var/www/scmproxy
 ---> Using cache
 ---> 9bbc66c009a7
Step 3/5 : WORKDIR /var/www/scmproxy
 ---> Using cache
 ---> 00ec1ba4fed2
Step 4/5 : COPY ./ ./
 ---> Using cache
 ---> 9a9f822ae52f
Step 5/5 : RUN pip3 install -U setuptools &&     pip3 install -r requirements.txt &&     chmod u+x start.sh
 ---> Using cache
 ---> 69b55632f05a
Successfully built 69b55632f05a
[root@localhost scmproxy]#

**Comment by Lingghh** [comment]
谢谢反馈哈。
这里麻烦再启动一下docker-compose，然后执行``journalctl -u docker.service``看看有什么错误日志

**Comment by michael1981** [comment]
3月 22 09:52:24 bogon dockerd-current[2952]: chown: changing ownership of '.': Permission denied
3月 22 09:52:24 bogon oci-systemd-hook[36704]: systemdhook <debug>: fc6a3ddfdd00: Skipping as container command is docker-entryp
3月 22 09:52:24 bogon dockerd-current[2952]: time="2022-03-22T09:52:24.636157649+08:00" level=warning msg="fc6a3ddfdd0054675120d
3月 22 09:52:24 bogon dockerd-current[2952]: time="2022-03-22T09:52:24+08:00" level=info msg="Firewalld running: true"
3月 22 09:52:24 bogon oci-umount[36762]: umounthook <debug>: prestart container_id:aad00cce12d6 rootfs:/var/lib/docker/overlay2/
3月 22 09:52:24 bogon dockerd-current[2952]: chown: changing ownership of '/var/lib/mysql/': Permission denied
3月 22 09:52:24 bogon dockerd-current[2952]: time="2022-03-22T09:52:24.945173942+08:00" level=warning msg="aad00cce12d69847579b7
3月 22 09:52:29 bogon dockerd-current[2952]: time="2022-03-22T09:52:29.590705613+08:00" level=error msg="Handler for GET /v1.26/
3月 22 09:52:29 bogon dockerd-current[2952]: time="2022-03-22T09:52:29.593064616+08:00" level=error msg="Handler for GET /v1.26/
3月 22 09:52:29 bogon dockerd-current[2952]: time="2022-03-22T09:52:29.596480275+08:00" level=error msg="Handler for GET /v1.26/
3月 22 09:52:29 bogon dockerd-current[2952]: time="2022-03-22T09:52:29.596503774+08:00" level=error msg="Handler for GET /v1.26/
3月 22 09:52:29 bogon dockerd-current[2952]: time="2022-03-22T09:52:29.597385238+08:00" level=error msg="Handler for GET /v1.26/
3月 22 09:52:29 bogon dockerd-current[2952]: time="2022-03-22T09:52:29.597845419+08:00" level=error msg="Handler for GET /v1.26/
3月 22 09:52:29 bogon dockerd-current[2952]: time="2022-03-22T09:52:29.597929815+08:00" level=error msg="Handler for GET /v1.26/
3月 22 09:52:29 bogon dockerd-current[2952]: time="2022-03-22T09:52:29.598123007+08:00" level=error msg="Handler for GET /v1.26/
3月 22 09:52:29 bogon dockerd-current[2952]: time="2022-03-22T09:52:29.598881676+08:00" level=error msg="Handler for GET /v1.26/
3月 22 09:52:30 bogon dockerd-current[2952]: time="2022-03-22T09:52:30.181725109+08:00" level=error msg="Handler for POST /v1.26
3月 22 09:52:30 bogon dockerd-current[2952]: time="2022-03-22T09:52:30.229316752+08:00" level=error msg="Handler for POST /v1.26
3月 22 09:52:30 bogon dockerd-current[2952]: time="2022-03-22T09:52:30.771959339+08:00" level=error msg="Handler for POST /v1.26
3月 22 09:52:30 bogon dockerd-current[2952]: time="2022-03-22T09:52:30.832645343+08:00" level=error msg="Handler for POST /v1.26
3月 22 09:52:31 bogon dockerd-current[2952]: time="2022-03-22T09:52:31.120830792+08:00" level=error msg="Handler for POST /v1.26
3月 22 09:52:31 bogon dockerd-current[2952]: time="2022-03-22T09:52:31.402779598+08:00" level=error msg="Handler for POST /v1.26
3月 22 09:52:31 bogon dockerd-current[2952]: time="2022-03-22T09:52:31.480241013+08:00" level=error msg="Handler for POST /v1.26
3月 22 09:52:31 bogon dockerd-current[2952]: time="2022-03-22T09:52:31.767419804+08:00" level=error msg="Handler for POST /v1.26
3月 22 09:52:31 bogon dockerd-current[2952]: time="2022-03-22T09:52:31.822420742+08:00" level=error msg="Handler for POST /v1.26
3月 22 09:52:50 bogon dockerd-current[2952]: time="2022-03-22T09:52:50+08:00" level=info msg="Firewalld running: true"
3月 22 09:52:50 bogon dockerd-current[2952]: chown: changing ownership of '.': Permission denied
3月 22 09:52:50 bogon dockerd-current[2952]: time="2022-03-22T09:52:50.630857520+08:00" level=warning msg="fc6a3ddfdd0054675120d
3月 22 09:52:50 bogon dockerd-current[2952]: time="2022-03-22T09:52:50+08:00" level=info msg="Firewalld running: true"
3月 22 09:52:50 bogon oci-umount[37177]: umounthook <debug>: prestart container_id:aad00cce12d6 rootfs:/var/lib/docker/overlay2/
3月 22 09:52:50 bogon dockerd-current[2952]: chown: changing ownership of '/var/lib/mysql/': Permission denied
3月 22 09:52:50 bogon dockerd-current[2952]: time="2022-03-22T09:52:50.983356725+08:00" level=warning msg="aad00cce12d69847579b7
lines 1324-1363/1363 (END)

**Comment by Lingghh** [comment]
看日志应该是docker没有足够权限在当前目录下操作
```
chown: changing ownership of '.': Permission denied
changing ownership of '/var/lib/mysql/': Permission denied
```

可以试试给当前运行的用户或docker进程启动用户加一下整个项目目录的读写权限看看

**Comment by michael1981** [comment]
都root用户了，还没权限？

**Comment by michael1981** [comment]
3月 22 11:22:28 bogon dockerd-current[10650]: 2022-03-22T03:22:28.850849Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolv
3月 22 11:22:28 bogon dockerd-current[10650]: 2022-03-22T03:22:28.850890Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-reso
3月 22 11:22:28 bogon dockerd-current[10650]: 2022-03-22T03:22:28.852451Z 0 [Note] Failed to start slave threads for channel ''
3月 22 11:22:28 bogon dockerd-current[10650]: 2022-03-22T03:22:28.863699Z 0 [Note] Event Scheduler: Loaded 0 events
3月 22 11:22:28 bogon dockerd-current[10650]: 2022-03-22T03:22:28.864500Z 0 [Note] mysqld: ready for connections.
3月 22 11:22:28 bogon dockerd-current[10650]: Version: '5.7.24-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
3月 22 11:22:36 bogon dockerd-current[10650]: time="2022-03-22T11:22:36.045491018+08:00" level=error msg="Handler for GET /v1.26/images/codeanalysis_file-server/json 
3月 22 11:22:36 bogon dockerd-current[10650]: time="2022-03-22T11:22:36.104906094+08:00" level=error msg="Handler for POST /v1.26/build returned error: Error processi
3月 22 11:22:36 bogon dockerd-current[10650]: time="2022-03-22T11:22:36.160769208+08:00" level=error msg="Handler for GET /v1.26/images/codeanalysis_login-server/json
3月 22 11:22:36 bogon dockerd-current[10650]: time="2022-03-22T11:22:36.221090848+08:00" level=error msg="Handler for POST /v1.26/build returned error: Error processi
3月 22 11:22:36 bogon dockerd-current[10650]: time="2022-03-22T11:22:36.291430895+08:00" level=error msg="Handler for GET /v1.26/images/codeanalysis_analysis-server/j
3月 22 11:22:36 bogon dockerd-current[10650]: time="2022-03-22T11:22:36.358345176+08:00" level=error msg="Handler for POST /v1.26/build returned error: Error processi

**Comment by Lingghh** [comment]
docker进程也是用root用户启动的吗

**Comment by michael1981** [comment]
是的，都是root用户启动的

**Comment by Lingghh** [comment]
可以清理旧镜像以及重启Docker进程试试，另外可以将当前工程目录设置一下``chown -R root:root .``

咨询下哈，之前你应该是有通过docker-compose正常启动的吧？如果有，期间有做过什么变动么？因为这个问题不太好分析，想了解一下发生的场景哈

**Comment by michael1981** [comment]
有可能是虚拟机磁盘空间设置的问题，我重新安装一下试试。

**Comment by michael1981** [comment]
找到原因了，就是虚拟机磁盘空间设置小的问题

**Comment by Lingghh** [comment]
@michael1981 这里可以考虑跟我们一起完善Q&A文档哈~
