### ISSUE TITLE
[咨询] 是否有全局配置能够不创建REFERENCES

### ISSUE THREAD

**Issue by anyuan95** [Tencent/CodeAnalysis#191]
场景：由于REFERENCES会影响性能，所以我用的数据库中不被允许使用REFERENCES关键字。
我想咨询一下是否有全局配置的方式，能够在migrate时不创建REFERENCES？

**Comment by anyuan95** [comment]
另一个问题：是否考虑过用户将四个codedog_*数据库的数据合到一个数据库中？即在config.sh中把XX_DB_NAME都指定成同一个数据库？
我试了一下，失败了，出现了这样的报错：
[init_config.error.log](https://github.com/Tencent/CodeAnalysis/files/8314402/init_config.error.log)。

**Comment by Lingghh** [comment]
@anyuan95 目前暂时没有全局外键屏蔽方式，只能通过修改Django框架与工程内的migrations文件，调整为逻辑外键

目前不支持将所有服务的数据合并到一个数据库，不同服务会存在同名表格，运行会报错

**Comment by anyuan95** [comment]
谢谢解答。
