### ISSUE TITLE
与sonarqube有什么区别？在使用sonarQube的基础上继续使用CodeAnalysis？

### ISSUE THREAD

**Issue by jierui001** [Tencent/CodeAnalysis#2]
1、与sonarqube有什么区别？
2、在使用sonarQube的基础上继续使用CodeAnalysis？

**Comment by zhang9w0v5** [comment]
1. 与SonarQube是同类，技术细节差异不同。例如Sonar会存代码至数据库，近期暴露过泄漏代码的安全漏洞。TCA并不会存放代码。
2. TCA兼容SonarQube，以沙箱模式运行SonarQube，当然还有更多的重型工具也是这模式，例如著名的Coverity等等。TCA内带一系列国产自研的工具，内部迭代>9年，未来会逐渐释放工具。

**Comment by m7751991** [comment]
在扫描代码的速度上有区别么
