### ISSUE TITLE
请问不支持python的flake8？

### ISSUE THREAD

**Issue by kinghu88** [Tencent/CodeAnalysis#20]
当前环境不支持flake8工具步骤:['analyze'].
![image](https://user-images.githubusercontent.com/24669338/148318138-7c2450ae-14bb-428f-9788-6a7972df0151.png)

**Comment by bensonhome** [comment]
@kinghu88 当前环境和TCA自带的flake8不兼容，可以看之前的日志提示，看看是什么原因。
解决方法：通过pip3单独安装flake8: pip3 install flake8

**Comment by kinghu88** [comment]
好的
