### ISSUE TITLE
[咨询] ‘执行指定代码库指定分支项目扫描任务’接口未找到

### ISSUE THREAD

**Issue by anyuan95** [Tencent/CodeAnalysis#201]
下图中的这个接口是不是还没有提供？
该接口是已经废弃了还是仍在开发中？

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/28748124/160547390-1f358045-848e-47e7-9e6d-5362d2b8f0ec.png">

尝试调用时出现了以下的报错：
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/28748124/160548278-a303eaed-3290-45b1-bc11-58331a7eaa55.png">

**Comment by Lingghh** [comment]
这里可以更新一下main分支的代码，目前最新的代码已经支持任务下发
