### ISSUE TITLE
当前项目配置的运行环境标签

### ISSUE THREAD

**Issue by vindia9** [Tencent/CodeAnalysis#215]
环境：
OS：CentOS 7.x
Docker :20.10.14
docker-compose: 1.29.2
CodeAnalysis版本: v1.1.2
启动方式: 初次启动，命令为 ./compose_init.sh

问题描述：

添加项目并首次启动分析后，子任务全部执行失败。错误信息如下：

执行结果：配置错误 当前项目配置的运行环境标签[Codedog_Linux]没有机器资源可以运行工具[customfilescan(analyze);customfilescan(datahandle);customscan(analyze);customscan(datahandle);eslint(analyze);eslint(datahandle);eslint_vue(analyze);eslint_vue(datahandle);fbrjs(analyze);fbrjs(datahandle);semgrep(analyze);semgrep(datahandle);cpd(analyze);cpd(datahandle);lizard(analyze);lizard(datahandle);codecount(analyze);codecount(datahandle)]，请在扫描方案中调整"运行环境"的标签后重新启动。

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/9072630/161369345-2bb70883-57b3-4a8a-8e8c-7cc94b22f4cc.png">

**Comment by aaaa-j** [comment]
在线分析需要先配置节点资源，配置说明参考：https://github.com/Tencent/CodeAnalysis/blob/main/client/README.md#%E4%BA%94%E4%BD%BF%E7%94%A8%E5%88%86%E5%B8%83%E5%BC%8F%E8%8A%82%E7%82%B9%E6%A8%A1%E5%BC%8F%E6%89%A7%E8%A1%8C%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by vindia9** [comment]
谢谢，成功启动了
