### ISSUE TITLE
第三方工具执行异常,未生成结果文件

### ISSUE THREAD

**Issue by vindia9** [Tencent/CodeAnalysis#216]
环境：
OS：CentOS 7.x
Docker :20.10.14
docker-compose: 1.29.2
CodeAnalysis版本: v1.1.2
Python：3.7.12

问题描述：

扫描报错：执行结果：节点端本地扫描错误 TaskError: Error[226]: 第三方工具执行异常,未生成结果文件: /root/CodeAnalysis-20220402.1/client/../tools/custom-semgrep/result.json

**Comment by Lingghh** [comment]
可以发一下执行日志，我们分析下哈（执行日志可以在任务详情界面上下载）

**Comment by vindia9** [comment]
你好，以下是`semgrep`部分的日志

```
-2022-04-03 01:42:10,828-INFO-util.logutil: start to run task: Semgrep, execute_processes: ['analyze', 'datahandle']
-2022-04-03 01:42:10,859-INFO-util.logutil: USE_LOCAL_TOOL=True, use local tool dir: /root/CodeAnalysis-20220402.1/client/../tools/puppy-tools-config
-2022-04-03 01:42:10,859-INFO-util.logutil: 加载公共编译工具的环境变量...
-2022-04-03 01:42:10,898-INFO-util.logutil: USE_LOCAL_TOOL=True, use local tool dir: /root/CodeAnalysis-20220402.1/client/../tools/linux-scc
-2022-04-03 01:42:10,898-INFO-util.logutil: Initing 1 tools, please wait a minute ...
[Tools init]:   0%|                                                           | 0/1 [00:00<?, ?it/s]
[Tools init]: 100%|████████████████████████████████████████████████| 1/1 [00:00<00:00, 18724.57it/s]
-2022-04-03 01:42:10,902-INFO-util.logutil: Initialize tools done.(use time: 0.00s)
-2022-04-03 01:42:10,902-WARNING-task.taskmgr: 不是内置工具,使用自定义工具模块(No module named 'tool.semgrep')
-2022-04-03 01:42:10,904-INFO-task.taskmgr: task start : <class 'task.model.analyze.AnalyzeTask'>
-2022-04-03 01:42:10,904-INFO-task.sourcemgr: pre_analyze start.
-2022-04-03 01:42:10,904-INFO-task.sourcemgr: start __checkout_source_dir.
-2022-04-03 01:42:10,904-INFO-task.sourcemgr: 常规项目，直接拉取或复用本地缓存资源.
-2022-04-03 01:42:36,036-INFO-task.sourcemgr: load_source_dir done. source_dir insert env. sourcedir: /root/CodeAnalysis-20220402.1/client/data/sourcedirs/git_h0n8qfgc
-2022-04-03 01:42:36,037-INFO-task.sourcemgr: pre_analyze done.
-2022-04-03 01:42:36,038-INFO-util.logutil: PATH =
****************************************************************************************************
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/root/bin
****************************************************************************************************
-2022-04-03 01:42:36,038-INFO-util.logutil: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
-2022-04-03 01:42:36,038-INFO-util.logutil: Codelint only cans main code.
-2022-04-03 01:42:36,067-INFO-util.codecount.codestat: task params taskdir: /root/CodeAnalysis-20220402.1/client/data/taskdirs/task_123
-2022-04-03 01:42:36,483-INFO-util.logutil: [文件数]过滤前：12599，过滤后：12171
-2022-04-03 01:42:36,490-INFO-util.logutil: ['/root/CodeAnalysis-20220402.1/client/../tools/linux-scc/scc', '--by-file', '-c', '--no-cocomo', '-f', 'json', '-o', '/root/CodeAnalysis-20220402.1/client/data/taskdirs/task_123/scc_result_48aaa376b2ac11ecbf020017fa024aa3.json', '/root/CodeAnalysis-20220402.1/client/data/sourcedirs/git_h0n8qfgc']
-2022-04-03 01:42:36,495-WARNING-util.logutil: /bin/sh: /root/CodeAnalysis-20220402.1/client/../tools/linux-scc/scc: 没有那个文件或目录
-2022-04-03 01:42:36,591-ERROR-util.logutil: Scc run failed! Result file(/root/CodeAnalysis-20220402.1/client/data/taskdirs/task_123/scc_result_48aaa376b2ac11ecbf020017fa024aa3.json) not exist. Return empty result.
-2022-04-03 01:42:36,593-INFO-util.codecount.repoter: 上报代码行数: {'code_line_num': 0, 'comment_line_num': 0, 'blank_line_num': 0, 'total_line_num': 0, 'filtered_code_line_num': 0, 'filtered_comment_line_num': 0, 'filtered_blank_line_num': 0, 'filtered_total_line_num': 0, 'filtered_lang_count': {}}
-2022-04-03 01:42:50,170-INFO-util.logutil: USE_LOCAL_TOOL=True, use local tool dir: /root/CodeAnalysis-20220402.1/client/../tools/custom-semgrep
-2022-04-03 01:42:50,170-INFO-util.logutil: Use local tool dir: /root/CodeAnalysis-20220402.1/client/../tools/custom-semgrep
-2022-04-03 01:42:50,177-INFO-util.logutil: 正在设置CodeDog内置Python环境(PYTHON37_HOME)...
-2022-04-03 01:42:50,185-INFO-task.basic.common: Python 3.7.2
-2022-04-03 01:42:50,280-INFO-util.logutil: 获取需要扫描的文件
-2022-04-03 01:42:50,304-INFO-task.basic.common: python: can't open file 'main.py': [Errno 2] No such file or directory
-2022-04-03 01:42:50,381-INFO-util.logutil: use SubProcController run cmd: python main.py
-2022-04-03 01:42:50,382-WARNING-task.puppytask: task status code is 226
-2022-04-03 01:42:50,383-WARNING-task.puppytask: task messsage: TaskError: Error[226]: 第三方工具执行异常,未生成结果文件: /root/CodeAnalysis-20220402.1/client/../tools/custom-semgrep/result.json
-2022-04-03 01:42:50,383-INFO-task.puppytask: task result: /root/CodeAnalysis-20220402.1/client/data/taskdirs/task_123/task_response.json
```

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/9072630/161409856-f30f2b7e-754b-4ef1-84c7-0edaef77a545.png">

**Comment by vindia9** [comment]
另外，我发现离线tools实际使用的目录位于 `CodeAnalysis/tools/` 而非 `CodeAnalysis/client/data/tools`

<img width="799" alt="image" src="https://user-images.githubusercontent.com/9072630/161410044-d36ba1e9-7d69-4060-a283-65fe0cf3ebe9.png">

**Comment by owlmk** [comment]
> 另外，我发现离线tools实际使用的目录位于 `CodeAnalysis/tools/` 而非 `CodeAnalysis/client/data/tools`
> 
> <img alt="image" width="799" src="https://user-images.githubusercontent.com/9072630/161410044-d36ba1e9-7d69-4060-a283-65fe0cf3ebe9.png">

这个是最新更新将默认的工具路径改到了代码库根目录，便于后续上传自研工具

**Comment by yql70** [comment]
> 你好，以下是`semgrep`部分的日志
> 
> ```
> -2022-04-03 01:42:10,828-INFO-util.logutil: start to run task: Semgrep, execute_processes: ['analyze', 'datahandle']
> -2022-04-03 01:42:10,859-INFO-util.logutil: USE_LOCAL_TOOL=True, use local tool dir: /root/CodeAnalysis-20220402.1/client/../tools/puppy-tools-config
> -2022-04-03 01:42:10,859-INFO-util.logutil: 加载公共编译工具的环境变量...
> -2022-04-03 01:42:10,898-INFO-util.logutil: USE_LOCAL_TOOL=True, use local tool dir: /root/CodeAnalysis-20220402.1/client/../tools/linux-scc
> -2022-04-03 01:42:10,898-INFO-util.logutil: Initing 1 tools, please wait a minute ...
> [Tools init]:   0%|                                                           | 0/1 [00:00<?, ?it/s]
> [Tools init]: 100%|████████████████████████████████████████████████| 1/1 [00:00<00:00, 18724.57it/s]
> -2022-04-03 01:42:10,902-INFO-util.logutil: Initialize tools done.(use time: 0.00s)
> -2022-04-03 01:42:10,902-WARNING-task.taskmgr: 不是内置工具,使用自定义工具模块(No module named 'tool.semgrep')
> -2022-04-03 01:42:10,904-INFO-task.taskmgr: task start : <class 'task.model.analyze.AnalyzeTask'>
> -2022-04-03 01:42:10,904-INFO-task.sourcemgr: pre_analyze start.
> -2022-04-03 01:42:10,904-INFO-task.sourcemgr: start __checkout_source_dir.
> -2022-04-03 01:42:10,904-INFO-task.sourcemgr: 常规项目，直接拉取或复用本地缓存资源.
> -2022-04-03 01:42:36,036-INFO-task.sourcemgr: load_source_dir done. source_dir insert env. sourcedir: /root/CodeAnalysis-20220402.1/client/data/sourcedirs/git_h0n8qfgc
> -2022-04-03 01:42:36,037-INFO-task.sourcemgr: pre_analyze done.
> -2022-04-03 01:42:36,038-INFO-util.logutil: PATH =
> ****************************************************************************************************
> /usr/local/sbin
> /usr/local/bin
> /usr/sbin
> /usr/bin
> /root/bin
> ****************************************************************************************************
> -2022-04-03 01:42:36,038-INFO-util.logutil: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
> -2022-04-03 01:42:36,038-INFO-util.logutil: Codelint only cans main code.
> -2022-04-03 01:42:36,067-INFO-util.codecount.codestat: task params taskdir: /root/CodeAnalysis-20220402.1/client/data/taskdirs/task_123
> -2022-04-03 01:42:36,483-INFO-util.logutil: [文件数]过滤前：12599，过滤后：12171
> -2022-04-03 01:42:36,490-INFO-util.logutil: ['/root/CodeAnalysis-20220402.1/client/../tools/linux-scc/scc', '--by-file', '-c', '--no-cocomo', '-f', 'json', '-o', '/root/CodeAnalysis-20220402.1/client/data/taskdirs/task_123/scc_result_48aaa376b2ac11ecbf020017fa024aa3.json', '/root/CodeAnalysis-20220402.1/client/data/sourcedirs/git_h0n8qfgc']
> -2022-04-03 01:42:36,495-WARNING-util.logutil: /bin/sh: /root/CodeAnalysis-20220402.1/client/../tools/linux-scc/scc: 没有那个文件或目录
> -2022-04-03 01:42:36,591-ERROR-util.logutil: Scc run failed! Result file(/root/CodeAnalysis-20220402.1/client/data/taskdirs/task_123/scc_result_48aaa376b2ac11ecbf020017fa024aa3.json) not exist. Return empty result.
> -2022-04-03 01:42:36,593-INFO-util.codecount.repoter: 上报代码行数: {'code_line_num': 0, 'comment_line_num': 0, 'blank_line_num': 0, 'total_line_num': 0, 'filtered_code_line_num': 0, 'filtered_comment_line_num': 0, 'filtered_blank_line_num': 0, 'filtered_total_line_num': 0, 'filtered_lang_count': {}}
> -2022-04-03 01:42:50,170-INFO-util.logutil: USE_LOCAL_TOOL=True, use local tool dir: /root/CodeAnalysis-20220402.1/client/../tools/custom-semgrep
> -2022-04-03 01:42:50,170-INFO-util.logutil: Use local tool dir: /root/CodeAnalysis-20220402.1/client/../tools/custom-semgrep
> -2022-04-03 01:42:50,177-INFO-util.logutil: 正在设置CodeDog内置Python环境(PYTHON37_HOME)...
> -2022-04-03 01:42:50,185-INFO-task.basic.common: Python 3.7.2
> -2022-04-03 01:42:50,280-INFO-util.logutil: 获取需要扫描的文件
> -2022-04-03 01:42:50,304-INFO-task.basic.common: python: can't open file 'main.py': [Errno 2] No such file or directory
> -2022-04-03 01:42:50,381-INFO-util.logutil: use SubProcController run cmd: python main.py
> -2022-04-03 01:42:50,382-WARNING-task.puppytask: task status code is 226
> -2022-04-03 01:42:50,383-WARNING-task.puppytask: task messsage: TaskError: Error[226]: 第三方工具执行异常,未生成结果文件: /root/CodeAnalysis-20220402.1/client/../tools/custom-semgrep/result.json
> -2022-04-03 01:42:50,383-INFO-task.puppytask: task result: /root/CodeAnalysis-20220402.1/client/data/taskdirs/task_123/task_response.json
> ```
> 
> <img alt="image" width="1262" src="https://user-images.githubusercontent.com/9072630/161409856-f30f2b7e-754b-4ef1-84c7-0edaef77a545.png">
看到问题是找不到main.py，这个目录/root/CodeAnalysis-20220402.1/client/../tools/custom-semgrep是不是没有拉全呢，可以重新拉取一下[https://github.com/TCATools/custom-semgrep](https://github.com/TCATools/custom-semgrep)

**Comment by vindia9** [comment]
可以了，谢谢
