### ISSUE TITLE
单个project下的仓库过多时，仓库登记/分支项目/分析方案页面会无法正常展示内容

### ISSUE THREAD

**Issue by anyuan95** [Tencent/CodeAnalysis#222]
如下图所示，查看仓库登记/分支项目/分析方案页面时，都会通过多次分页查询的方式查询出完整的repo列表。
当project下仓库特别多（我在单个项目下创建了**约10000个仓库**）时，会导致页面内容无法正常展示。
是否考虑下添加一个分页功能？这个问题导致我**整个project下的扫描结果都无法通过页面正常访问**。
btw，即使我通过管理页面的分析记录列表中的分析记录链接直接跳转，也会出现相同的情况。

而且从图中可见，每条查询速度都很慢，想问下这是什么原因导致的呢？我在server主机上访问数据库查询单表速度很快。

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/28748124/162658999-1f7203fc-c21a-4b4d-a7d7-3101cc949fb0.png">

**Comment by Lingghh** [comment]
我们这里分析看看哈

**Comment by nickcdon** [comment]
@anyuan95 考虑到一个项目正常情况下代码库不会过多，建议拆分到不同项目中。请求速度很慢应该是请求量太大，负载高导致。

**Comment by anyuan95** [comment]
收到，我把项目拆分一下再试试。

不过，我理解，上图中的每次分页查询应该都是顺序执行而不是并行的吧？而且我出现该问题时，已经没有正在执行的扫描任务了，**不太明白'请求量太大'是指哪里的请求量**？

顺便，还是**建议**考虑调整一下加载方式？比如：仓库登记列表改为无限下拉方式（默认只加载100条）；分支项目/分支方案页面的代码库筛选栏默认显示100条，模糊匹配通过调用api查询方式进行？

**Comment by nickcdon** [comment]
@anyuan95 由于设计上最初没考虑到这种仓库过多的情况，这块我们后续会调整设计下哈。
