### ISSUE TITLE
请求部分api接口出现异常：should either include a `serializer_class` attribute, or override the `get_serializer_class()` method

### ISSUE THREAD

**Issue by anyuan95** [Tencent/CodeAnalysis#225]
请求以下接口出现错误信息：
- API接口/代码度量数据模块接口.html#查看指定项目的文件行数列表
- API接口/代码度量数据模块接口.html#查看指定项目的语言列表

异常信息：
[2022-04-12T122339.500.html.txt](https://github.com/Tencent/CodeAnalysis/files/8470038/2022-04-12T122339.500.html.txt)
[2022-04-12T141024.500.html.txt](https://github.com/Tencent/CodeAnalysis/files/8470039/2022-04-12T141024.500.html.txt)

代码版本：main, eb37b97e

**Comment by anyuan95** [comment]
顺便，我在server的config.sh文件中指定了`export MAIN_DEBUG_MODE=false`，为什么报错时还是会出现django的debug页面呢？

**Comment by Lingghh** [comment]
感谢反馈，我们处理下哈

**Comment by Lingghh** [comment]
> 

调整之后是否有重启服务呢？

**Comment by Lingghh** [comment]
> 顺便，我在server的config.sh文件中指定了`export ANALYSIS_DEBUG_MODE=false`，为什么报错时还是会出现django的debug页面呢？

调整之后是否有重启服务呢

**Comment by Lingghh** [comment]
> 感谢反馈，我们处理下哈

问题已修复，可以拉取最新代码使用

**Comment by anyuan95** [comment]
> > 顺便，我在server的config.sh文件中指定了`export ANALYSIS_DEBUG_MODE=false`，为什么报错时还是会出现django的debug页面呢？
> 
> 调整之后是否有重启服务呢

有重启，而且去服务器上看了配置文件，里面已经是false了

**Comment by Lingghh** [comment]
> > > 顺便，我在server的config.sh文件中指定了`export ANALYSIS_DEBUG_MODE=false`，为什么报错时还是会出现django的debug页面呢？
> > 
> > 
> > 调整之后是否有重启服务呢
> 
> 有重启，而且去服务器上看了配置文件，里面已经是false了

这里可以进到analysis shell模式：

- 切换到``server``目录下，执行``source scripts/config.sh``
- 切换到``server/projects/analysis``目录下，执行``python manage.py shell``
- 输入以下代码看看
```Python
from django.conf import settings
print(settings.DEBUG) # 如果为False，表示配置生效，关闭Debug模式
```

如果不生效，可以重启一下服务：

- 切换到``server``目录下，执行``source scripts/deploy.sh start``

**Comment by anyuan95** [comment]
> ```python
> print(settings.DEBUG)
> ```

我通过shell模式查了下，输出的配置确实是false
```
[sankuai@set-xr-ed-wca-server-test02 analysis]$ python manage.py shell
-2022-04-14 11:29:22,891-DEBUG-asyncio: Using selector: EpollSelector
Python 3.7.0 (default, Apr  1 2022, 19:28:02)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.conf import settings
>>> print(settings.DEBUG)
False
```

然后重启了服务，再请求一个不存在的api接口，还是出现了debug页面
```
<div id="explanation">
    <p>
        You're seeing this error because you have <code>DEBUG = True</code> in
        your Django settings file. Change that to <code>False</code>, and Django
        will display a standard 404 page.
    </p>
</div>
```

**Comment by Lingghh** [comment]
这个接口路径能否发一下

**Comment by anyuan95** [comment]
> 这个接口路径能否发一下

我就是在/codemetric/cloclangs/接口后面随便加了一段
```
GET http://10.24.37.243:8000/analysis/api/orgs/7cNyU90vRnn/teams/waimqa/repos/12765/projects/9284/codemetric/cloclangs/aaa
Authorization: Token 0712b895f30c5e958ec71a7c22e1b1a2ad1d5c6b
```

**Comment by Lingghh** [comment]
这里没有复现出来..

这里访问的地址是否你调整过配置的服务部署地址呢？
重启server后可以执行``ps aux | grep analysis.gunicorn.conf.py``看看对应的进程启动时间是否为刚操作的时间

**Comment by anyuan95** [comment]
> 这里没有复现出来..
> 
> 这里访问的地址是否你调整过配置的服务部署地址呢？ 重启server后可以执行`ps aux | grep analysis.gunicorn.conf.py`看看对应的进程启动时间是否为刚操作的时间

查到原因了，是我这边有多个config文件，start_service里指定的config文件指向了未被调整的文件，导致DEBUG参数被覆盖了。
Sorry
