### ISSUE TITLE
文档勘误：`How to get start`  链接到了原始 MD 文件

### ISSUE THREAD

**Issue by G3G4X5X6** [Tencent/CodeAnalysis#250]
## 访问点
![image](https://user-images.githubusercontent.com/87740076/164179299-fe99ac20-24d8-45e6-b1af-8fada185b803.png)

## 访问返回
![image](https://user-images.githubusercontent.com/87740076/164179654-c93869a7-6bc9-49e5-8512-4f7b1cea90d2.png)

**Comment by Lingghh** [comment]
请问访问点的url是什么呢？

我在``https://github.com/Tencent/CodeAnalysis``页面访问显示是正常的

**Comment by nickcdon** [comment]
@G3G4X5X6 感谢提醒，GitHub构建Page可能未能将含有中文的md文件转成html，目前已将该文档文件命名进行调整，现在应该可以了。
