### ISSUE TITLE
:sparkles: Support SonarQube

### ISSUE THREAD

**Issue by GabrielLegend** [Tencent/CodeAnalysis#268]
Hi,

TCA is a great project, awesome.
And because our company often used SonarQube before, here I wrote a [TCA plug-in](https://github.com/GabrielLegend/tca_plugin_sonarqube) to integrate SonarQube and share it with you. :satisfied:

**Comment by GabrielLegend** [comment]
#269

**Comment by Lingghh** [comment]
Thank you for acknowledging our project and sharing your Plugin.
We review the code first and reply as soon as possible.

**Comment by GabrielLegend** [comment]
Thanks:smiley:
