### ISSUE TITLE
CodeAnalysis could not find log4j-shell? it is only check the jar?

### ISSUE THREAD

**Issue by wcc526** [Tencent/CodeAnalysis#28]
why not check the pom.xml? get mvn dependices?

regex = (log4j-core-1\\..*\\.jar)|(log4j-core-2\\.1[0-6]\\..*\\.jar)

https://github.com/Tencent/CodeAnalysis/blob/main/server/projects/main/apps/scan_conf/management/commands/open_source/regexfilescan.json#L24

**Comment by owlmk** [comment]
we have two ways to find log4j:
