### ISSUE TITLE
执行CPD任务时，报找不到目录的报错

### ISSUE THREAD

**Issue by jinghaifeng1** [Tencent/CodeAnalysis#281]
![image](https://user-images.githubusercontent.com/20569882/165488764-47fe6f03-aff2-46dc-b8da-47ae441aebc8.png)
![image](https://user-images.githubusercontent.com/20569882/165488773-202480f6-e68f-467e-a3da-b7f67f2d9151.png)

执行CPD任务的时候，报错说找不到某个目录，我看了下，本地确实没有这个目录，但是他为啥要去找这个目录呢

**Comment by cyw3** [comment]
这里在执行任务的同时 代码仓库是不是也在执行编译或者进行其他进程呢？

**Comment by cyw3** [comment]
对于.NETFramework,Version=v4.0.AssemblyAttributes.cs此类Visual Studio自动生成的文件，建议可以在分析方案中配置过滤掉，这样可以缩减分析耗时，也方便开发只用关注自己编写的代码文件问题。
