### ISSUE TITLE
在线分析速度比本地分析慢很多

### ISSUE THREAD

**Issue by Akitata** [Tencent/CodeAnalysis#289]
Java项目，默认Java规则，不编译，都使用checkstyle/codecount/cpd/lizard/pmd 这5个工具扫描(工具已经都下载到了本地)

本地扫描仅需40秒完成，在线扫描需要5分钟 

请问各位开发者该如何解决?

**Comment by Akitata** [comment]
@zhang9w0v5 

我只有一个节点 且已经配了UseLocalTool=True 应该不是去拉工具的代码

如何判断是否每次都有拉项目代码? 我看cllient/data/sourcedirs目录下是有我的项目的，而且client/data/cache.json里也有项目配置

**Comment by Lingghh** [comment]
可以看看在线扫描时每个任务的执行步骤哈，确认是在哪个环节执行比较耗时

**Comment by zhang9w0v5** [comment]
理论上，程序是同一套，执行效率在同样设备，同样操作系统，同样规模的代码量是不会有太大差异的。
如lingghh所说，akitata看看各个环节上报的时间，看看慢在哪里。

**Comment by Akitata** [comment]
已解决，是有在重复更新工具
