### ISSUE TITLE
报错：Dockerfile-common 文件执行 apt-get install -y --no-install-recommends $EXTRA_TOOLS 依赖报错

### ISSUE THREAD

**Issue by IsME420** [Tencent/CodeAnalysis#30]
![微信截图_20220107001458](https://user-images.githubusercontent.com/21011169/148414242-d3e2b730-e27d-4d8e-a60d-a39627ddfc60.png)

用的relase分支。
用默认源网络报错，改成了网易的apt-get源。执行依赖会报图中的错误。

**Comment by Lingghh** [comment]
麻烦发一下对Docker-common做了哪些调整哈，我们分析看看

**Comment by IsME420** [comment]
首先遇到的问题是用默认源的化在apt-get update会卡住  可能是网络问题，
![截图](https://user-images.githubusercontent.com/21011169/148489409-67f1ca3d-399e-4de8-9e2f-3624c088f8fd.png)

然后我就改成了163的源，修改如下：
`FROM python:3.7.12-slim


RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak
RUN echo 'deb http://mirrors.163.com/debian/ stretch main non-free contrib' > /etc/apt/sources.list
RUN echo 'deb http://mirrors.163.com/debian/ stretch-updates main non-free contrib' >> /etc/apt/sources.list
RUN echo 'deb http://mirrors.163.com/debian-security/ stretch/updates main non-free contrib' >> /etc/apt/sources.list


ARG EXTRA_TOOLS="gnupg curl wget jq vim-tiny net-tools procps python3-dev default-libmysqlclient-dev locales inotify-tools gcc subversion git telnet iputils-ping vim openssh-client"

RUN set -ex && cd / \
    && apt-get update \
    && apt-get install -y --no-install-recommends $EXTRA_TOOLS \
    && apt-get update \
    && apt-get install -y mariadb-client \
    && apt-get clean \
    && echo "LC_ALL=zh_CN.UTF-8" >> /etc/environment \
    && echo "zh_CN.UTF-8 UTF-8" > /etc/locale.gen \
    && echo "LANG=zh_CN.UTF-8" > /etc/locale.conf \
    && locale-gen \
    && ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime \
    && rm -rf /var/cache/apt/* /root/.cache

WORKDIR /var/www/django/codedog

COPY . .

RUN mkdir -p log/ && \
    pip install -U setuptools pip && \
    pip install -r requirements.txt
    
`

再执行，apt-get update 这步没问题了
但是到apt-get install -y --no-install-recommends $EXTRA_TOOLS 这步会报依赖错误：
![image](https://user-images.githubusercontent.com/21011169/148489596-5573309c-5247-4d56-b0c5-ebbc3acf22d7.png)
试了网上的一些依赖的解决方案，也不行

**Comment by Lingghh** [comment]
因为``python:3.7.12-slim``是基于``debian bullseye``(debian 11)版本构建的，对应的源需要选择 ``bullseye``版本的源
可以将你的修改替换为以下内容：
```
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
    echo 'deb http://mirrors.163.com/debian/ bullseye main non-free contrib' > /etc/apt/sources.list && \
    echo 'deb http://mirrors.163.com/debian/ bullseye-updates main non-free contrib' >> /etc/apt/sources.list && \
    echo 'deb http://mirrors.163.com/debian-security bullseye-security main non-free contrib' >> /etc/apt/sources.list
```

**Comment by IsME420** [comment]
找到原因了，找了一天，我服务器本地时间不对，导致的apt-get update错误，和apt-get的源无关。
