### ISSUE TITLE
前端：`更新密码` 没有使用 `密码类型` 输入框遮掩输入密码

### ISSUE THREAD

**Issue by G3G4X5X6** [Tencent/CodeAnalysis#300]
## 希望可以遮掩输入密码
![image](https://user-images.githubusercontent.com/87740076/167588793-b8bb69c1-829c-46e5-b9be-42670b808aaa.png)

**Comment by nickcdon** [comment]
这里我们调整支持下

**Comment by nickcdon** [comment]
已发布新版支持
