### ISSUE TITLE
执行结果：任务参数错误 TaskError: Error[205]: 数据库读取失败可能为选错了语言

### ISSUE THREAD

**Issue by liweihui1** [Tencent/CodeAnalysis#306]
-2022-05-11 10:27:51,661-INFO-util.logutil: start to run task: Hades_Beta_PHP, execute_processes: ['compile', 'analyze', 'datahandle']
-2022-05-11 10:27:53,274-INFO-util.logutil: 加载公共编译工具的环境变量...
-2022-05-11 10:27:53,354-INFO-util.logutil: Initing 1 tools, please wait a minute ...

[Tools init]:   0%|                                                           | 0/1 [00:00<?, ?it/s]
[Tools init]: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.58s/it]
[Tools init]: 100%|███████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.58s/it]
-2022-05-11 10:27:54,939-INFO-util.logutil: Initialize tools done.(use time: 1.58s)
-2022-05-11 10:27:54,946-INFO-task.taskmgr: task start : <class 'task.model.compile.CompileTask'>
-2022-05-11 10:27:54,946-INFO-task.sourcemgr: pre_compile start.
-2022-05-11 10:27:54,946-INFO-task.sourcemgr: start __checkout_source_dir.
-2022-05-11 10:27:54,947-INFO-task.sourcemgr: 常规项目，直接拉取或复用本地缓存资源.
-2022-05-11 10:27:56,783-INFO-task.sourcemgr: load_source_dir done. source_dir insert env. sourcedir: /home/iotmp/CodeAnalysis-main/client/data/sourcedirs/git_n10b5zkx
-2022-05-11 10:27:56,786-INFO-task.sourcemgr: pre_compile done.
-2022-05-11 10:27:56,787-INFO-util.logutil: PATH =
****************************************************************************************************
/home/iotmp/CodeAnalysis-main/client/../tools/Hades_Beta
/home/iotmp/CodeAnalysis-main/client/../tools/Zeus_Beta
/sbin
/bin
/usr/sbin
/usr/bin
****************************************************************************************************
-2022-05-11 10:27:56,787-INFO-util.logutil: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
-2022-05-11 10:27:56,787-INFO-util.logutil: Codelint only cans main code.
-2022-05-11 10:27:56,823-INFO-util.codecount.repoter: 已经上报过代码行数,本次分析无需上报.
-2022-05-11 10:27:56,841-INFO-util.logutil: 开始编译项目 /home/iotmp/CodeAnalysis-main/client/data/sourcedirs/git_n10b5zkx
-2022-05-11 10:27:56,842-INFO-util.logutil: 是否为增量编译: False
-2022-05-11 10:27:56,842-INFO-util.logutil: ['./Zeus', 'compile', '-p', '1_a5e507bd12ebe98baddba3d5aeee2dce0008d25e_php', '-db', '/home/iotmp/CodeAnalysis-main/client/data/taskdirs/task_93/workdir/db', '-l', 'php', '-s', '/home/iotmp/CodeAnalysis-main/client/data/sourcedirs/git_n10b5zkx']
-2022-05-11 10:27:56,852-INFO-task.basic.common: dlopen(): error loading libfuse.so.2
-2022-05-11 10:27:56,853-INFO-task.basic.common: 
-2022-05-11 10:27:56,853-INFO-task.basic.common: AppImages require FUSE to run. 
-2022-05-11 10:27:56,853-INFO-task.basic.common: You might still be able to extract the contents of this AppImage 
-2022-05-11 10:27:56,853-INFO-task.basic.common: if you run it with the --appimage-extract option. 
-2022-05-11 10:27:56,854-INFO-task.basic.common: See https://github.com/AppImage/AppImageKit/wiki/FUSE 
-2022-05-11 10:27:56,854-INFO-task.basic.common: for more information
-2022-05-11 10:27:56,943-INFO-util.logutil: 1
-2022-05-11 10:27:56,943-INFO-util.logutil: 准备上传到云端存储数据库
-2022-05-11 10:27:56,943-INFO-util.logutil: 开始上传
-2022-05-11 10:27:56,944-ERROR-util.wrapper: method(upload_file) call fails on error: [Errno 2] 没有那个文件或目录: '/home/iotmp/CodeAnalysis-main/client/data/taskdirs/task_93/workdir/db/1_a5e507bd12ebe98baddba3d5aeee2dce0008d25e_php.db'
-2022-05-11 10:27:56,944-INFO-util.wrapper: retrying method(upload_file) after 5 seconds
-2022-05-11 10:28:01,949-ERROR-util.wrapper: method(upload_file) call fails on error: [Errno 2] 没有那个文件或目录: '/home/iotmp/CodeAnalysis-main/client/data/taskdirs/task_93/workdir/db/1_a5e507bd12ebe98baddba3d5aeee2dce0008d25e_php.db'
-2022-05-11 10:28:01,950-INFO-util.wrapper: retrying method(upload_file) after 5 seconds
-2022-05-11 10:28:06,955-ERROR-util.wrapper: method(upload_file) call fails on error: [Errno 2] 没有那个文件或目录: '/home/iotmp/CodeAnalysis-main/client/data/taskdirs/task_93/workdir/db/1_a5e507bd12ebe98baddba3d5aeee2dce0008d25e_php.db'
-2022-05-11 10:28:06,955-WARNING-util.wrapper: method(upload_file) call still fails after 2 retries
-2022-05-11 10:28:06,956-WARNING-util.logutil: 上传失败
-2022-05-11 10:28:06,956-INFO-task.sourcemgr: done_compile start.
-2022-05-11 10:28:06,957-INFO-task.taskmgr: task done : <class 'task.model.compile.CompileTask'>
-2022-05-11 10:28:06,957-INFO-task.taskmgr: task start : <class 'task.model.analyze.AnalyzeTask'>
-2022-05-11 10:28:06,957-INFO-task.sourcemgr: pre_analyze start.
-2022-05-11 10:28:06,957-INFO-task.sourcemgr: pre_analyze done.
-2022-05-11 10:28:07,015-INFO-util.logutil: 本地未找到数据库文件/home/iotmp/CodeAnalysis-main/client/data/taskdirs/task_93/workdir/db/1_a5e507bd12ebe98baddba3d5aeee2dce0008d25e_php.db，从文件服务器下载
-2022-05-11 10:28:07,015-INFO-util.logutil: 开始下载文件tcaql/repos/1/1_a5e507bd12ebe98baddba3d5aeee2dce0008d25e_php.db
-2022-05-11 10:28:07,054-ERROR-util.api.httpclient: api request error: {"Err-type":"file_not_exist","Err-msg":"5b2T5YmN5paH5Lu25LiN5a2Y5Zyo"}
url: http://192.168.9.30/server/files/tcaql/repos/1/1_a5e507bd12ebe98baddba3d5aeee2dce0008d25e_php.db
-2022-05-11 10:28:07,054-ERROR-util.wrapper: method(download_file) call fails on error: HTTP Error 404: Not Found
-2022-05-11 10:28:07,054-INFO-util.wrapper: retrying method(download_file) after 5 seconds
-2022-05-11 10:28:12,100-ERROR-util.api.httpclient: api request error: {"Err-type":"file_not_exist","Err-msg":"5b2T5YmN5paH5Lu25LiN5a2Y5Zyo"}
url: http://192.168.9.30/server/files/tcaql/repos/1/1_a5e507bd12ebe98baddba3d5aeee2dce0008d25e_php.db
-2022-05-11 10:28:12,100-ERROR-util.wrapper: method(download_file) call fails on error: HTTP Error 404: Not Found
-2022-05-11 10:28:12,100-INFO-util.wrapper: retrying method(download_file) after 5 seconds
-2022-05-11 10:28:17,147-ERROR-util.api.httpclient: api request error: {"Err-type":"file_not_exist","Err-msg":"5b2T5YmN5paH5Lu25LiN5a2Y5Zyo"}
url: http://192.168.9.30/server/files/tcaql/repos/1/1_a5e507bd12ebe98baddba3d5aeee2dce0008d25e_php.db
-2022-05-11 10:28:17,148-ERROR-util.wrapper: method(download_file) call fails on error: HTTP Error 404: Not Found
-2022-05-11 10:28:17,148-WARNING-util.wrapper: method(download_file) call still fails after 2 retries
-2022-05-11 10:28:17,148-WARNING-util.logutil: 下载失败
-2022-05-11 10:28:17,150-WARNING-task.puppytask: task status code is 205
-2022-05-11 10:28:17,150-WARNING-task.puppytask: task messsage: TaskError: Error[205]: 数据库读取失败可能为选错了语言
-2022-05-11 10:28:17,151-INFO-task.puppytask: task result: /home/iotmp/CodeAnalysis-main/client/data/taskdirs/task_93/task_response.json

**Comment by liweihui1** [comment]
![image](https://user-images.githubusercontent.com/67351176/167756999-e869682e-705f-4c53-817f-5ade052ce3b9.png)

**Comment by owlmk** [comment]
https://github.com/AppImage/AppImageKit/wiki/FUSE 参考这里安装下

**Comment by liweihui1** [comment]
有其他解决方法吗，环境好像不能安装这个

**Comment by owlmk** [comment]
这里系统环境是？ 在tools/Zeus_Beta目录下 执行./Zeus -v 看下是否能正常执行

**Comment by liweihui1** [comment]
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
没有成功

**Comment by liweihui1** [comment]
centos

**Comment by liweihui1** [comment]
不行啊，失败了

**Comment by jkl1994** [comment]
碰到同样的问题，请问解决了吗

**Comment by cyw3** [comment]
这里 Hades_Beta_PHP 如果执行异常的话，建议先申请License，使用 TCA_QL_PHP 工具来替代， TCA_QL_PHP 是完整版工具。
