### ISSUE TITLE
功能增强：启动分析->客户端分析，希望可以增加一个复制配置文件内容的功能

### ISSUE THREAD

**Issue by G3G4X5X6** [Tencent/CodeAnalysis#308]
## 现状
首先需要下载配置文件，然后上传覆盖配置文件

## 需求
可以直接复制配置文件内容，如此就可以直接vim覆盖配置文件，方便快速
![image](https://user-images.githubusercontent.com/87740076/167760639-f57f109d-f07e-4922-b670-fcf80510e433.png)

**Comment by nickcdon** [comment]
好主意，我们这边跟进调整下

**Comment by nickcdon** [comment]
已发布新版，已支持复制配置文件
