### ISSUE TITLE
[feature request] Kotlin support

### ISSUE THREAD

**Issue by LifeIsStrange** [Tencent/CodeAnalysis#31]
Maybe you could share some analysises with Java

**Comment by cyw3** [comment]
TCA support kotlin:
https://github.com/Tencent/CodeAnalysis/blob/main/server/projects/main/apps/scan_conf/management/commands/open_source/ktlint.json
https://github.com/Tencent/CodeAnalysis/blob/main/server/projects/main/apps/scan_conf/management/commands/open_source/detekt.json

**Comment by LifeIsStrange** [comment]
thanks
