### ISSUE TITLE
`启动分析 ` -> `客户端分析` -> `全量分析`，生成配置文件参数`total_scan`不正确

### ISSUE THREAD

**Issue by G3G4X5X6** [Tencent/CodeAnalysis#312]
<img width="1280" alt="企业微信截图_16522604111411" src="https://user-images.githubusercontent.com/87740076/167815595-890b853c-5b59-43ea-b773-72a7c85dec29.png">

**Comment by nickcdon** [comment]
感谢反馈，已修复，可以拉取最新代码，更新前端服务即可
