### ISSUE TITLE
【项目优化】支持下载代码超时时间可配置

### ISSUE THREAD

**Issue by lincoohe** [Tencent/CodeAnalysis#335]
每一公司环境的网络环境和代码仓大小是不一样，今天测试拉取超过4mins时，会直接报错无法执行任务。

**Comment by lincoohe** [comment]
![44fb0afb44a5f50ec89d5776440b6f0](https://user-images.githubusercontent.com/32337791/168774469-e521c6fb-a6cb-4a56-9928-d54ac9401c5d.png)

**Comment by Lingghh** [comment]
这一块功能已支持，可以拉取最新代码进行配置哈
本地部署配置位置：[代码位置](https://github.com/Tencent/CodeAnalysis/blob/main/server/configs/django/local_main.py#L94)
