### ISSUE TITLE
【项目优化】TCA web页面的项目可以删除（可以假删除，或者按权限分配操作，或者丢到垃圾箱保存一段时间）

### ISSUE THREAD

**Issue by lincoohe** [Tencent/CodeAnalysis#336]
![20b96e7248720265cfdd2c74d8d4170](https://user-images.githubusercontent.com/32337791/168785549-fa0bc213-8225-4c1d-92e8-dcfad2f2aad1.png)

**Comment by Lingghh** [comment]
这里已记单哈，正在排期实现~

**Comment by Lingghh** [comment]
功能已支持，请拉取最新代码体验~
