### ISSUE TITLE
【项目建议】客户端配置的建议

### ISSUE THREAD

**Issue by fuce1314** [Tencent/CodeAnalysis#346]
下图为配置项
![image](https://user-images.githubusercontent.com/3125727/170064265-e0a3ae23-84b4-41b5-9a4b-43d0868c4d5e.png)

下图为建议图
![image](https://user-images.githubusercontent.com/3125727/170066318-0809da99-7d2c-4746-919d-0e4ddc1f534b.png)

建议说明：
个人建议可以在服务端页面新建一个菜单栏，叫【配置管理】，其他配置我没画出来，可以找个页面该下拉列表的就是下拉列表，该固定值得就是固定值，如果在有一个下载该配置，就完美了。

**Comment by Lingghh** [comment]
感谢建议，我们优化一下这个配置操作哈

**Comment by nickcdon** [comment]
@fuce1314 个人中心页面无法捕获到团队和项目。其实在分支项目页面启动客户端分析时，可以直接下载拿到codedog.ini配置文件的

**Comment by nickcdon** [comment]
@fuce1314 不过确实可以在项目页面加上此处配置说明
