### ISSUE TITLE
二进制文件依赖分析需求

### ISSUE THREAD

**Issue by Lingghh** [Tencent/CodeAnalysis#362]
1. 计算指定模块包或二进制文件的md5值或hash值；
2. 检测目标工程中是否包含该模块包

**Comment by fuce1314** [comment]
[代码检测.zip](https://github.com/Tencent/CodeAnalysis/files/8799381/default.zip)

java版本检测示例方法，可以检测jar包或者war包是否包含log4j模块，可以计算出文件得md5值。

思路1：

**Comment by auula** [comment]
i take the task！

**Comment by cyw3** [comment]
@fuce1314 @auula 

欢迎往[这里](https://github.com/Tencent/CodeAnalysis/tree/main/tools/feature_check)提交工具PR哈，感谢

**Comment by auula** [comment]
> @fuce1314 @auula
> 
> 欢迎往[这里](https://github.com/Tencent/CodeAnalysis/tree/main/tools/feature_check)提交工具公关哈，谢谢

我先在我自己仓库测试一下哈，[https://github.com/auula/onion](https://github.com/auula/onion)

**Comment by cyw3** [comment]
> > @fuce1314 @auula
> > 欢迎往[这里](https://github.com/Tencent/CodeAnalysis/tree/main/tools/feature_check)提交工具公关哈，谢谢
> 
> 我先在我自己仓库测试一下哈，https://github.com/auula/onion

👍

**Comment by auula** [comment]
仓库地址跟新了，后面我开发好了，我会fork你们仓库然后整理到你们这个目录中，并且我会写一份使用文档，名称我也改了叫`tca-scan`。

**Comment by auula** [comment]
Please review this Pull Request: [https://github.com/Tencent/CodeAnalysis/pull/394](https://github.com/Tencent/CodeAnalysis/pull/394)
