### ISSUE TITLE
扫描卡住不动

### ISSUE THREAD

**Issue by color-way** [Tencent/CodeAnalysis#38]
![image](https://user-images.githubusercontent.com/22786207/148513806-4fd9e63b-f5d5-48ef-8961-68f392aa0070.png)

**Comment by bensonhome** [comment]
@color-way 看看client/data/tools下是否拉取到工具目录呢

**Comment by color-way** [comment]
> @color-way 看看client/data/tools下是否拉取到工具目录呢
这三个文件夹
cloc  common-lizard-1.17.5  linux-Python-v3.7.2

**Comment by bensonhome** [comment]
@color-way 没有puppy-tools-config目录，可能是git拉取失败了，退出，重跑一下试试

**Comment by color-way** [comment]
> @color-way 没有puppy-tools-config目录，可能是git拉取失败了，退出，重跑一下试试

直接把https://github.com/TCATools/puppy-tools-config 这个放到这个目录下可以吗，拉取网速有点慢

**Comment by Zishuhooo** [comment]
![image](https://user-images.githubusercontent.com/32224062/148518594-91ed0eb7-d883-45ee-9780-83a0c4a955ff.png)
这个本地路径是填什么呢，，我也试了.git 会提示输入异常

**Comment by bensonhome** [comment]
@color-way 可以的，这里会拉取一系列的工具（url地址在puppy-tools-config这个库里对应的ini文件中）。
你可以手动把这些工具都拉下来，存放到client/data/tools目录下。
另外在client/config.ini的[common]中设置一个参数：
USE_LOCAL_TOOL=True
就可以不自动拉取工具，直接使用本地拉好的工具。

**Comment by jkl1994** [comment]
> @color-way 可以的，这里会拉取一系列的工具（url地址在puppy-tools-config这个库里对应的ini文件中）。 你可以手动把这些工具都拉下来，存放到client/data/tools目录下。 另外在client/config.ini的[common]中设置一个参数： USE_LOCAL_TOOL=True 就可以不自动拉取工具，直接使用本地拉好的工具。

在client/config.ini的[common]中设置一个参数USE_LOCAL_TOOL=True；执行扫描的时候，还是会去安装工具，卡住不动。。。
![image](https://user-images.githubusercontent.com/34265722/148535516-981caa5d-b378-4612-91bd-f7b298425508.png)
工具以及单独都拉下来了，
![image](https://user-images.githubusercontent.com/34265722/148535574-6a0fc47e-03a4-4bc5-a896-2d66db9fd972.png)

**Comment by bensonhome** [comment]
@jkl1994 @color-way 
使用本地工具可以参考这里的文档：https://github.com/Tencent/CodeAnalysis/blob/main/client/README.md
二、其他配置与用法
1. 配置使用本地工

另外麻烦更新下最新代码，最新的client代码增加了对应的提示信息，上面仍从git拉工具，可能是本地没有拉取完整工具，可以从最新版本的代码日志中看出是哪个工具。
