### ISSUE TITLE
配置用户凭证拉取github代码老报用户名密码错误

### ISSUE THREAD

**Issue by liukaips** [Tencent/CodeAnalysis#39]
![image](https://user-images.githubusercontent.com/24819958/148529270-2e963241-9438-47fd-80d8-4251b6c7a591.png)

**Comment by Lingghh** [comment]
github拉取代码需要用personal access token

**Comment by LoveCppp** [comment]
容器部署的化可以进入codeanalysis_scmproxy，查看日志 cat logs/scmproxy.log 大概率是github超时了

**Comment by liukaips** [comment]
> github拉取代码需要用personal access token
多谢大佬，配置了token是可以成功的， 页面上好像没有触发启动分析的按钮，所有的分析需要通过client进行命令触发吗？

**Comment by liukaips** [comment]
> > github拉取代码需要用personal access token
> > 多谢大佬，配置了token是可以成功的， 页面上好像没有触发启动分析的按钮，所有的分析需要通过client进行命令触发吗？

![image](https://user-images.githubusercontent.com/24819958/148727721-0caa89ac-d354-46bd-a08d-7a952eaa628d.png)
只有下载配置按钮，没有启动分析的按钮

**Comment by Lingghh** [comment]
是的，需要通过client触发哈
