### ISSUE TITLE
部分功能闭源？未来有开源计划吗？

### ISSUE THREAD

**Issue by yuanfeng0905** [Tencent/CodeAnalysis#4]
* https://github.com/Tencent/CodeAnalysis/blob/main/client/task/runtask.cpython-37m-x86_64-linux-gnu.so
* https://github.com/Tencent/CodeAnalysis/blob/main/client/node/taskrunner.cpython-37m-x86_64-linux-gnu.so
* https://github.com/Tencent/CodeAnalysis/blob/main/client/task/initparams.cpython-37m-x86_64-linux-gnu.so
* ...

**Comment by zhang9w0v5** [comment]
这块涉及商业版，是从商业版迁移而来，暂时没有开源。

**Comment by cocorunning** [comment]
暂时没有开源。
