### ISSUE TITLE
客户端扫描 400 异常

### ISSUE THREAD

**Issue by agentchang** [Tencent/CodeAnalysis#40]
![image](https://user-images.githubusercontent.com/97286623/148531613-eae338f5-2937-421a-95c0-32033992ce00.png)
config.ini 的文件服务器 token 和 codedog.ini 的个人 token 是否为同一个？

**Comment by Lingghh** [comment]
麻烦发一下main-server的 log/codedog.log，我们分析看看

**Comment by agentchang** [comment]
![image](https://user-images.githubusercontent.com/97286623/148534170-5ffac48b-0538-4d19-afb4-08acbb0a4740.png)
config.ini 和 codedog.ini 用的是同一个 token

**Comment by Lingghh** [comment]
这里可以更新一下代码再试试

**Comment by tengzhexiao** [comment]
我也遇到了同样的问题，更新最新代码一样

**Comment by jirufeng** [comment]
遇到了同样的问题

**Comment by Lingghh** [comment]
这里是否更新过默认的token呢？@tengzhexiao 

如果更新过，需要调整一下``server/dockerconfs/.env.local``或``server/scripts/config.sh``文件中的``FILE_SERVER_TOKEN``的值，然后重启一下服务（如果是Docker-Compose启动，则使用``docker-compose up -d``重启，如果是裸机部署，则进入``server``目录执行``scripts/deploy.sh start``进行重启
