### ISSUE TITLE
在线分析耗时一小时入库失败

### ISSUE THREAD

**Issue by AzuoHealer** [Tencent/CodeAnalysis#401]
![image](https://user-images.githubusercontent.com/39117380/173539873-93c9c971-c75e-41c3-9cf8-51173c2e8be3.png)

**Comment by AzuoHealer** [comment]
部署方式是docker一件部署的

**Comment by Lingghh** [comment]
这里有刷新过CodeDog用户的token么？

**Comment by AzuoHealer** [comment]
之前刷新过，那两个文件的token我都更换过了

**Comment by Lingghh** [comment]
> 之前刷新过，那两个文件的token我都更换过了

这里有调整 ``server/dockerconfs/.env.local``的``FILE_SERVER_TOKEN ``么？
调整该文件后还需要执行``docker-compose up -d``

**Comment by AzuoHealer** [comment]
都操作过了
