### ISSUE TITLE
[Bug] [度量结果 -> 代码统计] 选中的文件展开超出侧栏宽度时，文件名会被截断

### ISSUE THREAD

**Issue by G3G4X5X6** [Tencent/CodeAnalysis#403]
### 状态1
![image](https://user-images.githubusercontent.com/87740076/173724698-5c867cdd-bee0-4087-9399-3918bd07725c.png)

### 状态2
![image](https://user-images.githubusercontent.com/87740076/173724873-3ca216b9-1c13-479b-8ebf-9b68c2219a99.png)

### 状态3
![image](https://user-images.githubusercontent.com/87740076/173724952-052fc8c6-9ac0-404d-a239-6aeec6c5c043.png)

**Comment by Lingghh** [comment]
感谢反馈，我们处理一下
