### ISSUE TITLE
扫描完报错

### ISSUE THREAD

**Issue by color-way** [Tencent/CodeAnalysis#41]
![image](https://user-images.githubusercontent.com/22786207/148531863-214cde0d-4b0a-4de8-bfe6-72e07b7b8399.png)

**Comment by Lingghh** [comment]
麻烦发一下客户端输出的完整日志，我们分析一下哈

**Comment by color-way** [comment]
> 麻烦发一下客户端输出的完整日志，我们分析一下哈

在哪里呀

**Comment by Lingghh** [comment]
可以把最后一行正常日志以及完整的异常堆栈都截一下图

**Comment by Lingghh** [comment]
config.ini文件中配置的文件服务器url与server url的域名是否一致呢？

**Comment by color-way** [comment]
> config.ini文件中配置的文件服务器url与server url的域名是否一致呢？

是一样的URL=http://192.168.7.244:88/server/files/

**Comment by color-way** [comment]
这次好像成功了，但是卡在这了
![image](https://user-images.githubusercontent.com/22786207/148713810-5108e33a-796f-4064-937a-b9831a9a84ba.png)

**Comment by Lingghh** [comment]
目前能正常运行了么？
如果报错了，可以看一下analysis-worker是否正常运行

**Comment by color-way** [comment]
> 目前能正常运行了么？ 如果报错了，可以看一下analysis-worker是否正常运行

最后会报错第三方依赖文件服务器异常，入库失败。请问我这个config.ini中的地址是否填写正确：
[SERVER_URL]
; [必填]请将<Server IP地址>替换为实际的tca server地址
URL=http://192.168.7.244:88/server/main/

[FILE_SERVER]
; [必填]文件服务器地址，请将<Server IP地址>替换为实际的tca server地址
URL=http://192.168.7.244:8888/server/files/

web平台访问的地址是http://192.168.7.244:88/

**Comment by Lingghh** [comment]
文件服务器FILE_SERVER的链接可以调整为 ``URL=http://192.168.7.244:88/server/files/``

**Comment by color-way** [comment]
> 文件服务器FILE_SERVER的链接可以调整为 `URL=http://192.168.7.244:88/server/files/`

这两个端口是需要对外开放吗？还是一直卡在query result from server不动

**Comment by jirufeng** [comment]
同样卡在这里

**Comment by Lingghh** [comment]
不需要对外，这里可以检查一下``analysis-worker``的日志，看看是什么问题
```bash
docker-compose exec analysis-worker /bin/bash
tail -F -n 1000 log/codedog.log
```

**Comment by color-way** [comment]
> 

-2022-01-12 10:19:18,813-INFO-util.fileserver: Downloading file from http://192.168.7.244:88/server/files/taskdata/projects/1/task_180/ee26bccc734b11ecb0a5002277c9372e/tmp_dir.zip to /var/www/django/codedog/tempdata/a523b62ae4126341c7d8946d7301636cb74f21c6/tmp_dir.zip
-2022-01-12 10:19:19,818-WARNING-urllib3.connectionpool: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb32d48810>: Failed to establish a new connection: [Errno 113] No route to host')': /server/files/taskdata/projects/1/task_180/ee26bccc734b11ecb0a5002277c9372e/tmp_dir.zip

是不是因为是内网的docker部署的，没有ip地址所以报错？docker访问内网192.168.7.244是不通的

**Comment by color-way** [comment]
@Lingghh 有空帮忙确认一下呀

**Comment by Lingghh** [comment]
> > 
> 
> -2022-01-12 10:19:18,813-INFO-util.fileserver: Downloading file from http://192.168.7.244:88/server/files/taskdata/projects/1/task_180/ee26bccc734b11ecb0a5002277c9372e/tmp_dir.zip to /var/www/django/codedog/tempdata/a523b62ae4126341c7d8946d7301636cb74f21c6/tmp_dir.zip -2022-01-12 10:19:19,818-WARNING-urllib3.connectionpool: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb32d48810>: Failed to establish a new connection: [Errno 113] No route to host')': /server/files/taskdata/projects/1/task_180/ee26bccc734b11ecb0a5002277c9372e/tmp_dir.zip
> 
> 是不是因为是内网的docker部署的，没有ip地址所以报错？docker访问内网192.168.7.244是不通的

是这个原因导致的，目前这里是有什么限制么？为什么docker访问内网192.168.7.244是不通的呢？

**Comment by Lingghh** [comment]
这里可以关闭宿主机的防火墙试试
