### ISSUE TITLE
入库失败，（第三方依赖文件服务器异常）

### ISSUE THREAD

**Issue by cloudusers** [Tencent/CodeAnalysis#417]
按问题列表提示查看，并非防火墙与route相关，看worker的celery.log日志如下（本地环境是macos + docker部署）：

....
-2022-06-18 11:43:36,276-INFO-apps.codeproj.core.base: [Project: 1][Job: 7][Scan: 7][Type :2]Job result_code 成功，开始关闭更早的未入库的扫描（如有）...
-2022-06-18 11:43:36,282-INFO-apps.codeproj.core.base: [Project: 1][Job: 7][Scan: 7][Type :2]已关闭更早的未入库的扫描...
-2022-06-18 11:43:36,284-INFO-apps.codeproj.core.base: [Project: 1][Job: 7][Scan: 7][Type :2]准备task数据...
-2022-06-18 11:43:36,284-INFO-apps.codeproj.core.base: [Project: 1][Job: 7][Scan: 7][Type :2]调用各个模块job.on_job_end开始入库...
-2022-06-18 11:43:36,285-INFO-apps.codeproj.core.base: [Project: 1][Job: 7][Scan: 7][Type :2]模块[codelint]开始入库 ...
-2022-06-18 11:43:36,286-INFO-apps.codelint.job: [Project: 1][Scan: 7] 开始codelint入库...
-2022-06-18 11:43:36,287-INFO-apps.codelint.job: [Project: 1][Scan: 7] 共有2个工具的结果需要入库
-2022-06-18 11:43:36,293-INFO-apps.codelint.job.linthandler: [Project: 1][Scan: 7] 将0个工具已移除的问题置为关闭状态
-2022-06-18 11:43:36,296-INFO-apps.codelint.job.linthandler: [Project: 1][Scan: 7] 将0个未关闭的问题置为关闭状态
-2022-06-18 11:43:36,297-INFO-apps.codelint.job: [Project: 1][Scan: 7][1/2] 开始入库工具checkstyle的结果...
-2022-06-18 11:43:36,299-INFO-apps.codelint.job.linthandler: 1.1 解析参数，下载task_params: http://nginx:8000/files/public_server_temp/jobdata/projects/1/job7/bf761b96eeb811ecb2e00242ac14000a/task_params_32.json
-2022-06-18 11:43:36,391-INFO-apps.codelint.job.linthandler: 1.1 解析参数，下载result_data: http://localhost/server/files/taskdata/projects/1/task_32/c843d9f2eeb811ec9c58acde48001122/tmp_dir.zip
-2022-06-18 11:43:36,392-INFO-util.fileserver: Downloading file from http://localhost/server/files/taskdata/projects/1/task_32/c843d9f2eeb811ec9c58acde48001122/tmp_dir.zip to /var/www/django/codedog/tempdata/3135794b8627dda56770119649e39ad09a996f98_d5700aceeeb811ecb4540242ac140009/tmp_dir.zip
-2022-06-18 11:43:36,393-WARNING-urllib3.connectionpool: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f986bb2aad0>: Failed to establish a new connection: [Errno 111] Connection refused')': /server/files/taskdata/projects/1/task_32/c843d9f2eeb811ec9c58acde48001122/tmp_dir.zip

....

因为所有模块都在同一台机器上（容器方式部署），尝试连接失败

root@2058e897ba4d:/var/www/django/codedog# curl -v localhost:80
*   Trying 127.0.0.1:80...
* connect to 127.0.0.1 port 80 failed: Connection refused
*   Trying ::1:80...
* Immediate connect fail for ::1: Cannot assign requested address
* Failed to connect to localhost port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 80: Connection refused
root@2058e897ba4d:/var/www/django/codedog# 
root@2058e897ba4d:/var/www/django/codedog# 
root@2058e897ba4d:/var/www/django/codedog# curl -v localhost:8000
*   Trying 127.0.0.1:8000...
* connect to 127.0.0.1 port 8000 failed: Connection refused
*   Trying ::1:8000...
* Immediate connect fail for ::1: Cannot assign requested address
* Failed to connect to localhost port 8000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8000: Connection refused
root@2058e897ba4d:/var/www/django/codedog# 
root@2058e897ba4d:/var/www/django/codedog# 
root@2058e897ba4d:/var/www/django/codedog# netstat -a | grep 80
tcp        1      0 2058e897ba4d:43260      codeanalysis-nginx:8000 CLOSE_WAIT 
root@2058e897ba4d:/var/www/django/codedog# 
root@2058e897ba4d:/var/www/django/codedog#

**Comment by Lingghh** [comment]
这里需要改一下客户端的文件服务器上传地址，可以改为本机IP地址试试

**Comment by cloudusers** [comment]
你说的是改哪个配置？

我这里client 目录下的config.ini配置的是localhost
![image](https://user-images.githubusercontent.com/16657639/174444372-2478a25a-a87d-4a2f-af96-83e7be086d0e.png)

**Comment by cloudusers** [comment]
analysis-worker里的celery日志
![image](https://user-images.githubusercontent.com/16657639/174445345-39c0613e-5f01-48bb-b339-09018234e7ee.png)

**Comment by Lingghh** [comment]
> 我这里client 目录下的config.ini配置的是localhost

就这个文件哈，可以将[FILE_SERVER]URL中的localhost替换为机器的IP地址
