### ISSUE TITLE
当前环境不支持cobra工具步骤:['analyze']

### ISSUE THREAD

**Issue by agentch** [Tencent/CodeAnalysis#42]
![image](https://user-images.githubusercontent.com/20178425/148572575-94e9f7b2-9b2d-444d-86b0-20ddeaea5be3.png)
客户端安装了 cobra, python3-cobra，也执行了 common-cobra-v2.0.0-alpha.5/install.sh

**Comment by cyw3** [comment]
麻烦执行下以下命令看看log：
```
python --version
python <TCA Client位置>/data/tools/common-cobra-v2.0.0-alpha.5/cobra.py --help
<TCA Client位置>/data/tools/linux-Python-v3.7.2/bin/python --version
<TCA Client位置>/data/tools/linux-Python-v3.7.2/bin/python <TCA Client位置>/data/tools/common-cobra-v2.0.0-alpha.5/cobra.py --help
```

**Comment by agentch** [comment]
> 麻烦执行下以下命令看看log：
> 
> ```
> python --version
> python <TCA Client位置>/data/tools/common-cobra-v2.0.0-alpha.5/cobra.py --help
> <TCA Client位置>/data/tools/linux-Python-v3.7.2/bin/python --version
> <TCA Client位置>/data/tools/linux-Python-v3.7.2/bin/python <TCA Client位置>/data/tools/common-cobra-v2.0.0-alpha.5/cobra.py --help
> ```

![image](https://user-images.githubusercontent.com/20178425/148666266-de9186bf-846d-4e4f-9a7e-33d291f2eeb7.png)

![image](https://user-images.githubusercontent.com/20178425/148666316-6b44c41c-8e07-4f54-8ba6-f89e6d41df66.png)

**Comment by agentch** [comment]
![image](https://user-images.githubusercontent.com/20178425/148666348-e241a291-bd79-4934-b4a5-2656ae781848.png)

**Comment by agentch** [comment]
我暂时添加了一个 libffi.so.5 的软链接来解决

**Comment by cyw3** [comment]
👍
