### ISSUE TITLE
使用工具失败，需要输入编译命令，这个在哪里配置？

### ISSUE THREAD

**Issue by cloudusers** [Tencent/CodeAnalysis#420]
![image](https://user-images.githubusercontent.com/16657639/174463565-7a4347b0-9d4e-4eab-bf21-7d5d82f64fde.png)

**Comment by Lingghh** [comment]
可以在分析方案中配置一下编译命令：
<img width="2503" alt="配置位置" src="https://user-images.githubusercontent.com/5992684/174515026-18042ead-e129-4c8d-816d-72b4c6d6a138.png">

**Comment by cloudusers** [comment]
这个有对应的工具命令提示吗，输入什么编译命令

![image](https://user-images.githubusercontent.com/16657639/174516689-60b5ab0c-1294-4cad-9c35-26724e57189b.png)

**Comment by cloudusers** [comment]
已解决：
编译命令中输入：mvn compile
