### ISSUE TITLE
使用androidlint工具，最终任务失败，内容报与unzip解压失败相关

### ISSUE THREAD

**Issue by cloudusers** [Tencent/CodeAnalysis#422]
![image](https://user-images.githubusercontent.com/16657639/174547406-50e1424e-688f-450f-a9dc-afd7ff1eb918.png)

下载任务结果的json内容如下：
"Traceback (most recent call last):\n  File \"task/puppytask.py\", line 65, in run\n    response = TaskRunner(self._request_file, self._response_file).run_task()\n  File \"task/runtask.py\", line 140, in task.runtask.__tskr__.__tskr__.run_task\n  File \"/Users/cloudusers/Desktop/MTWorkSpace/project/arch/CodeAnalysis/client/task/taskmgr.py\", line 73, in taskrunner\n    result = task.runner(params)\n  File \"/Users/cloudusers/Desktop/MTWorkSpace/project/arch/CodeAnalysis/client/task/model/analyze.py\", line 49, in runner\n    return self.tool.analyze(params)\n  File \"/Users/cloudusers/Desktop/MTWorkSpace/project/arch/CodeAnalysis/client/tool/androidlint.py\", line 133, in analyze\n    return self.__get_issues_from_file(error_output, source_dir)\n  File \"/Users/cloudusers/Desktop/MTWorkSpace/project/arch/CodeAnalysis/client/tool/androidlint.py\", line 204, in __get_issues_from_file\n    warning_data = ET.ElementTree(file=file_path)\n  File \"/usr/local/Cellar/python@3.7/3.7.13/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py\", line 558, in __init__\n    self.parse(file)\n  File \"/usr/local/Cellar/python@3.7/3.7.13/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py\", line 598, in parse\n    self._root = parser._parse_whole(source)\n  File \"<string>\", line None\nxml.etree.ElementTree.ParseError: no element found: line 1, column 0\n"

**Comment by cloudusers** [comment]
macos系统，用docker一键部署的本地环境

注：使用基本规划工具等是正常的，目前对工具选了“【Java】减包扫描” 此工具后报的如上异常

**Comment by Lingghh** [comment]
收到，感谢反馈，我们分析一下

**Comment by cloudusers** [comment]
CodeAnalysis/client/data/taskdirs/task_63/下的文件【已脱敏】

[workdir.zip](https://github.com/Tencent/CodeAnalysis/files/8938860/workdir.zip)

**Comment by cloudusers** [comment]
CodeAnalysis/client/data/taskdirs/task_63/下的文件【已脱敏】

[workdir.zip](https://github.com/Tencent/CodeAnalysis/files/8938919/workdir.zip)

**Comment by cyw3** [comment]
看起来是 结果文件 为空导致的，这里已经适配了，可以更新下 Client的代码 然后重试下
