### ISSUE TITLE
现在不支持https么？

### ISSUE THREAD

**Issue by tianmengyang** [Tencent/CodeAnalysis#435]
![image](https://user-images.githubusercontent.com/100125916/175762548-91ce14e2-bc2d-4675-b6b0-ca68650d7f0e.png)
输入的仓库地址是https开头的自动转换为http导致，导致无法通过页面获取到代码显示

**Comment by Lingghh** [comment]
可以通过配置 https://github.com/Tencent/CodeAnalysis/blob/main/server/projects/main/codedog/settings/open_base.py#L235 变量，将其改为True，用于支持https哈

**Comment by tianmengyang** [comment]
不行呀，本地客户端上传后，还是提示账号密码错误，自动更改成http的了，<~, ~>
![image](https://user-images.githubusercontent.com/100125916/176122809-10e767b5-8c04-4278-9646-4c77640c6396.png)

**Comment by tianmengyang** [comment]
通过Docker-Compose部署的，日志报错信息里面已经是请求https了
![image](https://user-images.githubusercontent.com/100125916/176857575-b91ac4ca-d0ea-4dfe-939b-a0d0dcbfb4d2.png)
但是平台上仓库地址还是http的导致我给这个仓库增加凭证时总是显示账号密码错误：
![image](https://user-images.githubusercontent.com/100125916/176858019-e9996ed7-8e54-4276-977e-bc2555bf98f5.png)
![image](https://user-images.githubusercontent.com/100125916/176858138-4cbbf01c-d783-476f-88ea-3a1c1b9e1467.png)

**Comment by Lingghh** [comment]
> 通过Docker-Compose部署的，日志报错信息里面已经是请求https了 ![image](https://user-images.githubusercontent.com/100125916/176857575-b91ac4ca-d0ea-4dfe-939b-a0d0dcbfb4d2.png) 但是平台上仓库地址还是http的导致我给这个仓库增加凭证时总是显示账号密码错误： ![image](https://user-images.githubusercontent.com/100125916/176858019-e9996ed7-8e54-4276-977e-bc2555bf98f5.png) ![image](https://user-images.githubusercontent.com/100125916/176858138-4cbbf01c-d783-476f-88ea-3a1c1b9e1467.png)

第一张图片下方会包含对应的异常信息，能否提供下哈

**Comment by tianmengyang** [comment]
![image](https://user-images.githubusercontent.com/100125916/176978148-fb8bba37-a100-4392-874e-f2321090a81d.png)

**Comment by Lingghh** [comment]
收到，我们处理下

**Comment by tianmengyang** [comment]
好嘞

**Comment by Lingghh** [comment]
@tianmengyang 最新版本代码已支持https，可以拉取试试

开启方式：需要调整main服务配置文件https://github.com/Tencent/CodeAnalysis/blob/main/server/projects/main/codedog/settings/open_base.py#L235变量，将其改为True，用于支持https哈

**Comment by tianmengyang** [comment]
好的，需要重新部署Server么，有没有什么办法卸载之前部署的Server呀

**Comment by Lingghh** [comment]
需要重新部署，可以按下面步骤执行一下：
1. git pull最新代码，
2. 执行``docker-compose build tca-main``
3. 执行``compose_init.sh``

**Comment by tianmengyang** [comment]
我这边测试可以了
