### ISSUE TITLE
Jenkins初次构建默认的扫描方案能否修改

### ISSUE THREAD

**Issue by AzuoHealer** [Tencent/CodeAnalysis#440]

**Comment by zthzhang111** [comment]
初次构建想指定一个分析方案的话，需要先在客户端创建好分析方案并设置为默认方案，这样在Jenkins启动后就会使用默认方案；如果分析列表没有默认方案的话，就会使用基础规则包的扫描方案

**Comment by AzuoHealer** [comment]
@zthzhang111 Jenkins启动之前在tca web上是没有项目的，那样怎么设置分析方案？难不成我需要把git上所有的项目拉到tca上配置好分析方案吗？

**Comment by AzuoHealer** [comment]
@zthzhang111 在客户端哪个文件配置分析方案？

**Comment by zthzhang111** [comment]
@AzuoHealer 登记代码库以后就可以在分析方案列表创建
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/96770128/176822172-7a7d450c-24cc-44be-8005-91ae3fb1f556.png">

**Comment by AzuoHealer** [comment]
@zthzhang111 在Jenkins进行第一次审计之前 是不会在服务器上有登记的代码仓库的。

**Comment by AzuoHealer** [comment]
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/39117380/176849014-cd30d846-2877-4ae9-a4fc-d2d1fad043aa.png">

**Comment by AzuoHealer** [comment]
![image](https://user-images.githubusercontent.com/39117380/176849239-6ebcafda-c846-4686-a0c8-ef2ae9ebc263.png)

**Comment by AzuoHealer** [comment]
想知道这个ref_scheme_id 从哪儿获取

**Comment by zthzhang111** [comment]
@AzuoHealer ref_scheme_id这个是分析方案模版ID，后面我会把这个参数加到插件里
<img width="734" alt="image" src="https://user-images.githubusercontent.com/96770128/176849922-79ae6cfb-014a-4399-b0dd-ddc5a877842a.png">

**Comment by bensonhome** [comment]
@AzuoHealer 用ref_scheme_id确实可以达到你想要的效果，首次创建时会参照模板创建一个方案。
不过这里需要把scan_plan名称也写上，创建方案时以该名称命名。

**Comment by AzuoHealer** [comment]
@bensonhome @zthzhang111 可以了，感谢，顺便咨询下，有没有什么方法可以批量修改项目然后增加tca构建步骤的方法

**Comment by bensonhome** [comment]
@AzuoHealer 增加tca构建步骤是指？你是要要批量修改分析方案里的配置？修改规则包？

**Comment by AzuoHealer** [comment]
@bensonhome 在Jenkins项目里加入tca代码审计的步骤。是只能改job的xml吗

**Comment by bensonhome** [comment]
@AzuoHealer 如果项目多的话，是否可以通过Jenkinsfile的方式配置流水线，修改Jenkinsfile就可以了
