### ISSUE TITLE
【编译问题】使用需要编译的规则时，是否需要在代码库中自己加入对应的插件

### ISSUE THREAD

**Issue by ZQiannnn** [Tencent/CodeAnalysis#441]
如 spotbugs,需要增加 spotbugs-maven-plugins 自己配置好吗？

如果有infer规则，编译需要用infer进行编译吗？

**Comment by cyw3** [comment]
TCA这边的原则是尽可能非侵入式地进行代码仓库的代码分析。

不过这个也依赖于工具本身不需要额外的配置才行。具体工具具体分析。

目前TCA上集成的工具绝大部分不需要额外的编译配置。

- spotbugs：只需要确保代码库能够编译通过即可；
- infer：需要使用infer编译，不过这个TCA会自动调用infer来监控捕获编译过程。
