### ISSUE TITLE
添加规则是否可以以工具为维度添加

### ISSUE THREAD

**Issue by ZQiannnn** [Tencent/CodeAnalysis#445]
规则太多，仅仅用现有维度无法特别好的添加和剔除规则，比如NPE检测，开了java基础相关的官方包，实际没有spotbugs规则执行，想找到这条规则很难

**Comment by nickcdon** [comment]
后续我们会开放工具的相关筛选，提供便捷的添加规则方式

**Comment by b3tterm4n** [comment]
同求

**Comment by nickcdon** [comment]
已上线该功能，可以拉取最新版本
