### ISSUE TITLE
「需求」增加并发

### ISSUE THREAD

**Issue by AzuoHealer** [Tencent/CodeAnalysis#447]

**Comment by cyw3** [comment]
这里是指哪方面的并发呢？Server的任务并发，还是Client的工具执行并发？

**Comment by AzuoHealer** [comment]
Client工具执行并发

**Comment by bensonhome** [comment]
@AzuoHealer 6月14日的[v1.3.1](https://github.com/Tencent/CodeAnalysis/releases/tag/20220614.1)版本就已经支持client工具并发了，是不是没有用最新代码？

**Comment by AzuoHealer** [comment]
我客户端可能没更新，我试试
