### ISSUE TITLE
job_context内的scm_url与项目的scm_url不匹配

### ISSUE THREAD

**Issue by agentchang** [Tencent/CodeAnalysis#45]
![image](https://user-images.githubusercontent.com/97286623/148710158-df77accf-b9f4-4407-b23c-57f7f791b954.png)
![image](https://user-images.githubusercontent.com/97286623/148710168-8f64d208-1931-4aef-9fdd-cb804011e34e.png)
客户端通过ssh clone 的代码，在 web 显示的仓库地址为 http://ssh/gerrit，只能识别 http 仓库地址吗？

**Comment by Lingghh** [comment]
这里上报数据时本地代码库地址与平台登记代码库地址需要是一致的哈

**Comment by agentchang** [comment]
> 这里上报数据时本地代码库地址与平台登记代码库地址需要是一致的哈

我直接通过 client 推送的，但是平台把 ssh 仓库地址识别为了 http

**Comment by Lingghh** [comment]
本地scm_url格式是 ssh://git@xx:port/xx 吗？

**Comment by agentchang** [comment]
是的

**Comment by Lingghh** [comment]
这里建议先用http触发哈，ssh格式我们需要兼容一下
