### ISSUE TITLE
外部MySQL数据库大小写敏感问题

### ISSUE THREAD

**Issue by ZQiannnn** [Tencent/CodeAnalysis#469]
mysql数据库版本： PolarDB  100% 兼容 MySQL 5.7
tca版本: v1.4.0

实际使用时遇到两个问题：
1. 在新建代码库凭证的时候一直报错外键错误，经排查
`authen_scmaccount.auth_origin_id` 写入的是`Codedog`,关联的外键表`base_origin.name`中的是`codedog`
本地docker-compose部署无此问题

2.client运行localscan的时候，一直报错无权限，经排查
request.user是`codedog`，实际上的admin用户是`CodeDog`,非python技术栈无法继续跟踪，
另外发现一个有意思的点，不知道什么时候自动新建了一个`codedog`用户，把他改成超级管理员client就不会报无权限的错误了
<img width="1737" alt="image" src="https://user-images.githubusercontent.com/19886406/180997855-a1f51132-12bc-4cc0-997c-ac559f430654.png">

**Comment by ZQiannnn** [comment]
MySQL相关配置：
<img width="393" alt="image" src="https://user-images.githubusercontent.com/19886406/180998176-7953b469-cb95-474e-b634-33deca5760d8.png">

**Comment by Lingghh** [comment]
感谢反馈，我们处理下

**Comment by Lingghh** [comment]
@ZQiannnn 目前最新代码已经做了处理，可以拉取最新代码试试
如果出现重复值报错，可以到数据库将非``CodeDog``格式的codedog 字符串进行调整或删除
