### ISSUE TITLE
docker-compose安装报错

### ISSUE THREAD

**Issue by wangsanshi123** [Tencent/CodeAnalysis#480]
版本：20220718.1

报错详情：
main-worker_1      | [2022-07-28 15:23:54,728: ERROR/ForkPoolWorker-10] Task apps.job.tasks.jobcheck.monitor_closing_job[49f5e5c1-e717-4e9c-81fd-803a35675676] raised unexpected: TypeError("'datetime.timedelta' object is not callable")
main-worker_1      | Traceback (most recent call last):
main-worker_1      |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 451, in trace_task
main-worker_1      |     R = retval = fun(*args, **kwargs)
main-worker_1      |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 734, in __protected_call__
main-worker_1      |     return self.run(*args, **kwargs)
main-worker_1      |   File "/var/www/django/codedog/apps/job/tasks/jobcheck.py", line 103, in monitor_closing_job
main-worker_1      |     if job.save_time() < settings.CLOSING_JOB_TIMEOUT:
main-worker_1      | TypeError: 'datetime.timedelta' object is not callable
main-worker_1      | -2022-07-28 15:23:54,728-ERROR-celery.app.trace: Task apps.job.tasks.jobcheck.monitor_closing_job[49f5e5c1-e717-4e9c-81fd-803a35675676] raised unexpected: TypeError("'datetime.timedelta' object is not callable")
main-worker_1      | Traceback (most recent call last):
main-worker_1      |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 451, in trace_task
main-worker_1      |     R = retval = fun(*args, **kwargs)
main-worker_1      |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 734, in __protected_call__
main-worker_1      |     return self.run(*args, **kwargs)
main-worker_1      |   File "/var/www/django/codedog/apps/job/tasks/jobcheck.py", line 103, in monitor_closing_job
main-worker_1      |     if job.save_time() < settings.CLOSING_JOB_TIMEOUT:
main-worker_1      | TypeError: 'datetime.timedelta' object is not callable

**Comment by Lingghh** [comment]
感谢反馈，我们处理下

**Comment by Lingghh** [comment]
目前已修复，可以拉取最新代码试试
