### ISSUE TITLE
docker-compose安装报错 --celery和django-celery-results版本冲突

### ISSUE THREAD

**Issue by wangsanshi123** [Tencent/CodeAnalysis#482]
版本：20220718.1
安装方式：docker-compose up
错误详情
ERROR: Cannot install -r requirements.txt (line 18) and celery==5.2.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested celery==5.2.2
    django-celery-results 2.4.0 depends on celery<6.0 and >=5.2.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
The command '/bin/sh -c mkdir -p log/ &&     mkdir ~/.pip/ && echo "[global]\nindex-url = https://mirrors.cloud.tencent.com/pypi/simple" >> ~/.pip/pip.conf &&     pip install -U setuptools pip &&     pip install -r requirements.txt' returned a non-zero code: 1
ERROR: Service 'main-server' failed to build

解决办法：
将\server\configs\requirements.txt等python依赖包中的 celery==5.2.2改为 celery==5.2.3即可

**Comment by Lingghh** [comment]
感谢反馈，这一块已做处理，可以拉取最新代码进行部署

**Comment by wangsanshi123** [comment]
给力
