### ISSUE TITLE
入库失败

### ISSUE THREAD

**Issue by wangsanshi123** [Tencent/CodeAnalysis#488]
版本：0f8aa47327727c01a6f99f772d8dfd09792d1736
安装方式：docker
表现：
![image](https://user-images.githubusercontent.com/15081998/181725902-d7cfd61b-b9e3-4b7c-9476-83d5e1625e67.png)

client日志：
client_1           | 2022-07-29 15:56:44,484-INFO: node status profiling thread is started.
client_1           | 2022-07-29 15:56:44,484-INFO: task loop is started.
client_1           | 2022-07-29 16:26:33,111-INFO: node is free: True, get task: name=checkstyle, id=6, task_version=2.0
client_1           | 2022-07-29 16:26:33,159-INFO: clean data directory ...
client_1           | 2022-07-29 16:26:33,167-INFO: Python 3.7.12
client_1           | 2022-07-29 16:26:33,262-INFO: Task_6 (CheckStyle) starts ...
client_1           | 2022-07-29 16:57:46,573-INFO: task checkstyle with id 6 is done
client_1           | 2022-07-29 16:57:46,573-INFO: uploading task(checkstyle) result(code:203) to server
client_1           | 2022-07-29 16:57:46,895-INFO: result upload finished

节点管理：
![image](https://user-images.githubusercontent.com/15081998/181726208-9873a555-8836-47dd-98c1-738f0d21b3dd.png)

**Comment by Lingghh** [comment]
这里看起来是工具拉取异常了，默认从github拉取会比较慢，可以参考这个文档调整client/config.ini文件，指定工具通过腾讯工蜂拉取

https://tencent.github.io/CodeAnalysis/zh/guide/%E5%AE%A2%E6%88%B7%E7%AB%AF/%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E.html#%E4%B8%80%E3%80%81%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE
<img width="857" alt="image" src="https://user-images.githubusercontent.com/5992684/181727871-2b7b1c7d-4b74-4d5c-a234-e96a3679a9c4.png">

调整后，需要执行一下 
```bash
docker-compose build client
docker-compose up -d client
```

**Comment by wangsanshi123** [comment]
> 这里看起来是工具拉取异常了，默认从github拉取会比较慢，可以参考这个文档调整client/config.ini文件，指定工具通过腾讯工蜂拉取
> 
> https://tencent.github.io/CodeAnalysis/zh/guide/%E5%AE%A2%E6%88%B7%E7%AB%AF/%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E.html#%E4%B8%80%E3%80%81%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE <img alt="image" width="857" src="https://user-images.githubusercontent.com/5992684/181727871-2b7b1c7d-4b74-4d5c-a234-e96a3679a9c4.png">
> 
> 调整后，需要执行一下
> 
> ```shell
> docker-compose build client
> docker-compose up -d client
> ```

按照以上做了后，又卡在入库这里
![image](https://user-images.githubusercontent.com/15081998/181743818-8bb81274-1f1e-4d6b-b471-68a1f401b088.png)

**Comment by thelastwizardofthecentury** [comment]
请问解决了吗？我也一直在入库中
