### ISSUE TITLE
任务卡住，且取消不成功

### ISSUE THREAD

**Issue by wangsanshi123** [Tencent/CodeAnalysis#495]
1，任务卡在findbugs和spotbugs这两个任务了。通过节点管理工具，把compile全部取消掉后，还是卡在这两个任务。
![image](https://user-images.githubusercontent.com/15081998/182107441-01ca73e5-7ca1-4e91-a0b7-beea3c7e6085.png)
2，然后把取消任务，显示是成功的，但是重新开启新的任务显示有任务正在运行。
![image](https://user-images.githubusercontent.com/15081998/182107654-9e81ca30-6c6e-434b-9d6c-50b1d3c62a17.png)
![image](https://user-images.githubusercontent.com/15081998/182107693-f772d4d1-5121-455e-a932-3bd72408080b.png)
3，尝试通过docker-compse down,docker-compose up -d重启所有服务，仍然没有效果

**Comment by Lingghh** [comment]
可以执行一下`docker-compse logs -f analysis-worker`看看是否有异常

**Comment by cyw3** [comment]
1. 这些是编译型工具，compile阶段是必要的

**Comment by wangsanshi123** [comment]
Attaching to codeanalysis_analysis-worker_1
[36manalysis-worker_1  |[0m -2022-08-01 16:25:38,583-DEBUG-asyncio: Using selector: EpollSelector
[36manalysis-worker_1  |[0m  
[36manalysis-worker_1  |[0m  -------------- celery@e892ab7b9ee2 v5.2.3 (dawn-chorus)
[36manalysis-worker_1  |[0m --- ***** ----- 
[36manalysis-worker_1  |[0m -- ******* ---- Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-debian-11.2 2022-08-01 16:25:39
[36manalysis-worker_1  |[0m - *** --- * --- 
[36manalysis-worker_1  |[0m - ** ---------- [config]
[36manalysis-worker_1  |[0m - ** ---------- .> app:         codedog:0x7f0d7c11d750
[36manalysis-worker_1  |[0m - ** ---------- .> transport:   redis://redis:6379/0
[36manalysis-worker_1  |[0m - ** ---------- .> results:     disabled://
[36manalysis-worker_1  |[0m - *** --- * --- .> concurrency: 2 (prefork)
[36manalysis-worker_1  |[0m -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
[36manalysis-worker_1  |[0m --- ***** ----- 
[36manalysis-worker_1  |[0m  -------------- [queues]
[36manalysis-worker_1  |[0m                 .> celery           exchange=celery(direct) key=celery
[36manalysis-worker_1  |[0m                 
[36manalysis-worker_1  |[0m 
[36manalysis-worker_1  |[0m [tasks]
[36manalysis-worker_1  |[0m   . apps.base.tasks.server_health_check
[36manalysis-worker_1  |[0m   . apps.codelint.tasks.datahandler.clean_deleted_issuedetail
[36manalysis-worker_1  |[0m   . apps.codelint.tasks.datahandler.sync_checkpackage_rule_map
[36manalysis-worker_1  |[0m   . apps.codeproj.tasks.scanresult.clean_expired_scan
[36manalysis-worker_1  |[0m   . apps.codeproj.tasks.scanresult.clean_job_data
[36manalysis-worker_1  |[0m   . apps.codeproj.tasks.scanresult.put_scan_result
[36manalysis-worker_1  |[0m 
[36manalysis-worker_1  |[0m /usr/local/lib/python3.7/site-packages/celery/platforms.py:841: SecurityWarning: You're running the worker with superuser privileges: this is
[36manalysis-worker_1  |[0m absolutely not recommended!
[36manalysis-worker_1  |[0m 
[36manalysis-worker_1  |[0m Please specify a different user using the --uid option.
[36manalysis-worker_1  |[0m 
[36manalysis-worker_1  |[0m User information: uid=0 euid=0 gid=0 egid=0
[36manalysis-worker_1  |[0m 
[36manalysis-worker_1  |[0m   uid=uid, euid=euid, gid=gid, egid=egid,
[36manalysis-worker_1  |[0m [2022-08-01 16:25:39,591: INFO/MainProcess] Connected to redis://redis:6379/0
[36manalysis-worker_1  |[0m -2022-08-01 16:25:39,591-INFO-celery.worker.consumer.connection: Connected to redis://redis:6379/0
[36manalysis-worker_1  |[0m [2022-08-01 16:25:39,594: INFO/MainProcess] mingle: searching for neighbors
[36manalysis-worker_1  |[0m -2022-08-01 16:25:39,594-INFO-celery.worker.consumer.mingle: mingle: searching for neighbors
[36manalysis-worker_1  |[0m [2022-08-01 16:25:40,603: INFO/MainProcess] mingle: all alone
[36manalysis-worker_1  |[0m -2022-08-01 16:25:40,603-INFO-celery.worker.consumer.mingle: mingle: all alone
[36manalysis-worker_1  |[0m [2022-08-01 16:25:40,628: WARNING/MainProcess] /usr/local/lib/python3.7/site-packages/celery/fixups/django.py:204: UserWarning: Using settings.DEBUG leads to a memory
[36manalysis-worker_1  |[0m             leak, never use this setting in production environments!
[36manalysis-worker_1  |[0m   leak, never use this setting in production environments!''')
[36manalysis-worker_1  |[0m 
[36manalysis-worker_1  |[0m -2022-08-01 16:25:40,628-WARNING-py.warnings: /usr/local/lib/python3.7/site-packages/celery/fixups/django.py:204: UserWarning: Using settings.DEBUG leads to a memory
[36manalysis-worker_1  |[0m             leak, never use this setting in production environments!
[36manalysis-worker_1  |[0m   leak, never use this setting in production environments!''')
[36manalysis-worker_1  |[0m 
[36manalysis-worker_1  |[0m [2022-08-01 16:25:40,628: INFO/MainProcess] celery@e892ab7b9ee2 ready.
[36manalysis-worker_1  |[0m -2022-08-01 16:25:40,628-INFO-celery.apps.worker: celery@e892ab7b9ee2 ready.

**Comment by wangsanshi123** [comment]
> 1. 这些是编译型工具，compile阶段是必要的

![image](https://user-images.githubusercontent.com/15081998/182109700-974ba3cd-7022-4633-b4b9-14b034ae63e3.png)
能不能通过去掉勾选，把这个工具去掉？ 因为一直报编译不通过的错。加了编译命令也不行
![image](https://user-images.githubusercontent.com/15081998/182109973-8dea8705-0431-4fe8-9eff-5a3547b7d6c4.png)
怀疑是不是客户端的容器内没有预装maven(我是用的docker容器)

**Comment by wangsanshi123** [comment]
> 可以执行一下`docker-compse logs -f analysis-worker`看看是否有异常

刚刚运行了下docker-compse down ,可能之前的日志丢了

**Comment by Lingghh** [comment]
1. 可以访问一下 `{host}/manage/jobs` 看看是否有任务正在执行中
2. 客户端执行maven前需要自行安装下maven

**Comment by wangsanshi123** [comment]
在客户端中装了maven后就可以了。apt install maven
