### ISSUE TITLE
“分析方案模板”模块中的添加自定义规则时，进行过滤，失效

### ISSUE THREAD

**Issue by wangsanshi123** [Tencent/CodeAnalysis#530]
添加“安全”进行过滤，发现搜索后的结果异常
![eaa300cff838a23c9cec795e99fecc6](https://user-images.githubusercontent.com/15081998/184353695-96fd1fe6-1e65-4588-b28b-b7040deb4d17.jpg)

**Comment by nickcdon** [comment]
已经修复了，可以拉取最新代码更新下前端
