### ISSUE TITLE
执行java分析的时候报错需要输入编译命令

### ISSUE THREAD

**Issue by hq0419** [Tencent/CodeAnalysis#541]
![image](https://user-images.githubusercontent.com/23167007/185066167-886a3852-f6f8-4b10-a5ec-e50bc181869f.png)
![image](https://user-images.githubusercontent.com/23167007/185066234-1f5a11d4-f113-4c5e-abfa-f99a0409f6fb.png)
![image](https://user-images.githubusercontent.com/23167007/185066548-d0b0b5a6-8d04-44c0-9cde-34ff9c3a0e77.png)

**Comment by cyw3** [comment]
因为使用到了编译型工具，需要在对应项目的分析方案中 填写编译命令，并确保该项目能够在 客户端执行机器上 能够编译通过。

**Comment by hq0419** [comment]
多谢了
