### ISSUE TITLE
建议添加本地部署配置说明

### ISSUE THREAD

**Issue by m0re-work** [Tencent/CodeAnalysis#55]
建议添加本地私有化部署TCA工具的主机配置说明
如以下格式：
CPU：X 核
内存：X G
硬盘：X G

**Comment by bensonhome** [comment]
操作系统 | 最低配置要求
Linux/Mac/Windows: 8核16G内存，硬盘空间256G（可用空间不低于100G）
感谢建议，将添加到配置文档中

**Comment by zhang9w0v5** [comment]
要考虑被分析代码库的大小，如果代码库有200GB的话，还是按实际情况增加磁盘空间。
