### ISSUE TITLE
http://127.0.0.1:9001 用户密码是什么？

### ISSUE THREAD

**Issue by abel533** [Tencent/CodeAnalysis#552]
TCA服务状态监控平台：http://127.0.0.1:9001

TCA容器名称: tca-services

给了地址，没有密码，无法登录查看。(80端口的 CodeDog 无法登录 9001）。

**Comment by abel533** [comment]
另外除了github就没有其他镜像地址吗？

>执行结果：节点端SCM任务故障 NodeError: Error[203]: fatal: unable to access 'https://github.com/TCATools/linux-jdk1.8.0_65.git/': Failed to connect to github.com port 443: Connection timed out

**Comment by Lingghh** [comment]
感谢反馈，账号：tca，密码：tca，这一块我们在文档补充下
https://github.com/Tencent/CodeAnalysis/blob/main/scripts/docker/supervisord.conf

**Comment by Lingghh** [comment]
还支持工蜂镜像地址，可以看下配置文档 https://tencent.github.io/CodeAnalysis/zh/guide/%E5%AE%A2%E6%88%B7%E7%AB%AF/%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E.html#_2-%E9%85%8D%E7%BD%AEclient-config-ini%E6%96%87%E4%BB%B6
