### ISSUE TITLE
下载完配置文件，覆盖原始文件没用

### ISSUE THREAD

**Issue by jirufeng** [Tencent/CodeAnalysis#56]
使用docker启动的，启动分析时，下载了配置文件，覆盖client/codedog.ini，还是同样的结果。
![image](https://user-images.githubusercontent.com/19670860/148737878-87d6e3c0-9815-4553-a454-b92e2397a1f4.png)

**Comment by Lingghh** [comment]
这里需要在client目录下执行命令启动分析哈
