### ISSUE TITLE
java依赖漏洞扫描，多pom.xml文件的时候扫描没有漏洞结果

### ISSUE THREAD

**Issue by l0ners** [Tencent/CodeAnalysis#567]
下载文件后只有report.json文件

{
  "incr_scan": false,
  "issue_count": 0,
  "issue_encode": false,
  "summary": null,
  "issue_detail_paths": []
}

**Comment by cyw3** [comment]
已支持

**Comment by l0ners** [comment]
> 已支持

目前多个pom.xml结果仅显示其中一个pom.xml的漏洞
