### ISSUE TITLE
安装成功后一直卡在正在加载中

### ISSUE THREAD

**Issue by m0re-work** [Tencent/CodeAnalysis#57]
![image](https://user-images.githubusercontent.com/59357339/148739540-335f4236-3241-459d-8705-96b55e9ae836.png)
安装成功后一直卡在正在加载中

**Comment by nickcdon** [comment]
@m0re-work 麻烦可以看看是否接口请求存在5xx错误，或在server目录下再次执行./scripts/deploy.sh start

**Comment by m0re-work** [comment]
已经执行了，并不好用

**Comment by m0re-work** [comment]
报错 500 Internal Server Error

**Comment by m0re-work** [comment]
执行./scripts/deploy.sh start 后依旧存在500报错

**Comment by m0re-work** [comment]
![image](https://user-images.githubusercontent.com/59357339/148921697-fdfe0d3e-cc08-4aec-9c7f-8395d268e7dc.png)

**Comment by m0re-work** [comment]
![image](https://user-images.githubusercontent.com/59357339/148925831-62c3f2f8-3a65-495b-af37-d0aabfc532c5.png)
请求 URL: http://10.0.8.12/server/credential/api/v3/login/user/
请求方法: GET
状态代码: 502 Bad Gateway
远程地址: 10.0.8.12:80
引用站点策略: strict-origin-when-cross-origin
Connection: keep-alive
Content-Length: 559
Content-Type: text/html; charset=utf-8
Date: Tue, 11 Jan 2022 10:09:42 GMT
Server: nginx/1.20.1
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Authorization: CodeDog eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjQxODg3OTQ2LCJqdGkiOiIwYTM4ODE5ZmU3OGE0NmVlOTBjMWU3NWQ0MjhhNjdiMyIsInVzZXJfaWQiOiJDb2RlRG9nIn0.txlywAZ9okA4V9MMk23s6FXLnzJF09dvTVBZuYVSdiaN31cZaIdJNHXDuoY6Ml5VOPOPAM1g1LNwVDlqYQ2ZRXDuO8BnasIB6leO9lvY9d0dZ8YGZaTiLO7b7yWDQulwY8qboBoZPyBFEeHpd4t6EL64uxcTH1LG7Y8oMqPAMaM
Connection: keep-alive
Content-Type: application/json
Host: 10.0.8.12
Referer: http://10.0.8.12/teams
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/97.0.1072.55

**Comment by nickcdon** [comment]
@m0re-work 请问是docker部署的吗？

**Comment by nickcdon** [comment]
如果是docker部署，在根目录下可以执行下./compose_init.sh脚本试试

**Comment by nickcdon** [comment]
麻烦再参考对应server部署文档重试看看
本地部署文档：https://github.com/Tencent/CodeAnalysis/blob/main/doc/deploy.md
docker部署文档：https://github.com/Tencent/CodeAnalysis/blob/main/doc/deploy_dc.md

**Comment by nickcdon** [comment]
如果是docker部署，麻烦查看下是否已执行`./compose_init.sh`
![image](https://user-images.githubusercontent.com/18720809/148935010-82fadb7b-d412-4b2e-a5de-3b61335a9381.png)

**Comment by m0re-work** [comment]
就是参照本地部署文档部署的

**Comment by m0re-work** [comment]
![image](https://user-images.githubusercontent.com/59357339/148939152-2be7b203-49a3-4c8f-af2e-6b95e98e1590.png)
希望这部分可以完善

**Comment by nickcdon** [comment]
@m0re-work 请问目前是否还未解决？

**Comment by m0re-work** [comment]
未解决

**Comment by m0re-work** [comment]
[root@VM-8-12-centos CodeAnalysis-main]# ./compose_init.sh
Recreating codeanalysismain_redis_1 ... 
Recreating codeanalysismain_mysql_1 ... done
wait dbEnter password: 
.Enter password: 

Building file-server
ERROR: Forbidden path outside the build context: ../../dockerconfs/Dockerfile-common ()
ERROR: No container found for file-server_1
Building login-server
ERROR: Forbidden path outside the build context: ../../dockerconfs/Dockerfile-common ()
ERROR: No container found for login-server_1
Building analysis-server
ERROR: Forbidden path outside the build context: ../../dockerconfs/Dockerfile-common ()
ERROR: No container found for analysis-server_1
Building main-server
ERROR: Forbidden path outside the build context: ../../dockerconfs/Dockerfile-common ()
ERROR: No container found for main-server_1
Building main-server
ERROR: Forbidden path outside the build context: ../../dockerconfs/Dockerfile-common ()

**Comment by m0re-work** [comment]
镜像：腾讯云Lighthouse CentOS7.6

**Comment by Lingghh** [comment]
更新docker-compose,重新运行即可
这里需要将本地的docker-compose更新到2以上

**Comment by m0re-work** [comment]
安装docker-compose ing

**Comment by m0re-work** [comment]
重装了很多次依旧报错，对腾讯云服务器兼容性这么差吗

**Comment by Lingghh** [comment]
> 重装了很多次依旧报错，对腾讯云服务器兼容性这么差吗

这里是指重装docker-compose多次依旧报错么？还是上述的报错原因么？
能否提供一下对应的docker、docker-compose的版本信息，我们本地复现一下看看

**Comment by m0re-work** [comment]
官方文档部分缺少部分命令可能会出现相关问题，已经补充相关命令
