### ISSUE TITLE
能分析iOS项目吗

### ISSUE THREAD

**Issue by weinierfei** [Tencent/CodeAnalysis#573]
请问部署在Linux上能分析iOS项目吗？还是分析iOS项目得部署在macOS上？

**Comment by zhang9w0v5** [comment]
如果所用的规则包里的工具规则不需要Mac的编译环境，那么可以在Linux或Windows上进行分析，反之则依赖Mac的环境（例如Xcode携带的Clang等等）。

**Comment by weinierfei** [comment]
好的,感谢回复.
