### ISSUE TITLE
规则json修改源码不生效问题

### ISSUE THREAD

**Issue by lee-lib** [Tencent/CodeAnalysis#581]
我司开发人员将CodeAnalysis/server/projects/main/apps/scan_conf/management/commands/open_source/semgrep.json 等各个规则的d中description字段翻译成中文后重新部署CodeAnalysis，查看数据库表scan_conf_checkruledesc中description是中文了，但是扫描结果详情中依然是英文的。

**Comment by yql70** [comment]
麻烦提供下扫描结果详情的截图吧

**Comment by lee-lib** [comment]
![issue_02](https://user-images.githubusercontent.com/32378307/187190172-37b331ff-2125-4829-b395-e02491b38c8a.png)
![issue_03](https://user-images.githubusercontent.com/32378307/187190246-020527a3-d24a-4f2c-9125-7c78467d919e.png)
![issue_01](https://user-images.githubusercontent.com/32378307/187190261-3183e0ec-e7f9-4e3d-97af-d4cc81682a21.png)
图1是数据库scan_conf_checkruledesc表截图；
图2是CodeAnalysis/server/projects/main/apps/scan_conf/management/commands/open_source/semgrep.json中截图，description是中文；
图3是实际扫描的结果截图，依然是英文

**Comment by lee-lib** [comment]
部署过程是./quick_install.sh local deploy，待部署脚本执行完成后，重新找到相关规则json文件，将rule文件中的title和description字段翻译后，重新部署执行./quick_install.sh local deploy，扫描项目后，title字段变成中文，但是description依然是英文

**Comment by yql70** [comment]
扫描结果中的description是工具输出的msg，不是工具json中的description，所以还是英文，而工具json中的description会在近期上线展示。

**Comment by lee-lib** [comment]
> 

好的，感谢答疑

**Comment by nickcdon** [comment]
工具json中的description已经上线展示了
