### ISSUE TITLE
建议: 工具仓库设置为模板仓库

### ISSUE THREAD

**Issue by auula** [Tencent/CodeAnalysis#586]
您好，建议将工具插件那个demo仓库设置为一个官方模板仓库，这样别人要开发自己的插件就可以直接fork模板仓库进行开发了，这种基于模块仓库比文档上那个demo仓库方式要好，你们官方更新也方便直接更新块模板仓库就行了，而其他如果要开发插件的话直接fork模板仓库进行开发就行了，而模板仓库里面的内容就在其中。

[模板仓库设置教程请查看Github官方文档](https://docs.github.com/cn/repositories/creating-and-managing-repositories/creating-a-template-repository)

![image](https://user-images.githubusercontent.com/38412458/187474330-494dbd61-f853-4a00-902c-187f4fd7a246.png)

**Comment by bensonhome** [comment]
@auula 好建议，已经采纳，设置为模板仓库：
https://github.com/TCATools/demo_tool
