### ISSUE TITLE
[需求]Jenkins插件功能优化

### ISSUE THREAD

**Issue by AzuoHealer** [Tencent/CodeAnalysis#598]
增加控制流水线成功或失败

**Comment by Lingghh** [comment]
感谢反馈，我们评估看看怎么支持哈

**Comment by bensonhome** [comment]
@AzuoHealer 已经支持门禁，可以参考下使用文档：https://github.com/Tencent/CodeAnalysis/tree/main/plugins/jenkins_plugin

**Comment by AzuoHealer** [comment]
@Lingghh @bensonhome 感谢！

**Comment by bensonhome** [comment]
通过源码编译插件包，也可以直接使用编好的插件包 [jenkins_plugin.hpi](https://github.com/Tencent/CodeAnalysis/releases/download/20220907.1/jenkins_plugin.hpi)
