### ISSUE TITLE
Docker创建失败

### ISSUE THREAD

**Issue by merlinxcy** [Tencent/CodeAnalysis#6]
一直要求输入密码
![image](https://user-images.githubusercontent.com/18378246/148028188-c899ace7-5af2-4476-83a8-36e4deaaf213.png)

**Comment by cocorunning** [comment]
可以输入默认密码：``TCA!@#2021``（可以在docker-compose.yml中的mysql服务配置获取和修改默认密码

**Comment by merlinxcy** [comment]
> 可以输入默认密码：`TCA!@#2021`（可以在docker-compose.yml中的mysql服务配置获取和修改默认密码

谢谢解决了
