### ISSUE TITLE
code analysis stuck in init tools

### ISSUE THREAD

**Issue by tengzhexiao** [Tencent/CodeAnalysis#60]
`[Tools init]:  10%|█████                                             | 1/10 [00:04<00:36,  4.10s/it]2022-01-10 18:35:55,168-WARNING-cmdgit: no .git/config file in work_tree
2022-01-10 18:52:33,028-INFO-util.logutil:
****************************************************************************************************
代码分析结果:
NodeError: Error[203]: error: external filter 'git-lfs filter-process' failed
fatal: bin/model/lexeme/model.tflite: smudge filter lfs failed
****************************************************************************************************
2022-01-10 18:52:33,028-INFO-util.logutil: json report: XXX\CodeAnalysis/client/scan_status.json
2022-01-10 18:52:33,028-ERROR-util.logutil: NodeError: Error[203]: error: external filter 'git-lfs filter-process' failed
fatal: bin/model/lexeme/model.tflite: smudge filter lfs failed
Traceback (most recent call last):
  File "XXX\CodeAnalysis\client\node\gitload.py", line 153, in __retry_checkout
    self._scm_client.checkout()
  File "src\_cmdgit.py", line 1585, in src._cmdgit.CmdGit.checkout
  File "src\_cmdgit.py", line 1426, in src._cmdgit.CmdGit._clone
  File "src\_cmdgit.py", line 224, in src._cmdgit.CmdGit._cmd_error_check
util._scmbase.ScmCommandError: error: external filter 'git-lfs filter-process' failed
fatal: bin/model/lexeme/model.tflite: smudge filter lfs failed`

scan_status.json:

{
  "status": "error",
  "error_code": 203,
  "url": "http://XXXX/code-analysis/repos/1/projects/1/scan-history",
  "text": "扫描异常",
  "description": "NodeError: Error[203]: error: external filter 'git-lfs filter-process' failed\nfatal: bin/model/lexeme/model.tflite: smudge filter lfs failed",
  "scan_report": {}
}

**Comment by cyw3** [comment]
这是Github对LFS的带宽限制，目前已经重新移除对应工具库的LFS。
麻烦删掉以下目录，然后重试下看看

```
rm -rf <TCA Client>/data/tools/puppy-tools-config
rm -rf <TCA Client>/data/tools/linux-dart-sdk-v2.7.2
```

**Comment by Grapefruit-Shu** [comment]
这个init一直遇到各种问题，进度有时候20%就挂掉，有时候50%，还有一次90%，上午跑了10多次，没有一次成功，都是init的时候报错了。
这个除了删除对应的目录还有别的方案吗

**Comment by zhang9w0v5** [comment]
init会初始化一些工具，这些工具从网络上拉下去，多数情况是网络问题。首次初始化就绪之后，以后每次都是增量update工具，会好很多。

最好的解决方案，当前我们认为是私有化部署一套，在自己的网络里部署（包括工具库）。

**Comment by cyw3** [comment]
可以手动把这些工具都拉下来，存放到client/data/tools目录下。
另外在client/config.ini的[common]中设置一个参数：
USE_LOCAL_TOOL=True
就可以不自动拉取工具，直接使用本地拉好的工具。

**Comment by Grapefruit-Shu** [comment]
那些工具的git地址可以在哪里看，我去都单独拉取下来，再按照你们说的直接使用本地的

**Comment by cyw3** [comment]
https://github.com/TCATools/puppy-tools-config/blob/master/linux_tools.ini#L71
可以在这里找到配置

https://github.com/TCATools

**Comment by Grapefruit-Shu** [comment]
哦哦，好的。谢谢

**Comment by Grapefruit-Shu** [comment]
我还想问个问题，就是 这里设置的是 PASSWORD_KEY=a6x4c7esudcv396w  密码的，用户名是哪里设置的，还是说可以增加username字段的，我今天上午改过一次 config.ini的配置的，报错
NodeError: Error[203]: fatal: could not read Username for 'https://gitlab.testplus.cn': No such device or address

**Comment by Grapefruit-Shu** [comment]
这个gitlab的地址 是我们内部的一个gitlab地址的

**Comment by Grapefruit-Shu** [comment]
还是说我这个地址  直接使用  https://username:@gitlab.testplus.cn  这种，用户名从这个url中提取

**Comment by bensonhome** [comment]
@Grapefruit-Shu 用户名和密码是可以单独配置的，可以在config.ini里单独增加以下字段值（并不是PASSWORD_KEY字段）：
[TOOL_LOAD_ACCOUNT]
; 拉取工具的账号密码,必要时（如使用内部git服务存储工具库）可以选用,默认不需要
; [可选]拉取工具库的公共账号密码
USERNAME=
PASSWORD=

**Comment by Grapefruit-Shu** [comment]
好的，谢谢

**Comment by bensonhome** [comment]
@Grapefruit-Shu 这块配置也已经更新了，可以更新下代码
