### ISSUE TITLE
redis can't connected

### ISSUE THREAD

**Issue by TimerZz007** [Tencent/CodeAnalysis#616]
部署方式：源码部署
问题：main worker 日志显示redis无法连接，tca server 任务执行详情页面卡住不动

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/64236661/189833363-2a6a93a4-714e-41e9-9573-d1680257cbe6.png">

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/64236661/189833478-78bb9fc5-3db9-4516-a236-ae47dff4c97f.png">

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/64236661/189833561-2ec3bfe0-54a5-49c5-a4b8-0ee160157c6d.png">

![image](https://user-images.githubusercontent.com/64236661/189833623-09b8af60-25e9-4f09-832f-e743dd15880a.png)

**Comment by Lingghh** [comment]
感谢反馈，我们分析下

**Comment by TimerZz007** [comment]
这个问题同样还会出现在扫完毕后，插入数据库的时候，导致结果无法插入数据库
![image](https://user-images.githubusercontent.com/64236661/190574969-46063194-b144-49f5-a5c2-fcb2082813f2.png)

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/64236661/190575077-eb2a3c97-1958-4cc2-855b-6beb6078f4c6.png">

**Comment by Lingghh** [comment]
这个是属于组件问题，我们已经有初步方案，这两天验证ok会支持上

**Comment by TimerZz007** [comment]
我们换了一台amd的服务器，解决了这个错误
