### ISSUE TITLE
不能拉gitlab代码仓库

### ISSUE THREAD

**Issue by TimerZz007** [Tencent/CodeAnalysis#621]
仓库登记认证通过
启动分析无法拉去gitlab代码

![image](https://user-images.githubusercontent.com/64236661/190391426-7166544e-e9f6-494a-8275-2f5284f587e9.png)

错误日志如下：
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/64236661/190391825-3459652c-3603-445d-b4e2-cd9e14585798.png">

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/64236661/190392075-91fbcd86-4521-455b-b8a7-cd6a9aba2a2e.png">

**Comment by Lingghh** [comment]
在部署tca服务的机器上能否clone自建gitlab的代码库么

**Comment by TimerZz007** [comment]
手动git clone可以拉下来，试过了

**Comment by TimerZz007** [comment]
ssh key可以拉取
