### ISSUE TITLE
docker部署更新版本时，遇到报错

### ISSUE THREAD

**Issue by l0ners** [Tencent/CodeAnalysis#641]
旧版代码与新版代码不在同一个目录，没有覆盖。
旧版的镜像已经删掉。
因为网络问题，本地构建镜像总是失败，所以重新拉取最新的镜像，执行命令 ./quick_install.sh docker deploy
出现这个目录的报错。
宿主机是没有这两个目录，镜像也是最新拉取的，所以没搞懂是什么原因导致的。
![image](https://user-images.githubusercontent.com/68841518/192729441-76b77b96-64c9-4855-8ded-94f8b97d5059.png)

**Comment by Lingghh** [comment]
感谢反馈，这是已知问题，我们发新镜像修复下

**Comment by l0ners** [comment]
> 感谢反馈，这是已知问题，我们发新镜像修复下

好的

**Comment by Lingghh** [comment]
最新镜像已经解决，可以拉取试试

**Comment by l0ners** [comment]
> 最新镜像已经解决，可以拉取试试

最新镜像拉取后可以了，感谢
