### ISSUE TITLE
【bug】自定义工具重新编辑规则报错

### ISSUE THREAD

**Issue by D0n9** [Tencent/CodeAnalysis#700]
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/16030944/202145096-2c59a8cb-21ad-4ac2-8dbb-9aa32f101155.png">

添加规则正常，再次编辑规则的时候报 404

**Comment by nickcdon** [comment]
感谢反馈，我们排查修复下

**Comment by nickcdon** [comment]
> 



> <img alt="image" width="1195" src="https://user-images.githubusercontent.com/16030944/202145096-2c59a8cb-21ad-4ac2-8dbb-9aa32f101155.png">
> 
> 添加规则正常，再次编辑规则的时候报 404

已修复，可以拉取最新代码
