### ISSUE TITLE
API接口调用失败，提示{'status_code': 401, 'code': 1000, 'msg': '身份认证信息未提供。'}

### ISSUE THREAD

**Issue by jklZy1** [Tencent/CodeAnalysis#709]
按照api文档说明，增加header头字段
{
  "Authorization": "当前user的token"
}
但是调用后一直鉴权不通过，提示我身份认证信息未提供，我的token信息是从控制台-个人令牌那里取的，为什么还是报错

**Comment by Lingghh** [comment]
header格式可以调整下面格式试试
```
{
  "Authorization": "Token 当前user的token"
}
```

**Comment by jklZy1** [comment]
> header格式可以调整下面格式试试
> 
> ```
> {
>   "Authorization": "Token 当前user的token"
> }
> ```

现在可以了
