### ISSUE TITLE
[Error] 仓库登记成功后，开启第一次代码分析报代码库与账号不匹配

### ISSUE THREAD

**Issue by Sanshix** [Tencent/CodeAnalysis#726]
![41670222410_ pic](https://user-images.githubusercontent.com/25609960/205568080-0d71214b-9227-487d-93c1-74d1fb5274b3.jpg)
<img width="818" alt="image" src="https://user-images.githubusercontent.com/25609960/205570240-fafbfee4-9196-4392-b8f8-9e724ef1af37.png">

**Comment by Sanshix** [comment]
尝试在容器中git clone 代码仓库，可以正常clone代码到容器中

**Comment by Lingghh** [comment]
登记的代码库支持https访问吗？

**Comment by Sanshix** [comment]
> 

不支持，仓库登记的时候填写的是http地址
