### ISSUE TITLE
连接svn仓库失败

### ISSUE THREAD

**Issue by 980468094** [Tencent/CodeAnalysis#768]
![image](https://user-images.githubusercontent.com/49626869/219330213-3dfccffa-4b9f-4606-838a-6fd1bca9b126.png)

**Comment by 980468094** [comment]
svn代码链接已确定是正确的，参考FAQ（https://tencent.github.io/CodeAnalysis/zh/quickStarted/FAQ.html#server%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E4%B8%8E%E5%A4%84%E7%90%86%E6%96%B9%E6%B3%95）中没有合适的解答

**Comment by brucehsie** [comment]
我们也遇到这个问题， SVN代码链接确保是正确的，用户名/密码正确， 通过SVN客户端可以正常连接。
登记代码仓库时，显示: cd_error 代码库及账号不匹配。

**Comment by Lingghh** [comment]
感谢反馈，我们已经定位到问题，今天发版修复

**Comment by 980468094** [comment]
现在SVN可以正常连接了，但是在配置项目分析的时候依然提示仓库与账号信息不匹配，以参考FAQ中相关解答确认自己的svn支持使用HTTPS连接，具体报错信息如下：
![image](https://user-images.githubusercontent.com/49626869/219938266-73910e5d-73c2-437f-8a32-3467889cb04e.png)
![bce85366186ea9f3172f9a2ad93ea0d](https://user-images.githubusercontent.com/49626869/219938273-c2220c71-d88e-4316-820a-1f953ac559f7.png)

**Comment by Lingghh** [comment]
感谢反馈，可以拉取最新代码试试
