### ISSUE TITLE
数据入库-执行结果：第三方依赖文件服务器异常 数据入库失败

### ISSUE THREAD

**Issue by ontheway01** [Tencent/CodeAnalysis#786]
参考了问题  #417 和 #41 
按问题列表提示查看，并非route相关，看worker的celery.log日志如下（本地环境是centos+ docker部署）：
源代码中不涉及ZIP格式文件，C语言扫描选择了Tscan-cpp工具规则，使用的在线分析，一直失败。

> -2023-03-08 09:12:06,577-DEBUG-urllib3.connectionpool: http://0.0.0.0:80 "PUT /server/files/public_server_temp/scandata/projects/13/scans/56/3e173f02bd4e11eda83302420a2c0102/error_msg.json HTTP/1.1" 200 24
> -2023-03-08 09:12:06,577-ERROR-apps.codeproj.core.base: [Project: 13][Job: 56][Scan: 56][Type :2]数据入库失败。[{'module': 'codelint', 'traceback': 'Traceback (most recent call last):\n  File "/CodeAnalysis/server/projects/analysis/apps/codeproj/core/base.py", line 78, in _put_module_result\n    method(self._scan, module_tasks)\n  File "/CodeAnalysis/server/projects/analysis/apps/codelint/job/__init__.py", line 33, in on_job_end\n    result_handler.handle()\n  File "/CodeAnalysis/server/projects/analysis/apps/codelint/job/linthandler.py", line 786, in handle\n    self.download_task_result()\n  File "/CodeAnalysis/server/projects/analysis/util/retrylib.py", line 41, in wrapper\n    return func(*args, **kwargs)\n  File "/CodeAnalysis/server/projects/analysis/apps/codelint/job/linthandler.py", line 666, in download_task_result\n    dir_path, _ = download_and_unzip_file(self._task_result["result_data_url"])\n  File "/CodeAnalysis/server/projects/analysis/util/retrylib.py", line 41, in wrapper\n    return func(*args, **kwargs)\n  File "/CodeAnalysis/server/projects/analysis/apps/codelint/job/utils.py", line 47, in download_and_unzip_file\n    return unzip(file_server.download_file(file_url))\n  File "/CodeAnalysis/server/projects/analysis/util/filemanager.py", line 29, in unzip\n    zip_file = zipfile.ZipFile(file_path)\n  File "/usr/local/lib/python3.7/zipfile.py", line 1258, in __init__\n    self._RealGetContents()\n  File "/usr/local/lib/python3.7/zipfile.py", line 1325, in _RealGetContents\n    raise BadZipFile("File is not a zip file")\nzipfile.BadZipFile: File is not a zip file\n', 'result_code': 116}]
> -2023-03-08 09:12:06,582-INFO-apps.codeproj.tasks.scanresult: [Project: 13][Job: 56][Scan: 56] 入库结束，开始执行回调

**Comment by ontheway01** [comment]
.docker_temp/logs/client/client_error.log 查看信息正常

> 2023-03-08 09:05:18,444-INFO: node is free: True, get task: name=tscan_cpp, id=251, task_version=2.0
> 2023-03-08 09:05:18,472-INFO: clean data directory ...
> 2023-03-08 09:05:18,492-INFO: Python 3.7.16
> 2023-03-08 09:05:18,584-INFO: Task_251 (Tscan-cpp) starts ...
> 2023-03-08 09:10:49,462-INFO: task tscan_cpp with id 251 is done
> 2023-03-08 09:10:49,463-INFO: uploading task(tscan_cpp) result(code:4) to server
> 2023-03-08 09:10:49,986-INFO: result upload finished

**Comment by ontheway01** [comment]
`/CodeAnalysis/client/data/taskdirs/task_251/task.log` 查看如下

> 2023-03-08 09:10:43,807-INFO: [Checking] [90/90, 100%] [1] [Done] /CodeAnalysis/client/data/sourcedirs/git_732hd91r/include/sql/sqlNsi.h
> 2023-03-08 09:10:43,814-INFO: Extra Header End
> 2023-03-08 09:10:43,854-WARNING: task status code is 4
> 2023-03-08 09:10:43,854-WARNING: task messsage: ParseError: not well-formed (invalid token): line 7, column 17
> 2023-03-08 09:10:43,855-WARNING: task result: 
> Traceback (most recent call last):
>   File "task/puppytask.py", line 63, in run
>     response = TaskRunner(self._request_file, self._response_file).run_task()
>   File "task/runtask.py", line 129, in task.runtask.__tskr__.__tskr__.run_task
>   File "/CodeAnalysis/client/task/taskmgr.py", line 73, in taskrunner
>     result = task.runner(params)
>   File "/CodeAnalysis/client/task/model/analyze.py", line 49, in runner
>     return self.tool.analyze(params)
>   File "/CodeAnalysis/client/tool/tscan_cpp.py", line 30, in analyze
>     issues = super().analyze(params, tc_home, bin_name, want_suffix)
>   File "/CodeAnalysis/client/tool/util/tscan.py", line 64, in analyze
>     issues.extend(self._format_issue(output_file))
>   File "/CodeAnalysis/client/tool/util/tscan.py", line 69, in _format_issue
>     result_tree = ET.parse(output_file)
>   File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
>     tree.parse(source, parser)
>   File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
>     self._root = parser._parse_whole(source)
>   File "<string>", line None
> xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 7, column 17
> 
> 2023-03-08 09:10:43,856-INFO: task result: /CodeAnalysis/client/data/taskdirs/task_251/task_response.json

**Comment by ontheway01** [comment]
/CodeAnalysis/client/data/taskdirs/task_251/task_response.json 如下

```json
{
 "task_version": "3.0",
 "status": 4,
 "message": "ParseError: not well-formed (invalid token): line 7, column 17",
 "result": "Traceback (most recent call last):\n  File \"task/puppytask.py\", line 63, in run\n    response = TaskRunner(self._request_file, self._response_file).run_task()\n  File \"task/runtask.py\", line 129, in task.runtask.__tskr__.__tskr__.run_task\n  File \"/CodeAnalysis/client/task/taskmgr.py\", line 73, in taskrunner\n    result = task.runner(params)\n  File \"/CodeAnalysis/client/task/model/analyze.py\", line 49, in runner\n    return self.tool.analyze(params)\n  File \"/CodeAnalysis/client/tool/tscan_cpp.py\", line 30, in analyze\n    issues = super().analyze(params, tc_home, bin_name, want_suffix)\n  File \"/CodeAnalysis/client/tool/util/tscan.py\", line 64, in analyze\n    issues.extend(self._format_issue(output_file))\n  File \"/CodeAnalysis/client/tool/util/tscan.py\", line 69, in _format_issue\n    result_tree = ET.parse(output_file)\n  File \"/usr/local/lib/python3.7/xml/etree/ElementTree.py\", line 1197, in parse\n    tree.parse(source, parser)\n  File \"/usr/local/lib/python3.7/xml/etree/ElementTree.py\", line 598, in parse\n    self._root = parser._parse_whole(source)\n  File \"<string>\", line None\nxml.etree.ElementTree.ParseError: not well-formed (invalid token): line 7, column 17\n",
 "files": null,
 "start_time": "2023-03-08 09:05:18",
 "end_time": "2023-03-08 09:10:43",
 "time_format": "%Y-%m-%d %H:%M:%S"
}
```

**Comment by didebughu** [comment]
代码源文件非UTF-8编码格式，导致扫描结果xml文件解析异常，目前已添加异常处理提示用户检查文件编码格式
