### ISSUE TITLE
docker启动访问错误

### ISSUE THREAD

**Issue by p4hi** [Tencent/CodeAnalysis#8]
docker-compose搭建后，登陆产生错误如下图
![image](https://user-images.githubusercontent.com/97092765/148039642-dbb3db36-aeaf-4873-81d2-fdcd5c756574.png)

**Comment by nickcdon** [comment]
@p4hi 需要执行docker-compose exec login-server /bin/bash
python manage.py createcachetable，麻烦参考docker-compose部署文档：https://github.com/Tencent/CodeAnalysis/blob/main/doc/deploy_dc.md

**Comment by p4hi** [comment]
已解决
