### ISSUE TITLE
【错误】管理后台项目管理页筛选功能无效

### ISSUE THREAD

**Issue by D0n9** [Tencent/CodeAnalysis#808]
/server/main/api/v2/teams/?limit=10&offset=0&check_status=1  这个接口的状态筛选参数 check_status 好像没生效。不管怎么选都是返回全量的数据。

看了代码，好像没有这块逻辑。

server/projects/main/apps/codeproj/apis/v2.py:29  
![image](https://user-images.githubusercontent.com/16030944/228267537-2e35b32a-6ac9-4b09-b22c-2e862eaf9165.png)

server/projects/main/apps/codeproj/api_filters/base.py:25 
![image](https://user-images.githubusercontent.com/16030944/228267642-3b617007-bc55-4b29-9b23-5e3df96466ae.png)

**Comment by nickcdon** [comment]
可以拉取最新代码，更新前端
