### ISSUE TITLE
Docker部署文档完善

### ISSUE THREAD

**Issue by m0re-work** [Tencent/CodeAnalysis#82]
使用Docker部署过程中
请增加
wait dbEnter password: 
.Enter password: 
两个字段的说明
![image](https://user-images.githubusercontent.com/59357339/148965469-b0581855-5928-495b-9923-d5fa1601e8e9.png)

**Comment by Lingghh** [comment]
这里的初始化脚本已补充说明，可以更新代码体验

**Comment by m0re-work** [comment]
Killed
1 error occurred:
	* Status: The command '/bin/sh -c mkdir -p log/ &&     pip install -U setuptools pip &&     pip install -r requirements.txt' returned a non-zero code: 137, Code: 137


service "main-server" is not running container #1
Sending build context to Docker daemon  1.613MB
Step 1/6 : FROM python:3.7.12-slim
 ---> d3c9ad326043
Step 2/6 : ARG EXTRA_TOOLS="gnupg curl wget jq vim-tiny net-tools procps python3-dev default-libmysqlclient-dev locales inotify-tools gcc subversion git telnet iputils-ping vim openssh-client"
 ---> Using cache
 ---> 4027bf0e6245
Step 3/6 : RUN set -ex && cd /     && apt-get update     && apt-get install -y --no-install-recommends $EXTRA_TOOLS     && apt-get update     && apt-get install -y mariadb-client     && apt-get clean     && echo "LC_ALL=zh_CN.UTF-8" >> /etc/environment     && echo "zh_CN.UTF-8 UTF-8" > /etc/locale.gen     && echo "LANG=zh_CN.UTF-8" > /etc/locale.conf     && locale-gen     && ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime     && rm -rf /var/cache/apt/* /root/.cache
 ---> Using cache
 ---> 8e3f43254e55
Step 4/6 : WORKDIR /var/www/django/codedog
 ---> Using cache
 ---> c64d8d3ca0b0
Step 5/6 : COPY . .
 ---> 5085fc34ed0a
Step 6/6 : RUN mkdir -p log/ &&     pip install -U setuptools pip &&     pip install -r requirements.txt
 ---> Running in 33526b9d9776

Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (57.5.0)
Collecting setuptools
  Downloading setuptools-60.5.0-py3-none-any.whl (958 kB)
Requirement already satisfied: pip in /usr/local/lib/python3.7/site-packages (21.2.4)
Killed
Sending build context to Docker daemon  1.613MB
Step 1/6 : FROM python:3.7.12-slim
 ---> d3c9ad326043
Step 2/6 : ARG EXTRA_TOOLS="gnupg curl wget jq vim-tiny net-tools procps python3-dev default-libmysqlclient-dev locales inotify-tools gcc subversion git telnet iputils-ping vim openssh-client"
 ---> Using cache
 ---> 4027bf0e6245
Step 3/6 : RUN set -ex && cd /     && apt-get update     && apt-get install -y --no-install-recommends $EXTRA_TOOLS     && apt-get update     && apt-get install -y mariadb-client     && apt-get clean     && echo "LC_ALL=zh_CN.UTF-8" >> /etc/environment     && echo "zh_CN.UTF-8 UTF-8" > /etc/locale.gen     && echo "LANG=zh_CN.UTF-8" > /etc/locale.conf     && locale-gen     && ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime     && rm -rf /var/cache/apt/* /root/.cache
 ---> Using cache
 ---> 8e3f43254e55
Step 4/6 : WORKDIR /var/www/django/codedog
 ---> Using cache
 ---> c64d8d3ca0b0
Step 5/6 : COPY . .
 ---> 22854c958f51
Step 6/6 : RUN mkdir -p log/ &&     pip install -U setuptools pip &&     pip install -r requirements.txt
 ---> Running in e2ac50ac740e

**Comment by Lingghh** [comment]
你使用的机器是什么配置呢？看起来是构建到一半被系统给killed，应该是内存不够用

**Comment by m0re-work** [comment]
Lighthouse的1C1G主机，这个配置是肯定不够用的，主要考虑到网络是硅谷地区的部署难度相对较低，我会汇总相关问题，后期会反馈
