### ISSUE TITLE
请问如何添加pmd的rules

### ISSUE THREAD

**Issue by mio4kon** [Tencent/CodeAnalysis#860]
当前规则如下，都是默认的。现在想增加p3c的rulesets。
![image](https://github.com/Tencent/CodeAnalysis/assets/8521943/51782e8b-dc4c-4d1c-840e-745eda6bfb35)

这里我尝试在这里加入测试规则。
![image](https://github.com/Tencent/CodeAnalysis/assets/8521943/588f0a45-285b-4d37-bd6b-f7c2457da3e2)

进入docker后执行 `python manage.py loadcheckers all --dirname open_source`
执行结果：
![image](https://github.com/Tencent/CodeAnalysis/assets/8521943/5b2a6ec6-967e-44b3-bd51-e3b9c5e11221)
但是在页面上还是搜不到新加的测试规则 _UseConcatOnce2_

求救这种应该怎么弄

**Comment by Lingghh** [comment]
看起来加载报错

可以先进docker容器后执行 `source configs/config.sh`，然后再运行`python manage.py loadcheckers pmd --dirname open_source`

如果有异常信息，麻烦贴一下

**Comment by mio4kon** [comment]
> 看起来加载报错
> 
> 可以先进docker容器后执行 `source configs/config.sh`，然后再运行`python manage.py loadcheckers pmd --dirname open_source`
> 
> 如果有异常信息，麻烦贴一下

可以了，感谢
