### ISSUE TITLE
重复代码分析，每次结果都是0，看执行日志所有被分析文件都被跳过了: Skipping xxx since it appears to be a symlink

### ISSUE THREAD

**Issue by wwwxxxx** [Tencent/CodeAnalysis#870]
[task_2649.log](https://github.com/Tencent/CodeAnalysis/files/12141368/task_2649.log)

**Comment by wwwxxxx** [comment]
辛苦大佬帮看下，有结论望回复

**Comment by cyw3** [comment]
麻烦确认下日志中涉及的文件 或者 某一级目录 是否是软链接？

**Comment by wwwxxxx** [comment]
已经解决了，确实是软链的问题。在线分析的。顺便问下，我们支持把度量分析做成可支持参数配置的方式吗？比如指定分析目录之类的

**Comment by wwwxxxx** [comment]
已经解决了，确实是软链的问题。在线分析的。顺便问下，我们支持把度量分析做成可支持参数配置的方式吗？比如指定分析目录之类的

**Comment by cyw3** [comment]
> 已经解决了，确实是软链的问题。在线分析的。顺便问下，我们支持把度量分析做成可支持参数配置的方式吗？比如指定分析目录之类的

- 支持了一些参数，可以查看分析方案中代码度量里面的配置。
- 可以在分析方案中设置过滤路径
