### ISSUE TITLE
Killed循环运行

### ISSUE THREAD

**Issue by m0re-work** [Tencent/CodeAnalysis#88]
Killed
Sending build context to Docker daemon  1.613MB
Step 1/6 : FROM python:3.7.12-slim
 ---> d3c9ad326043
Step 2/6 : ARG EXTRA_TOOLS="gnupg curl wget jq vim-tiny net-tools procps python3-dev default-libmysqlclient-dev locales inotify-tools gcc subversion git telnet iputils-ping vim openssh-client"
 ---> Using cache
 ---> 4027bf0e6245
Step 3/6 : RUN set -ex && cd /     && apt-get update     && apt-get install -y --no-install-recommends $EXTRA_TOOLS     && apt-get update     && apt-get install -y mariadb-client     && apt-get clean     && echo "LC_ALL=zh_CN.UTF-8" >> /etc/environment     && echo "zh_CN.UTF-8 UTF-8" > /etc/locale.gen     && echo "LANG=zh_CN.UTF-8" > /etc/locale.conf     && locale-gen     && ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime     && rm -rf /var/cache/apt/* /root/.cache
 ---> Using cache
 ---> 8e3f43254e55
Step 4/6 : WORKDIR /var/www/django/codedog
 ---> Using cache
 ---> c64d8d3ca0b0
Step 5/6 : COPY . .
 ---> 22854c958f51
Step 6/6 : RUN mkdir -p log/ &&     pip install -U setuptools pip &&     pip install -r requirements.txt
 ---> Running in e2ac50ac740e
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (57.5.0)
Collecting setuptools
  Downloading setuptools-60.5.0-py3-none-any.whl (958 kB)
Requirement already satisfied: pip in /usr/local/lib/python3.7/site-packages (21.2.4)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 57.5.0
    Uninstalling setuptools-57.5.0:
      Successfully uninstalled setuptools-57.5.0
Killed
Sending build context to Docker daemon  86.27kB
Step 1/6 : FROM python:3.7.12-slim
 ---> d3c9ad326043
Step 2/6 : ARG EXTRA_TOOLS="gnupg curl wget jq vim-tiny net-tools procps python3-dev default-libmysqlclient-dev locales inotify-tools gcc subversion git telnet iputils-ping vim openssh-client"
 ---> Using cache
 ---> 4027bf0e6245
Step 3/6 : RUN set -ex && cd /     && apt-get update     && apt-get install -y --no-install-recommends $EXTRA_TOOLS     && apt-get update     && apt-get install -y mariadb-client     && apt-get clean     && echo "LC_ALL=zh_CN.UTF-8" >> /etc/environment     && echo "zh_CN.UTF-8 UTF-8" > /etc/locale.gen     && echo "LANG=zh_CN.UTF-8" > /etc/locale.conf     && locale-gen     && ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime     && rm -rf /var/cache/apt/* /root/.cache
 ---> Using cache
 ---> 8e3f43254e55
Step 4/6 : WORKDIR /var/www/django/codedog
 ---> Using cache
 ---> c64d8d3ca0b0
Step 5/6 : COPY . .
 ---> 563e879a8cd5
Step 6/6 : RUN mkdir -p log/ &&     pip install -U setuptools pip &&     pip install -r requirements.txt
 ---> Running in 55874b73280d
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (57.5.0)
Collecting setuptools
  Downloading setuptools-60.5.0-py3-none-any.whl (958 kB)
Requirement already satisfied: pip in /usr/local/lib/python3.7/site-packages (21.2.4)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 57.5.0
    Uninstalling setuptools-57.5.0:
      Successfully uninstalled setuptools-57.5.0

**Comment by Lingghh** [comment]
这个地方不是循环运行，main-server、main-worker、main-beat等服务会分别构建，可以稍微等待一会
