### ISSUE TITLE
cppcheck增量分析因无cppcheck_result.xml异常

### ISSUE THREAD

**Issue by carsongyang2010** [Tencent/CodeAnalysis#898]
客户端版本：tca-client-v20230222.1-x86_64-linux.zip
这个分析项目跑全量分析没有问题，跑增量分析就报错了
任务执行异常FileNotFoundError:[Errno 2] No such file or directory:'cppdheck_result.xml
[cppcheck增量分析因无cppcheck_result.xml异常.docx](https://github.com/Tencent/CodeAnalysis/files/12367008/cppcheck.cppcheck_result.xml.docx)

**Comment by didebughu** [comment]
请问是部署方式是什么呢？是源码部署吗还是其他什么部署方式

**Comment by didebughu** [comment]
已对该问题进行修复，可以更新代码重新试下

**Comment by didebughu** [comment]
如仍有问题，请重新打开
