### ISSUE TITLE
因为之前没查看密码，密码跳过了，重新运行了一次compose_init.sh，现在报错了

### ISSUE THREAD

**Issue by michael1981** [Tencent/CodeAnalysis#9]
![image](https://user-images.githubusercontent.com/23006690/148041002-713fed6b-6f11-4622-bf15-13bf7920f1cd.png)

**Comment by sevck** [comment]
密码在compose_init.sh里面

**Comment by michael1981** [comment]
> 

后来找到密码了，然后再运行就这样了

**Comment by sevck** [comment]
docker ps 运行的删除

**Comment by Zishuhooo** [comment]
我也遇到这个报错，请问解决了吗。（试过评论里的删除镜像，没有用）

**Comment by Zishuhooo** [comment]
> 

更新docker-compose,重新运行即可

**Comment by michael1981** [comment]
@Zishuhooo 是更新docker-compose程序，还是更新文件呢？

**Comment by Zishuhooo** [comment]
> @Zishuhooo 是更新docker-compose程序，还是更新文件呢？

我是更新的docker-compose程序，卸载后重新装

**Comment by michael1981** [comment]
> > @Zishuhooo 是更新docker-compose程序，还是更新文件呢？
> 
> 我是更新的docker-compose程序，卸载后重新装

可以了，之前没注意docker-compose的版本，后来更新到2版本了，谢谢
