### ISSUE TITLE
云服务器无法部署

### ISSUE THREAD

**Issue by m0re-work** [Tencent/CodeAnalysis#91]
尝试Docker和web server部署均失败
腾讯云服务器，美国硅谷机房，CentOS7.6
均按照文档操作

**Comment by Lingghh** [comment]
这里在哪个步骤失败了呢？麻烦贴一下日志哈

**Comment by m0re-work** [comment]
7 errors occurred:
	* Status: The command '/bin/sh -c mkdir -p log/ &&     pip install -U setuptools pip &&     pip install -r requirements.txt' returned a non-zero code: 137, Code: 137
	* Status: The command '/bin/sh -c mkdir -p log/ &&     pip install -U setuptools pip &&     pip install -r requirements.txt' returned a non-zero code: 137, Code: 137
	* Status: fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x977850, 0x16)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0x7ffd279cbfc0 sp=0x7ffd279cbf90 pc=0x435d52
runtime.sysMap(0xc000000000, 0x4000000, 0xce2398)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc6 fp=0x7ffd279cc000 sp=0x7ffd279cbfc0 pc=0x418ee6
runtime.(*mheap).sysAlloc(0xcc7de0, 0x400000, 0x0, 0x3)
	/usr/local/go/src/runtime/malloc.go:727 +0x1e5 fp=0x7ffd279cc0a8 sp=0x7ffd279cc000 pc=0x40c885
runtime.(*mheap).grow(0xcc7de0, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:1344 +0x85 fp=0x7ffd279cc110 sp=0x7ffd279cc0a8 pc=0x428445
runtime.(*mheap).allocSpan(0xcc7de0, 0x1, 0x2d342d4d56002a00, 0xce23a8, 0x0)
	/usr/local/go/src/runtime/mheap.go:1160 +0x6b6 fp=0x7ffd279cc190 sp=0x7ffd279cc110 pc=0x4281f6
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:907 +0x65 fp=0x7ffd279cc1e8 sp=0x7ffd279cc190 pc=0x461da5
runtime.(*mheap).alloc(0xcc7de0, 0x1, 0x12a, 0x0)
	/usr/local/go/src/runtime/mheap.go:901 +0x85 fp=0x7ffd279cc238 sp=0x7ffd279cc1e8 pc=0x4276c5
runtime.(*mcentral).grow(0xcdac98, 0x0)
	/usr/local/go/src/runtime/mcentral.go:506 +0x7a fp=0x7ffd279cc280 sp=0x7ffd279cc238 pc=0x4188ba
runtime.(*mcentral).cacheSpan(0xcdac98, 0x40000)
	/usr/local/go/src/runtime/mcentral.go:177 +0x3e5 fp=0x7ffd279cc2f8 sp=0x7ffd279cc280 pc=0x418645
runtime.(*mcache).refill(0x7f8bdbdeb108, 0x2a)
	/usr/local/go/src/runtime/mcache.go:142 +0xa5 fp=0x7ffd279cc318 sp=0x7ffd279cc2f8 pc=0x417fe5
runtime.(*mcache).nextFree(0x7f8bdbdeb108, 0xcb102a, 0x7f8bdbdeb108, 0x7f8bb74cb000, 0x7ffd279cc3a8)
	/usr/local/go/src/runtime/malloc.go:880 +0x8d fp=0x7ffd279cc350 sp=0x7ffd279cc318 pc=0x40d10d
runtime.mallocgc(0x180, 0x96ce60, 0x7ffd279cc401, 0x7ffd279cc450)
	/usr/local/go/src/runtime/malloc.go:1061 +0x834 fp=0x7ffd279cc3f0 sp=0x7ffd279cc350 pc=0x40daf4
runtime.newobject(0x96ce60, 0x460ae0)
	/usr/local/go/src/runtime/malloc.go:1195 +0x38 fp=0x7ffd279cc420 sp=0x7ffd279cc3f0 pc=0x40df98
runtime.malg(0x8000, 0x0)
	/usr/local/go/src/runtime/proc.go:3520 +0x31 fp=0x7ffd279cc460 sp=0x7ffd279cc420 pc=0x4408f1
runtime.mpreinit(0xcb10c0)
	/usr/local/go/src/runtime/os_linux.go:340 +0x29 fp=0x7ffd279cc480 sp=0x7ffd279cc460 pc=0x432a09
runtime.mcommoninit(0xcb10c0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/proc.go:663 +0xf7 fp=0x7ffd279cc4c8 sp=0x7ffd279cc480 pc=0x439b57
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:565 +0xa5 fp=0x7ffd279cc520 sp=0x7ffd279cc4c8 pc=0x4396e5
runtime.rt0_go(0x7ffd279cc558, 0xa, 0x7ffd279cc558, 0x0, 0x0, 0xa, 0x7ffd279cde2a, 0x7ffd279cde4b, 0x7ffd279cde56, 0x7ffd279cde5b, ...)
	/usr/local/go/src/runtime/asm_amd64.s:214 +0x125 fp=0x7ffd279cc528 sp=0x7ffd279cc520 pc=0x469325
: exit status 2: unknown, Code: 1
	* Status: The command '/bin/sh -c mkdir -p log/ &&     pip install -U setuptools pip &&     pip install -r requirements.txt' returned a non-zero code: 137, Code: 137
	* Status: The command '/bin/sh -c apt-get update && apt-get install -y unzip procps && rm /etc/nginx/conf.d/default.conf' returned a non-zero code: 137, Code: 137
	* Status: fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x977850, 0x16)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0x7fffa7df2fd0 sp=0x7fffa7df2fa0 pc=0x435d52
runtime.sysMap(0xc000000000, 0x4000000, 0xce2398)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc6 fp=0x7fffa7df3010 sp=0x7fffa7df2fd0 pc=0x418ee6
runtime.(*mheap).sysAlloc(0xcc7de0, 0x400000, 0x0, 0x3)
	/usr/local/go/src/runtime/malloc.go:727 +0x1e5 fp=0x7fffa7df30b8 sp=0x7fffa7df3010 pc=0x40c885
runtime.(*mheap).grow(0xcc7de0, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:1344 +0x85 fp=0x7fffa7df3120 sp=0x7fffa7df30b8 pc=0x428445
runtime.(*mheap).allocSpan(0xcc7de0, 0x1, 0x2d342d4d56002a00, 0xce23a8, 0x0)
	/usr/local/go/src/runtime/mheap.go:1160 +0x6b6 fp=0x7fffa7df31a0 sp=0x7fffa7df3120 pc=0x4281f6
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:907 +0x65 fp=0x7fffa7df31f8 sp=0x7fffa7df31a0 pc=0x461da5
runtime.(*mheap).alloc(0xcc7de0, 0x1, 0x12a, 0x0)
	/usr/local/go/src/runtime/mheap.go:901 +0x85 fp=0x7fffa7df3248 sp=0x7fffa7df31f8 pc=0x4276c5
runtime.(*mcentral).grow(0xcdac98, 0x0)
	/usr/local/go/src/runtime/mcentral.go:506 +0x7a fp=0x7fffa7df3290 sp=0x7fffa7df3248 pc=0x4188ba
runtime.(*mcentral).cacheSpan(0xcdac98, 0x40000)
	/usr/local/go/src/runtime/mcentral.go:177 +0x3e5 fp=0x7fffa7df3308 sp=0x7fffa7df3290 pc=0x418645
runtime.(*mcache).refill(0x7f59a996f108, 0x2a)
	/usr/local/go/src/runtime/mcache.go:142 +0xa5 fp=0x7fffa7df3328 sp=0x7fffa7df3308 pc=0x417fe5
runtime.(*mcache).nextFree(0x7f59a996f108, 0xcb102a, 0x7f59a996f108, 0x7f598504f000, 0x7fffa7df33b8)
	/usr/local/go/src/runtime/malloc.go:880 +0x8d fp=0x7fffa7df3360 sp=0x7fffa7df3328 pc=0x40d10d
runtime.mallocgc(0x180, 0x96ce60, 0x7fffa7df3401, 0x7fffa7df3460)
	/usr/local/go/src/runtime/malloc.go:1061 +0x834 fp=0x7fffa7df3400 sp=0x7fffa7df3360 pc=0x40daf4
runtime.newobject(0x96ce60, 0x460ae0)
	/usr/local/go/src/runtime/malloc.go:1195 +0x38 fp=0x7fffa7df3430 sp=0x7fffa7df3400 pc=0x40df98
runtime.malg(0x8000, 0x0)
	/usr/local/go/src/runtime/proc.go:3520 +0x31 fp=0x7fffa7df3470 sp=0x7fffa7df3430 pc=0x4408f1
runtime.mpreinit(0xcb10c0)
	/usr/local/go/src/runtime/os_linux.go:340 +0x29 fp=0x7fffa7df3490 sp=0x7fffa7df3470 pc=0x432a09
runtime.mcommoninit(0xcb10c0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/proc.go:663 +0xf7 fp=0x7fffa7df34d8 sp=0x7fffa7df3490 pc=0x439b57
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:565 +0xa5 fp=0x7fffa7df3530 sp=0x7fffa7df34d8 pc=0x4396e5
runtime.rt0_go(0x7fffa7df3568, 0xa, 0x7fffa7df3568, 0x0, 0x0, 0xa, 0x7fffa7df3e2a, 0x7fffa7df3e4b, 0x7fffa7df3e56, 0x7fffa7df3e5b, ...)
	/usr/local/go/src/runtime/asm_amd64.s:214 +0x125 fp=0x7fffa7df3538 sp=0x7fffa7df3530 pc=0x469325
: exit status 2: unknown, Code: 1
	* Status: The command '/bin/sh -c mkdir -p log/ &&     pip install -U setuptools pip &&     pip install -r requirements.txt' returned a non-zero code: 137, Code: 137

**Comment by m0re-work** [comment]
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/usr/local/lib/python3.7/http/client.py", line 465, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.7/http/client.py", line 509, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 339, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 482, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 349, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    version=version,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 287, in __init__
    version=version,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 528, in _prepare_linked_requirement
    link, req.source_dir, self._download, self.download_dir, hashes
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 217, in unpack_url
    hashes=hashes,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 94, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/network/download.py", line 145, in __call__
    for chunk in chunks:
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/progress_bars.py", line 144, in iter
    for x in it:
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 87, in response_chunks
    decode_content=False,
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by m0re-work** [comment]
Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/moby/d473007fd222eaba7bf4e5f81e4e31a285b9c55d083640149c82766e3388ad1e/log.json: no such file or directory): runc did not terminate successfully: unknown

**Comment by m0re-work** [comment]
github回复太不方便了

**Comment by m0re-work** [comment]
能否更换一个反馈方式

**Comment by m0re-work** [comment]
邮箱:mail@m0re.work

**Comment by Lingghh** [comment]
> 7 errors occurred: * Status: The command '/bin/sh -c mkdir -p log/ && pip install -U setuptools pip && pip install -r requirements.txt' returned a non-zero code: 137, Code: 137 * Status: The command '/bin/sh -c mkdir -p log/ && pip install -U setuptools pip && pip install -r requirements.txt' returned a non-zero code: 137, Code: 137 * Status: fatal error: runtime: out of memory
> 
> runtime stack: runtime.throw(0x977850, 0x16) /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0x7ffd279cbfc0 sp=0x7ffd279cbf90 pc=0x435d52 runtime.sysMap(0xc000000000, 0x4000000, 0xce2398) /usr/local/go/src/runtime/mem_linux.go:169 +0xc6 fp=0x7ffd279cc000 sp=0x7ffd279cbfc0 pc=0x418ee6 runtime.(*mheap).sysAlloc(0xcc7de0, 0x400000, 0x0, 0x3) /usr/local/go/src/runtime/malloc.go:727 +0x1e5 fp=0x7ffd279cc0a8 sp=0x7ffd279cc000 pc=0x40c885 runtime.(*mheap).grow(0xcc7de0, 0x1, 0x0) /usr/local/go/src/runtime/mheap.go:1344 +0x85 fp=0x7ffd279cc110 sp=0x7ffd279cc0a8 pc=0x428445 runtime.(*mheap).allocSpan(0xcc7de0, 0x1, 0x2d342d4d56002a00, 0xce23a8, 0x0) /usr/local/go/src/runtime/mheap.go:1160 +0x6b6 fp=0x7ffd279cc190 sp=0x7ffd279cc110 pc=0x4281f6 runtime.(*mheap).alloc.func1() /usr/local/go/src/runtime/mheap.go:907 +0x65 fp=0x7ffd279cc1e8 sp=0x7ffd279cc190 pc=0x461da5 runtime.(*mheap).alloc(0xcc7de0, 0x1, 0x12a, 0x0) /usr/local/go/src/runtime/mheap.go:901 +0x85 fp=0x7ffd279cc238 sp=0x7ffd279cc1e8 pc=0x4276c5 runtime.(*mcentral).grow(0xcdac98, 0x0) /usr/local/go/src/runtime/mcentral.go:506 +0x7a fp=0x7ffd279cc280 sp=0x7ffd279cc238 pc=0x4188ba runtime.(*mcentral).cacheSpan(0xcdac98, 0x40000) /usr/local/go/src/runtime/mcentral.go:177 +0x3e5 fp=0x7ffd279cc2f8 sp=0x7ffd279cc280 pc=0x418645 runtime.(*mcache).refill(0x7f8bdbdeb108, 0x2a) /usr/local/go/src/runtime/mcache.go:142 +0xa5 fp=0x7ffd279cc318 sp=0x7ffd279cc2f8 pc=0x417fe5 runtime.(*mcache).nextFree(0x7f8bdbdeb108, 0xcb102a, 0x7f8bdbdeb108, 0x7f8bb74cb000, 0x7ffd279cc3a8) /usr/local/go/src/runtime/malloc.go:880 +0x8d fp=0x7ffd279cc350 sp=0x7ffd279cc318 pc=0x40d10d runtime.mallocgc(0x180, 0x96ce60, 0x7ffd279cc401, 0x7ffd279cc450) /usr/local/go/src/runtime/malloc.go:1061 +0x834 fp=0x7ffd279cc3f0 sp=0x7ffd279cc350 pc=0x40daf4 runtime.newobject(0x96ce60, 0x460ae0) /usr/local/go/src/runtime/malloc.go:1195 +0x38 fp=0x7ffd279cc420 sp=0x7ffd279cc3f0 pc=0x40df98 runtime.malg(0x8000, 0x0) /usr/local/go/src/runtime/proc.go:3520 +0x31 fp=0x7ffd279cc460 sp=0x7ffd279cc420 pc=0x4408f1 runtime.mpreinit(0xcb10c0) /usr/local/go/src/runtime/os_linux.go:340 +0x29 fp=0x7ffd279cc480 sp=0x7ffd279cc460 pc=0x432a09 runtime.mcommoninit(0xcb10c0, 0xffffffffffffffff) /usr/local/go/src/runtime/proc.go:663 +0xf7 fp=0x7ffd279cc4c8 sp=0x7ffd279cc480 pc=0x439b57 runtime.schedinit() /usr/local/go/src/runtime/proc.go:565 +0xa5 fp=0x7ffd279cc520 sp=0x7ffd279cc4c8 pc=0x4396e5 runtime.rt0_go(0x7ffd279cc558, 0xa, 0x7ffd279cc558, 0x0, 0x0, 0xa, 0x7ffd279cde2a, 0x7ffd279cde4b, 0x7ffd279cde56, 0x7ffd279cde5b, ...) /usr/local/go/src/runtime/asm_amd64.s:214 +0x125 fp=0x7ffd279cc528 sp=0x7ffd279cc520 pc=0x469325 : exit status 2: unknown, Code: 1 * Status: The command '/bin/sh -c mkdir -p log/ && pip install -U setuptools pip && pip install -r requirements.txt' returned a non-zero code: 137, Code: 137 * Status: The command '/bin/sh -c apt-get update && apt-get install -y unzip procps && rm /etc/nginx/conf.d/default.conf' returned a non-zero code: 137, Code: 137 * Status: fatal error: runtime: out of memory
> 
> runtime stack: runtime.throw(0x977850, 0x16) /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0x7fffa7df2fd0 sp=0x7fffa7df2fa0 pc=0x435d52 runtime.sysMap(0xc000000000, 0x4000000, 0xce2398) /usr/local/go/src/runtime/mem_linux.go:169 +0xc6 fp=0x7fffa7df3010 sp=0x7fffa7df2fd0 pc=0x418ee6 runtime.(*mheap).sysAlloc(0xcc7de0, 0x400000, 0x0, 0x3) /usr/local/go/src/runtime/malloc.go:727 +0x1e5 fp=0x7fffa7df30b8 sp=0x7fffa7df3010 pc=0x40c885 runtime.(*mheap).grow(0xcc7de0, 0x1, 0x0) /usr/local/go/src/runtime/mheap.go:1344 +0x85 fp=0x7fffa7df3120 sp=0x7fffa7df30b8 pc=0x428445 runtime.(*mheap).allocSpan(0xcc7de0, 0x1, 0x2d342d4d56002a00, 0xce23a8, 0x0) /usr/local/go/src/runtime/mheap.go:1160 +0x6b6 fp=0x7fffa7df31a0 sp=0x7fffa7df3120 pc=0x4281f6 runtime.(*mheap).alloc.func1() /usr/local/go/src/runtime/mheap.go:907 +0x65 fp=0x7fffa7df31f8 sp=0x7fffa7df31a0 pc=0x461da5 runtime.(*mheap).alloc(0xcc7de0, 0x1, 0x12a, 0x0) /usr/local/go/src/runtime/mheap.go:901 +0x85 fp=0x7fffa7df3248 sp=0x7fffa7df31f8 pc=0x4276c5 runtime.(*mcentral).grow(0xcdac98, 0x0) /usr/local/go/src/runtime/mcentral.go:506 +0x7a fp=0x7fffa7df3290 sp=0x7fffa7df3248 pc=0x4188ba runtime.(*mcentral).cacheSpan(0xcdac98, 0x40000) /usr/local/go/src/runtime/mcentral.go:177 +0x3e5 fp=0x7fffa7df3308 sp=0x7fffa7df3290 pc=0x418645 runtime.(*mcache).refill(0x7f59a996f108, 0x2a) /usr/local/go/src/runtime/mcache.go:142 +0xa5 fp=0x7fffa7df3328 sp=0x7fffa7df3308 pc=0x417fe5 runtime.(*mcache).nextFree(0x7f59a996f108, 0xcb102a, 0x7f59a996f108, 0x7f598504f000, 0x7fffa7df33b8) /usr/local/go/src/runtime/malloc.go:880 +0x8d fp=0x7fffa7df3360 sp=0x7fffa7df3328 pc=0x40d10d runtime.mallocgc(0x180, 0x96ce60, 0x7fffa7df3401, 0x7fffa7df3460) /usr/local/go/src/runtime/malloc.go:1061 +0x834 fp=0x7fffa7df3400 sp=0x7fffa7df3360 pc=0x40daf4 runtime.newobject(0x96ce60, 0x460ae0) /usr/local/go/src/runtime/malloc.go:1195 +0x38 fp=0x7fffa7df3430 sp=0x7fffa7df3400 pc=0x40df98 runtime.malg(0x8000, 0x0) /usr/local/go/src/runtime/proc.go:3520 +0x31 fp=0x7fffa7df3470 sp=0x7fffa7df3430 pc=0x4408f1 runtime.mpreinit(0xcb10c0) /usr/local/go/src/runtime/os_linux.go:340 +0x29 fp=0x7fffa7df3490 sp=0x7fffa7df3470 pc=0x432a09 runtime.mcommoninit(0xcb10c0, 0xffffffffffffffff) /usr/local/go/src/runtime/proc.go:663 +0xf7 fp=0x7fffa7df34d8 sp=0x7fffa7df3490 pc=0x439b57 runtime.schedinit() /usr/local/go/src/runtime/proc.go:565 +0xa5 fp=0x7fffa7df3530 sp=0x7fffa7df34d8 pc=0x4396e5 runtime.rt0_go(0x7fffa7df3568, 0xa, 0x7fffa7df3568, 0x0, 0x0, 0xa, 0x7fffa7df3e2a, 0x7fffa7df3e4b, 0x7fffa7df3e56, 0x7fffa7df3e5b, ...) /usr/local/go/src/runtime/asm_amd64.s:214 +0x125 fp=0x7fffa7df3538 sp=0x7fffa7df3530 pc=0x469325 : exit status 2: unknown, Code: 1 * Status: The command '/bin/sh -c mkdir -p log/ && pip install -U setuptools pip && pip install -r requirements.txt' returned a non-zero code: 137, Code: 137

这个异常是机器内存不足，提示“ fatal error: runtime: out of memory”，可以监测看看

**Comment by Lingghh** [comment]
> ERROR: Exception: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher yield File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 519, in read data = self._fp.read(amt) if not fp_closed else b"" File "/usr/local/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read data = self.__fp.read(amt) File "/usr/local/lib/python3.7/http/client.py", line 465, in read n = self.readinto(b) File "/usr/local/lib/python3.7/http/client.py", line 509, in readinto n = self.fp.readinto(b) File "/usr/local/lib/python3.7/socket.py", line 589, in readinto return self._sock.recv_into(b) File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into return self.read(nbytes, buffer) File "/usr/local/lib/python3.7/ssl.py", line 929, in read return self._sslobj.read(len, buffer) socket.timeout: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper status = run_func(*args) File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper return func(self, options, args) File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 339, in run reqs, check_supported_wheels=not options.target_dir File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve collected.requirements, max_rounds=try_to_avoid_resolution_too_deep File "/usr/local/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 482, in resolve state = resolution.resolve(requirements, max_rounds=max_rounds) File "/usr/local/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 349, in resolve self._add_to_criteria(self.state.criteria, r, parent=None) File "/usr/local/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria if not criterion.candidates: File "/usr/local/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in **bool** return bool(self._sequence) File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in **bool** return any(self) File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in return (c for c in iterator if id(c) not in self._incompatible_ids) File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built candidate = func() File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link version=version, File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 287, in **init** version=version, File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in **init** self.dist = self._prepare() File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare dist = self._prepare_distribution() File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True) File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement return self._prepare_linked_requirement(req, parallel_builds) File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 528, in _prepare_linked_requirement link, req.source_dir, self._download, self.download_dir, hashes File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 217, in unpack_url hashes=hashes, File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 94, in get_http_url from_path, content_type = download(link, temp_dir.path) File "/usr/local/lib/python3.7/site-packages/pip/_internal/network/download.py", line 145, in **call** for chunk in chunks: File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/progress_bars.py", line 144, in iter for x in it: File "/usr/local/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 87, in response_chunks decode_content=False, File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream data = self.read(amt=amt, decode_content=decode_content) File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 541, in read raise IncompleteRead(self._fp_bytes_read, self.length_remaining) File "/usr/local/lib/python3.7/contextlib.py", line 130, in **exit** self.gen.throw(type, value, traceback) File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher raise ReadTimeoutError(self._pool, None, "Read timed out.") pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

这里可以在机器终端执行``curl https://files.pythonhosted.org`` 试试，看看机器网络能否连通 pypi源
如果不行可以用腾讯云pypi源试试，参照配置：
```
$ mkdir ~/.pip/
$ echo "[global]\nindex-url = https://mirrors.cloud.tencent.com/pypi/simple" >> ~/.pip/pip.conf
```

**Comment by Lingghh** [comment]
> 能否更换一个反馈方式

这里建议还是在github issue反馈哈~这样其他同学遇到类似的问题也能快速看到解决方案，这边我们也会根据issue反馈进一步完善服务和文档哈

**Comment by Lingghh** [comment]
>wrong python version
从错误信息看起来是本地python版本不对，可以输出 python --version 确认一下是不是python3哈

**Comment by zhang9w0v5** [comment]
m0re-work 同学，这么积极，你遇到的问题我们一定重视。

**Comment by m0re-work** [comment]
目前使用在Lighthouse本地部署安装成功，主要的问题是文档部分命令缺失，而非产品自身问题
在重新测试Docker部署的问题，会评估TCA与腾讯云服务器产品相关的兼容性
有问题我会第一时间反馈各位
