### ISSUE TITLE
问题列表高级搜索无法输入

### ISSUE THREAD

**Issue by ningjunwei** [Tencent/CodeAnalysis#919]
![image](https://github.com/Tencent/CodeAnalysis/assets/79590928/0f67c65f-1fb3-4c89-8bd3-33645daf5bd7)

 main  分支
commit_id aa1fcced6409a45c442df860aa4f3726d4bb98e6

**Comment by ningjunwei** [comment]
![05883c4ec76d64389974c9624312da0](https://github.com/Tencent/CodeAnalysis/assets/79590928/a69f5d20-ddaf-4638-92ae-83e41a83ac52)
仓库登记这里也有这样的问题

**Comment by nickcdon** [comment]
已修复 #920
