### ISSUE TITLE
安全漏洞分析能力疑问

### ISSUE THREAD

**Issue by sz-sec** [Tencent/CodeAnalysis#92]
试着对DVWA漏洞靶场源码进行了代码分析，没有发现一个安全问题，请问是我配置的问题吗

![image](https://user-images.githubusercontent.com/97586009/149254898-622d9526-bfca-4fdf-8db9-9a9aefbcf5ac.png)

**Comment by nickcdon** [comment]
@sz-sec 可以查看分析方案里面的规则配置，看看是否有配置相关安全规则

**Comment by owlmk** [comment]
@sz-sec 分析方案->自定义规则包->添加规则->选 php 语言 安全类别 都加上去再看看

**Comment by sz-sec** [comment]
> @sz-sec 分析方案->自定义规则包->添加规则->选 php 语言 安全类别 都加上去再看看 另外我们有些工具因为一些原因暂未对开源版使用，可以在tca.tencent.com上体验看下

这些规则看起来并不像能匹配安全漏洞的，比如OWASP top10

![image](https://user-images.githubusercontent.com/97586009/149328343-3fc71b60-f1d7-418d-a1fc-d484d1455df9.png)

**Comment by sz-sec** [comment]
选择php类别 筛选出的规则只有几条，但搜索php关键字，插件就有很多。可能目前筛选功能还在完善，耐心等待中。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nickctang ***@***.***&gt;
发送时间: 2022年1月14日 10:14
收件人: Tencent/CodeAnalysis ***@***.***&gt;
抄送: sz-sec ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [Tencent/CodeAnalysis] 安全漏洞分析能力疑问 (Issue #92)

**Comment by owlmk** [comment]
刚更新了规则配置，可以更新代码重新部署下应该能直接看到php对应的安全规则包

**Comment by nickcdon** [comment]
@sz-sec 这边docker部署了一遍，搜索PHP安全规则应该可以看到171条规则。
![image](https://user-images.githubusercontent.com/18720809/149444719-219b71d8-4be6-483e-9e23-602c03e856a5.png)

**Comment by nickcdon** [comment]
> 刚更新了规则配置，可以更新代码重新部署下应该能直接看到php对应的安全规则包

@sz-sec 可在根目录下执行加载PHP基础安全规则包
```bash
git pull
docker-compsoe build
docker-compose up -d
docker-compose exec main-server /bin/bash -c "python manage.py loadpackages safety_php --dirname open_source_package"
```

目前需要重新先build，后续我们考虑优化部署脚本

**Comment by zhang9w0v5** [comment]
@sz-sec 请保持关注项目迭代。内部相关子工具，我们已经在为release进行迭代，预计2022春季能出来。
