### ISSUE TITLE
源码安装，只能访问到nginx

### ISSUE THREAD

**Issue by AzuoHealer** [Tencent/CodeAnalysis#93]
![image](https://user-images.githubusercontent.com/39117380/149259313-0cf0d984-4395-442e-9394-7bd46eed2d15.png)

**Comment by nickcdon** [comment]
@AzuoHealer 安装过程是否存在报错呢？麻烦看一下/etc/nginx/conf.d/目录的相关配置

**Comment by AzuoHealer** [comment]
安装过程中无报错，您看具体哪个配置？
![image](https://user-images.githubusercontent.com/39117380/149263425-1331ca76-8837-4634-b354-1eaeb68b93e1.png)

**Comment by AzuoHealer** [comment]
可以了，编译安装的nginx有问题，yum重装了一遍就可以了。
