### ISSUE TITLE
celery could not be found

### ISSUE THREAD

**Issue by m0re-work** [Tencent/CodeAnalysis#94]
celery could not be found
源码安装

**Comment by Lingghh** [comment]
这里执行完项目的依赖安装（通过``pip``安装后），可以在python安装路径下的``bin``目录找到``celery``可执行文件，然后建立一下软链：
```
# /path/to 请改为python安装路径下的``bin``目录的绝对路径
$ ln -s /path/to/celery /usr/local/bin/celery
```

**Comment by m0re-work** [comment]
![image](https://user-images.githubusercontent.com/59357339/149264093-0241a636-3113-4299-992c-ef2aa89f44ef.png)

**Comment by Lingghh** [comment]
这里链接错了，可以执行``ln -s /usr/local/python3/bin/celery /usr/local/bin/celery``

**Comment by RussGan** [comment]
这里重新软链接一下哈：

**Comment by RussGan** [comment]
这里重新软链接一下哈：`ln -s /usr/local/python3/bin/celery   /usr/local/bin/celery`
再执行一下：`export PATH=/usr/local/bin:$PATH`

**Comment by m0re-work** [comment]
❌ gunicorn could not be found
