### ISSUE TITLE
一直卡在init tools 可以自己去拉下来复制到client/data/tools文件夹内吗

### ISSUE THREAD

**Issue by yipeikk** [Tencent/CodeAnalysis#95]
![image](https://user-images.githubusercontent.com/50133499/149283103-f042707b-da03-4c5d-90ab-d7fa99ed652f.png)

**Comment by cyw3** [comment]
可以手动把这些工具都拉下来，存放到client/data/tools目录下。
https://github.com/TCATools

另外在client/config.ini的[common]中设置一个参数：
USE_LOCAL_TOOL=True
就可以不自动拉取工具，直接使用本地拉好的工具。

**Comment by yipeikk** [comment]
@cyw3 能知道具体需要拉哪些工具吗 这个地址上面 工具挺多的

**Comment by cyw3** [comment]
这里面工具分为linux/windows/mac三端的工具。可以按照你机器系统是什么来决定。

看到应该用的是windows，这里可以拉取common、custom和win开头的工具，和puppy-tools-config库

**Comment by yipeikk** [comment]
![image](https://user-images.githubusercontent.com/50133499/149306009-6581e78a-f530-4afa-9d1c-d8ef03088e63.png)
@cyw3 拉取完了所有工具 配置 了USE_LOCAL_TOOL=True 这个需要什么环境吗

**Comment by yql70** [comment]
> ![image](https://user-images.githubusercontent.com/50133499/149306009-6581e78a-f530-4afa-9d1c-d8ef03088e63.png) @cyw3 拉取完了所有工具 配置 了USE_LOCAL_TOOL=True 这个需要什么环境吗

[#86 ](https://github.com/Tencent/CodeAnalysis/issues/86#issuecomment-1010813015) 昨天修复了这个问题，麻烦更新下CodeAnalysis代码库，然后重启server服务，再重试下

**Comment by wushifeng** [comment]
JAVA工程的分析我在gitee上建了这些工具的镜像
具体看这个https://github.com/Tencent/CodeAnalysis/issues/86
具体配置参考 https://gitee.com/TCATools
