### ISSUE TITLE
无法邀请团队成员

### ISSUE THREAD

**Issue by ningjunwei** [Tencent/CodeAnalysis#954]
![image](https://github.com/Tencent/CodeAnalysis/assets/79590928/1bddb7f2-1ae2-4adb-8725-d30c5dfa5253)
![image](https://github.com/Tencent/CodeAnalysis/assets/79590928/1704c1c3-d557-4c3e-839d-85e7ec83504e)
在团队内邀请成员时，网页打开链接，提示  未找到
 
服务是采用源码构建部署的，对应信息如下：
Author: Jero <lingh0927@hotmail.com>
Date:   Thu Sep 21 10:13:51 2023 +0800

    Merge pull request #923 from yalechen-cyw/main

    :art: support overseas_product_code_security

commit 48875e75c6015809c7d12fc25dab563265f8d3bf

**Comment by glayyiyi** [comment]
用docker-compose方式部署，遇到了同样的问题，请看如何解决？

**Comment by nickcdon** [comment]
#971 done
