### ISSUE TITLE
仓库登记gitlab

### ISSUE THREAD

**Issue by AzuoHealer** [Tencent/CodeAnalysis#96]
![image](https://user-images.githubusercontent.com/39117380/149289338-0860500e-9dfc-469b-85b0-c61e7127294c.png)
![image](https://user-images.githubusercontent.com/39117380/149289355-09a42c2c-fba5-4dd1-a8dc-1f99a9b33f8b.png)
![image](https://user-images.githubusercontent.com/39117380/149289445-ead53936-082f-44cd-91d2-f52e0dd41b93.png)
账号密码无问题，但是登记失败。

**Comment by owlmk** [comment]
这是个ssh的地址，要用http的

**Comment by AzuoHealer** [comment]
http的也一样。。。

**Comment by AzuoHealer** [comment]
![image](https://user-images.githubusercontent.com/39117380/149299797-17554fb4-7764-4919-b6a7-2c9417acf628.png)
@owlmk

**Comment by color-way** [comment]
遇到相同的问题，帮忙解决一下

**Comment by Lingghh** [comment]
这里是采用docker-compose启动的么？
可以进入``scmproxy``看一下错误日志
```
docker-compose exec scmproxy /bin/bash
tail -n 100 logs/scmproxy.log
```

**Comment by AzuoHealer** [comment]
不是docker部署的

**Comment by michael1981** [comment]
我也问了同样的问题，他们后来都不回答了

**Comment by zhang9w0v5** [comment]
最好把log捞出来看看。大家并非全职跟进开源，时间精力比较紧张，我们这个项目是认真执行开源的，不会放着问题不管。

大家的环境各有千秋，可以先旁路测试一下当地环境在命令行git能否clone目标代码库。

**Comment by Lingghh** [comment]
> 不是docker部署的

可以在项目目录下执行``cd server/projects/scmproxy``，然后``tail -n 100 logs/scmproxy.log``看一下是否有报错内容

**Comment by AzuoHealer** [comment]
@Lingghh 抱歉哈，我在项目目录里没找到scmproxy.log
![image](https://user-images.githubusercontent.com/39117380/149438915-6531c03d-f3eb-4ad3-9a98-b9b15e4718e7.png)

**Comment by AzuoHealer** [comment]
我找到问题了，ScmProxy这个服务没自动起。有这个服务的启动说明文档吗？

**Comment by AzuoHealer** [comment]
![image](https://user-images.githubusercontent.com/39117380/149445674-c93a40af-9d07-4316-91b7-dd3ccfe7013e.png)
