### ISSUE TITLE
基于客户端分析模式，怎么获取git代码的详情，代码库12G

### ISSUE THREAD

**Issue by zzzfwww** [Tencent/CodeAnalysis#968]
想要问下，https://tencent.github.io/CodeAnalysis/zh/guide/%E5%AE%A2%E6%88%B7%E7%AB%AF/%E6%9C%AC%E5%9C%B0%E5%88%86%E6%9E%90.html 

基于这个客户端本地分析，分析完成之后的结果上报到服务端，然后页面展示这里/teams/server/repos/11/projects/23/codefile  codefile接口一直报超时的问题，这个我进入services的容器内部，发现确实一直在git拉取代码，由于我这个库有10G，导致一直再拉，等很久看这个里面拉取到10G  再次点击，还是发现又重新清空了又重新拉取，这个问题怎么解决

可不可以有一个机制，tca容器里面支持从外部挂载代码目录进去，这个代码的准确与否交还给使用者，你看下这个可以嘛？如果可以你们那边有没有计划进行优化

另外像我这种情况你们那边有没有什么建议可以解决这个问题

**Comment by Lingghh** [comment]
如果内部有用私有化gitlab，可以试试配置OAuth授权，这样服务端展示代码时可以通过接口到平台获取，不用整个代码库拉取下来

**Comment by zzzfwww** [comment]
<img width="811" alt="image" src="https://github.com/Tencent/CodeAnalysis/assets/3351405/6e53ad8a-591a-424b-98c2-74a58ace0c8a">
看到了这个地方，我周一试试看
