### ISSUE TITLE
query result from server ...

### ISSUE THREAD

**Issue by yipeikk** [Tencent/CodeAnalysis#97]
![image](https://user-images.githubusercontent.com/50133499/149440953-844c1905-26e6-4724-8cdc-05eda931769c.png)

配置的文件服务器地址和token是正确的

服务那边日志只有这些
![image](https://user-images.githubusercontent.com/50133499/149441079-2d011234-7cce-4105-a254-f18868f7440e.png)

**Comment by yipeikk** [comment]
最后出现了入库失败的错误

**Comment by yipeikk** [comment]
![image](https://user-images.githubusercontent.com/50133499/149441462-7bd77287-3bda-4e54-bd92-d1e97a328764.png)

**Comment by yipeikk** [comment]
![image](https://user-images.githubusercontent.com/50133499/149441716-fd8ee6bd-e201-447c-8cc0-86f97cd297f5.png)

**Comment by yipeikk** [comment]
celery日志
![image](https://user-images.githubusercontent.com/50133499/149443477-803de3b4-70ab-4f6b-ab98-05a38e7fd988.png)

**Comment by Lingghh** [comment]
目前看起来是在analysis-worker中无法访问 ``192.168.2.224`` 地址，请问这个IP地址是VM对外的IP还是容器内的IP

**Comment by yipeikk** [comment]
> 

对外的ip地址 就是server的ip地址

**Comment by yipeikk** [comment]
> 目前看起来是在analysis-worker中无法访问 `192.168.2.224` 地址，请问这个IP地址是VM对外的IP还是容器内的IP

![image](https://user-images.githubusercontent.com/50133499/149460528-f5c6e9e7-ebb0-4b6b-bc5e-76dac1c15326.png)
查看 能够访问 192.168.2.224

**Comment by Lingghh** [comment]
可以在analysis-worker容器执行 curl 文件下载链接试试

**Comment by yipeikk** [comment]
> 可以在analysis-worker容器执行 curl 文件下载链接试试

确实下载不了 这是不是代表analysis-worker没有这个tmp.zip文件呢？ 我看了一下客户端这边
![image](https://user-images.githubusercontent.com/50133499/149463492-1dbc5738-43e6-43cf-9826-1f055ba2be33.png)
这个是不是具体的分析结果文件？

**Comment by yipeikk** [comment]
> 这个是一部分结果文件，下载不了有提示什么报错么？

提示 no route to host
我在sever-file 这个容器的data目录下搜索了一下这个tmp.zip 也不能够搜索到
我有什么办法确定这个文件确实已经生成了吗？

**Comment by Lingghh** [comment]
``no route to host`` 这个可能是防火墙限制，可以关闭宿主机的防火墙试试

**Comment by yipeikk** [comment]
> 



> `no route to host` 这个可能是防火墙限制，可以关闭宿主机的防火墙试试
确实是防火墙影响 谢谢
