### ISSUE TITLE
扫描完成后查看问题列表文件,报“获取代码信息耗时较久，请稍后再试”

### ISSUE THREAD

**Issue by 297791083** [Tencent/CodeAnalysis#99]
错误信息如下：
![image](https://user-images.githubusercontent.com/97274579/149488952-36ad1fe3-a97d-41e0-818b-3d63b80c584a.png)
![image](https://user-images.githubusercontent.com/97274579/149489006-51bc75dd-6149-4c52-859c-0e639c64fa66.png)

**Comment by zhang9w0v5** [comment]
当前版本，建议私有化部署TCA，以及使用私有化的Git，这是友好体验的内部经验。通过公网会有一些网络因素或Git服务的因素，可能带来拉取代码的问题。
